### ISSUE TITLE
FeatureRequest: 引入更多 flutter 组件

### ISSUE THREAD

**Issue by zacksleo** [mpflutter/mpflutter#100]
1. Divider 看起来是可以用的，可能需要把Theme支持的部分去掉？
2. 其他更多组件，如 IconButton，ListTile

**Comment by PonyCui** [comment]
有计划引入精简的 material 库，不过这可能增大最终产物，开发者需要作权衡。

**Comment by zacksleo** [comment]
像 Input，Theme 这些 widget 不可用的原因是什么呢

**Comment by PonyCui** [comment]
> 

会增大包体积

**Comment by zacksleo** [comment]
包的大小，还是交给开发者来权衡吧，毕竟类似于Input, ListTile, Button 这种组件还是很常用的

**Comment by PonyCui** [comment]
是的，所以我们还是会提供一个精简的 material 库让开发者自行选择。
