### ISSUE TITLE
如何发布、调试小程序

### ISSUE THREAD

**Issue by doubletcjs** [mpflutter/mpflutter#103]
写好的项目，如何发布到小程序。现在只能写本地ip，发到体验版小程序，并且本地开发工具一定要开调试模式才能查看，动不动就白屏、页面变形

**Comment by zacksleo** [comment]
`dart scripts/build_weapp.dart` 之后生成build文件，把这个文件夹上传小程序就可以了

**Comment by doubletcjs** [comment]
app.js下
engine.initWithDebuggerServerAddr("127.0.0.1:9898");

这个地址不需要改？

**Comment by zacksleo** [comment]
这个是开发/debug 的时候用的，见 https://mpflutter.com/zh/docs/first-app-weapp/#%E7%9C%9F%E6%9C%BA%E8%B0%83%E8%AF%95

build 发布以后不会用到这个
