### ISSUE TITLE
TableRow 中的 decoration 不起作用

### ISSUE THREAD

**Issue by zacksleo** [mpflutter/mpflutter#106]
`const TableRow(decoration: BoxDecoration(color: Colors.blue),)`, 没有出现背景色

**Comment by zacksleo** [comment]
0.13.0 还是不起作用

**Comment by PonyCui** [comment]
给一个完整的 dart 文件看看？我在 sample 中测试过是 OK 的。

**Comment by zacksleo** [comment]
https://gist.github.com/zacksleo/e667bd3a4b2c4d78646ae7b9daa81265

**Comment by PonyCui** [comment]
更新至 0.13.1 应该可以正常使用。
另外，根据 flutter 文档说明，TableRow 下的 children 必须使用 TableCell 包裹，否则 decoration 不能生效。

**Comment by zacksleo** [comment]
> 更新至 0.13.1 应该可以正常使用。 另外，根据 flutter 文档说明，TableRow 下的 children 必须使用 TableCell 包裹，否则 decoration 不能生效。

在TableRow 中使用decoration, 官方示例中是有的

见示例代码 https://api.flutter.dev/flutter/widgets/Table-class.html

```dart
        TableRow(
          decoration: const BoxDecoration(
            color: Colors.grey,
          ),
          children: <Widget>[
            Container(
              height: 64,
              width: 128,
              color: Colors.purple,
            ),
            Container(
              height: 32,
              color: Colors.yellow,
            ),
            Center(
              child: Container(
                height: 32,
                width: 32,
                color: Colors.orange,
              ),
            ),
          ],
        ),
```

**Comment by PonyCui** [comment]
已在 0.14.0 版本修复上述问题。
