### ISSUE TITLE
请问WechatMiniProgramButton返回值中的加密方式是什么？

### ISSUE THREAD

**Issue by Flonger** [mpflutter/mpflutter#111]
WechatMiniProgramButton(
                  openType: 'getPhoneNumber',
                  onGetPhoneNumber: (value) {
                    print('11111');
                    print(value); //这里返回的是加密的东西，请问怎么解密？
                  },
                  child: Container(
                    color: Colors.blue,
                    child: Align(
                      alignment: Alignment.center,
                      child: Text(
                        '获取手机号',
                        style: TextStyle(fontSize: 15, color: Colors.black87),
                      ),
                    ),
                  ),
                )

**Comment by PonyCui** [comment]
你可以阅读微信小程序相关文档解决问题

**Comment by Flonger** [comment]
找到原因了，模拟器调试的时候不返回code，只有与真机调试才会返回code，多谢

**Comment by PonyCui** [comment]
也有可能是你的微信开发者工具太旧，或者运行库版本太低。
