### ISSUE TITLE
用 mpflutter 写了个小程序，说说体验

### ISSUE THREAD

**Issue by OHeroJ** [mpflutter/mpflutter#112]
![gh_d1a005e59c3b_430 (1)](https://user-images.githubusercontent.com/12316547/159653161-4dfe1ea5-ef8b-4413-bab9-fc64a5e65c99.jpg)

整体开发还是比较流程，只是有些地方会出现莫名问题，比如 SizedBox 设置宽高都没效果，换成 Container 就好了，还有就是 ListView 应该还有些问题。

flutter_markdown 的渲染也还有问题，可从这个小程序中看出，pre 的渲染有问题。

tab 的点击有些卡顿。

因为小程序整体比较简单，问题出现不多，有些也已经在之前反馈过。

mpflutter 希望越来越好。好项目，千万别断更了哇 🙏🏻

**Comment by PonyCui** [comment]
感谢支持，上述反馈的问题已经用小笔笔记下了。

**Comment by OHeroJ** [comment]
> 

好东西，会在群里宣传推广。大佬牛逼

**Comment by doubletcjs** [comment]
从入门到放弃

**Comment by PonyCui** [comment]
> 从入门到放弃。复杂点的功能就hold不住了。

遇到什么复杂场景，不妨说说，提个 issue？

**Comment by PonyCui** [comment]
使用 0.14.0 版本已经可以解决 MainTabView keepAlive 问题。

**Comment by PonyCui** [comment]
> 

GitHub 就是最好的技术交流渠道
