### ISSUE TITLE
对mpflutter开发小程序的一些疑问

### ISSUE THREAD

**Issue by philos3** [mpflutter/mpflutter#113]
之前使用flutter开发，现在准备使用mpflutter开发小程序，有以下疑问：
1、flutter的第三方库怎么知道哪些支持，哪些不支持？还是只支持大佬已经适配过的比如getx？
2、getx第三方库更新是否无缝，flutter版本是否同步支持最新版本？
3、./mpflutter packages get的log信息，添加get: ^4.6.1依赖 执行命令后，无log，写代码的时候没有引入成功，这种问题怎么排查？
![image](https://user-images.githubusercontent.com/8424317/159965932-12c176a4-e46b-42a2-a699-4b056ff23b7c.png)

**Comment by philos3** [comment]
项目在androidstudio打开之后，执行命令dio报错，这个不支持吗？如何扩展呢

Because lightsnail_wx depends on dio ^4.0.3 which doesn't match any versions, version solving failed.
Running "flutter pub get" in lightsnail_wx...                           
pub get failed (1; Because lightsnail_wx depends on dio ^4.0.3 which doesn't match any
versions, version solving failed.)

**Comment by philos3** [comment]
注释掉dio，执行命令仍然报错
pub get failed (1; Because lightsnail_wx depends on get ^4.6.1 which doesn't match any
versions, version solving failed.)

**Comment by PonyCui** [comment]
dependency_overrides:
    dio: ^4.0.0
    get: ^4.3.9
只能使用文档上说明的版本，./mpflutter packages get 是有 log 提示的，在命令行下执行。

**Comment by philos3** [comment]
> dependency_overrides: dio: ^4.0.0 get: ^4.3.9 只能使用文档上说明的版本，./mpflutter packages get 是有 log 提示的，在命令行下执行。

这个限制有点多，为什么只能限制固定版本呢，如果第三方需要支持，有没有扩展文档呢？

**Comment by PonyCui** [comment]
因为 MPFlutter 官方对 get 和 dio 做了一定的修改以适配小程序使用，MPFlutter 提供的版本一般是最后一个大版本，不会在 API 上有较大的差异，使用推荐的版本就可以。
如果需要更高版本，你可以自行 fork 对应的仓库修改后使用。
