### ISSUE TITLE
MPFlutter体验

### ISSUE THREAD

**Issue by oom2android** [mpflutter/mpflutter#114]
进度：目前完成一部分UI开发，接口还没搞，现在爬视频地址有点难搞

录屏地址 [https://blog.oom2android.xyz/upload/2022/03/20220325153907-2dc0a2b892394ffc926f1e9291ae7cb2.webm](https://blog.oom2android.xyz/upload/2022/03/20220325153907-2dc0a2b892394ffc926f1e9291ae7cb2.webm)

![uTools_1648193143912](https://user-images.githubusercontent.com/101734710/160080558-7e4e414e-d1ab-4e9e-9d3d-d14207bd0c8e.png)![uTools_1648193125289](https://user-images.githubusercontent.com/101734710/160080585-4ab32d16-05e2-4870-9cc9-f8a53fc7b390.png)
![uTools_1648193097138](https://user-images.githubusercontent.com/101734710/160080599-6ded3179-7165-4b2e-bd38-80ed9b199fb5.png)![uTools_1648193075299](https://user-images.githubusercontent.com/101734710/160080615-6af68b5c-40b0-4a93-ad9c-4172fec47396.png)

遇到的问题：

1. 不支持IndexedStack，底部Tab切换无法保存界面状态。解决方法 ：通过Visibility显示隐藏界面。
2. ListView 水平滚动无法隐藏滚动条。解决方法：在微信小程序app.wxss 添加 ::-webkit-scrollbar {
  width: 0;
  height: 0;
  color: transparent;
  } ，全局隐藏滚动条。

3. 一级界面 appBar 无法显示 ，二级界面可以，不知道是不是只有我的有问题。解决方法：在body里面实现。
4. 页面跳转白屏时间有点长。
5. 第三方轮播好像不支持。解决方法：自己写 ，通过MPPageView +Timer 实现。
6. 等等

第三方支持比较少，好多东西要自己搞。但是能用flutter开发小程序还是挺不错的，希望MPFlutter越来越好，哈哈哈，加油。

**Comment by PonyCui** [comment]
问题 1 已经有解决方案啦，使用 0.14.0 版本，设置 MainTabView 中的 keepAlive 属性为 true 即可。
其它问题，也在探索解决方案中。

**Comment by PonyCui** [comment]
问题 5 已经可以解决，MPPageView 在 0.14.1 版本中已经有 autoplay 参数 。
