### ISSUE TITLE
使用微信小程序的内置swiper组件时无法包含多个swiper-item

### ISSUE THREAD

**Issue by xiaoyao20084321** [mpflutter/mpflutter#126]
使用微信小程序的内置swiper组件时无法包含多个swiper-item，目前只能包含一个，因为只有一个child，没有children
![image](https://user-images.githubusercontent.com/10344550/160746912-fb1833b5-4501-4bf6-92ac-0e5e071b4591.png)
![image](https://user-images.githubusercontent.com/10344550/160746918-b80d5dd1-9f1e-4ccc-ada6-43dc225f0d23.png)

**Comment by PonyCui** [comment]
0.14.1 版本中已经支持 MPMiniProgramView.children 。

**Comment by hewang42** [comment]
那如何修改 indicator dots 的样式呢，比如改变位置，改变形状
