### ISSUE TITLE
是否提供禁用滑动功能

### ISSUE THREAD

**Issue by pangoo-reuse** [mpflutter/mpflutter#129]
`SingleChildScrollView(
        child: Container(
          width: size.width,
          height: size.height,
          color: Colors.grey[100],
          child: MPMiniProgramView(
            tag: "map",
            attributes: {"longitude": 121.620802, "latitude": 31.290517,"enable-scroll":true},
          ),
        ),
        // physics: BouncingScrollPhysics(),
      )`

如上，如果微信的组件可以滑动则会出现冲突，flutter 自身滑动会拦截掉map的滑动事件

**Comment by PonyCui** [comment]
理应提供一个禁止页面滑动的能力，如果页面中没有 root 级别的 ScrollView 时，应默认禁止页面滚动。

**Comment by PonyCui** [comment]
这个问题出现在 android 上吗？iOS 不会有这个问题。

**Comment by PonyCui** [comment]
问题已修复，可以升级至 0.14.2 解决。

**Comment by pangoo-reuse** [comment]
然而地图还是不能滑动，是否是拦截了滑动事件？

**Comment by PonyCui** [comment]
使用 https://mpflutter.com/zh/docs/weapp-api#wechatminiprogrammapview WechatMiniProgramMapView 试试

**Comment by pangoo-reuse** [comment]
body:           Container(
        color: Colors.yellow,
        child: WechatMiniProgramMapView(
          longitude: 121.620802,
          latitude: 31.290517,
          enableScroll: true,
        ),
      )
单纯就只有这样，真机上不能滑动

**Comment by quan327886341** [comment]
我也遇到这个问题，地图在真机调试时不能滑动，模拟器可以滑动
