### ISSUE TITLE
用 mpflutter 写了第二个小程序，反馈下问题。

### ISSUE THREAD

**Issue by OHeroJ** [mpflutter/mpflutter#136]
基于mpflutter 0.14.1 开发。

本来按第一个开发的流畅度，预计一天就可以完成的。可是实践下来花费实践了2天。还有很多问题均发布到了 issues 上。

* https://github.com/mpflutter/mpflutter/issues/134
* https://github.com/mpflutter/mpflutter/issues/133
* https://github.com/mpflutter/mpflutter/issues/132
* https://github.com/mpflutter/mpflutter/issues/131
* https://github.com/mpflutter/mpflutter/issues/130

个人觉得3个非常亟需解决的问题：
* `Expanded` 和 `MPEditText` 这两控件是高频组件，但是问题在微信小程序比较突出
* 还有是页面刷新问题，网络请求后刷新页面状态，莫名会多出一次刷新。 而因多出的这次刷新会让页面布局，比如 Text 明明是有数据给过去，但是就没有展示出来。
* `MPScafold(body: xxxx)`,  想问的是它默认是滚动的么？因为嵌入 mp 的滚动组件，侧边栏的滚动条莫名会出现 2 个。所以滚动的时候还有卡死现象

**Comment by PonyCui** [comment]
> MPScafold(body: xxxx), 想问的是它默认是滚动的么？因为嵌入 mp 的滚动组件，侧边栏的滚动条莫名会出现 2 个。所以滚动的时候还有卡死现象
关于这个问题，会在 0.14.2 中解决，已经有解决方案。

**Comment by PonyCui** [comment]
这些问题应该都在 0.14.2 中得到解决了
