### ISSUE TITLE
这项目太棒了，请教几个小问题。

### ISSUE THREAD

**Issue by ThrLi** [mpflutter/mpflutter#137]
首先感谢大佬辛苦作出如此神作，可千万别断更啊！
之前接触过Flutter开发，最近手上有几个微信小程序项目想用MP来做，想咨询一下：
1，在加入第三方的时候，如何知道可以使用哪些版本？我找了一圈，没找到MP可以支持的第三方版本的相关说明文档。
2，是否有QQ或微信交流群之类的地方？除了Issues没有其他联系大佬的地方了吗？
3，随着微信小程序的版本迭代，MP和微信小程序之间的适配是否会出现断层？我们自己是否可以自行补救？又该如何做呢？
十分感谢大佬抽出宝贵时间回答这几个小问题。

**Comment by PonyCui** [comment]
你好。
关于问题一，可以关注文档中的[外部工具库](https://mpflutter.com/zh/docs/lib-getx)栏目，这里会推出兼容 MP 的第三方库。对于其它库，如果是纯 dart 的不涉及 dart:ui 和 material 的库都可以直接使用，使用方式和原有的 Flutter 用法一致。对于不兼容的库，你可以自行 fork 后，去掉 dart:ui 和 material 就可以使用。
关于问题二，建议是通过 Issue 解决问题，这样比较容易沉淀记录。
关于问题三，微信小程序和其它小程序已经相对稳定了，不太会有断层的情况，如果有，可以提 issue，是可以解决的。

**Comment by ThrLi** [comment]
感谢大佬，另外请问一下，MP中是否支持第三方的图表插件和第三方的视频插件？比如柱状图，饼状图之类的还有一些播放器，这块使用频率还是挺高的，不过在[外部工具库](https://mpflutter.com/zh/docs/lib-getx)中好像没有这一块内容。

**Comment by PonyCui** [comment]
> 感谢大佬，另外请问一下，MP中是否支持第三方的图表插件和第三方的视频插件？比如柱状图，饼状图之类的还有一些播放器，这块使用频率还是挺高的，不过在[外部工具库](https://mpflutter.com/zh/docs/lib-getx)中好像没有这一块内容。

最近会兼容一个 chart 插件，可以关注一下。

**Comment by PonyCui** [comment]
视频组件可以使用内置的 MPVideoView

**Comment by ThrLi** [comment]
好的，十分期待，感谢大佬的解答，祝愿MP越来越好！

**Comment by PonyCui** [comment]
如果后续有问题可以新开 issue 提问，十分乐意帮助各位解决问题。
