### ISSUE TITLE
请问是否支持地图插件？

### ISSUE THREAD

**Issue by ThrLi** [mpflutter/mpflutter#138]
小程序中有需要用到展示店铺地图的截图以及点击后进入微信地图导航界面，请问MP目前是否支持？该如何实现呢？

**Comment by PonyCui** [comment]
请阅读文档 https://mpflutter.com/zh/docs/weapp-api#wechatminiprogrammapview
使用 universal_miniprogram_api 调用微信 openLocation API 即可
