### ISSUE TITLE
MPMainTabView安全区域问题

### ISSUE THREAD

**Issue by xiaoyao20084321** [mpflutter/mpflutter#139]
微信小程序：
使用MPMainTabView后， 底部tab安全区域出现问题
![image](https://user-images.githubusercontent.com/10344550/161941533-c2e40083-7fe2-433e-bf05-ddc69e07dc9b.png)
![image](https://user-images.githubusercontent.com/10344550/161941561-015fd81b-ba33-4ce6-8c09-0fa801355e70.png)

**Comment by PonyCui** [comment]
问题已修复，可以升级至 0.14.2 解决。
