### ISSUE TITLE
使用GetX的GetMpApp组件时候，如果不指定color，控制台会报错，并且项目无法运行

### ISSUE THREAD

**Issue by xiaoyao20084321** [mpflutter/mpflutter#140]
使用GetX的GetMpApp组件时候，如果不指定color，控制台会报错，并且项目无法运行，color不应该是必须属性，

**Comment by PonyCui** [comment]
已在 https://github.com/mpflutter/mpflutter/commit/0aba2c84af12252f57c3da7560a2cbf9ce700351 修复，跟随下一版本发布。
version > 0.14.3
