### ISSUE TITLE
MPMainTabView新的安全区域问题（不确定是不是微信小程序开发者的问题）

### ISSUE THREAD

**Issue by xiaoyao20084321** [mpflutter/mpflutter#141]
微信小程序里，多次进行重启刷新项目， 会出现多出安全区域问题。复现如下
1、启动项目，此时微信小程序界面正常
2、多次重启刷新项目，此时出现问题
3、在微信小程序开发工具选择换一个模拟器，界面又变回正常，此时就算变回原来的模拟器，还会是正常现象

下面是出现问题时候的图
![image](https://user-images.githubusercontent.com/10344550/162158398-639d1329-e8b6-4f36-8015-967085b31324.png)

（注：MP官方项目如：   git clone https://github.com/mpflutter/mpflutter_template.git awesome_project 多次重启刷新项目，在小程序模拟器上也会偶现不会居中的问题，也是切换模拟器就会好了 ）

**Comment by PonyCui** [comment]
这个问题应该在0.16.3 修正了
