### ISSUE TITLE
反编译问题

### ISSUE THREAD

**Issue by capy9** [mpflutter/mpflutter#142]
想请问下是否比别的框架不易被反编译，只发布小程序版本的话.

**Comment by PonyCui** [comment]
那是肯定的，dart2js 会编译成非常精简的代码，但是对于反编译专业人士而言，也没什么特别大的难度。

**Comment by capy9** [comment]
> 那是肯定的，dart2js 会编译成非常精简的代码，但是对于反编译专业人士而言，也没什么特别大的难度。

谢谢
