### ISSUE TITLE
Appbar 在小程序显示问题

### ISSUE THREAD

**Issue by pangoo-reuse** [mpflutter/mpflutter#145]
Appbar 在微信小程序里面不能置顶到微信原生的Titlebar位置，请问是否测试过？

**Comment by PonyCui** [comment]
要隐藏微信自带的 AppBar，你需要配置页面参数。
https://mpflutter.com/zh/docs/weapp-route-page#生成小程序实体-page
MPScaffold 并没有能力动态替换。

**Comment by PonyCui** [comment]
如果需要全局隐藏微信自带的导航栏，可以直接修改 pages/index/index.json 中的设置。
