### ISSUE TITLE
怎么调用文件选择的方法

### ISSUE THREAD

**Issue by xxvendor** [mpflutter/mpflutter#148]
咨询一下，我们当前项目有文件选择的功能，以前用的是flutter的插件，但是该插件只支持Android ios 和web，如果需要通过mpflutter打包成小程序和h5，这一块该怎么实现呢，在build好的代码中进行重新实现吗

**Comment by PonyCui** [comment]
我会写一个插件帮助你实现这个功能

**Comment by kksqql** [comment]
感谢

**Comment by PonyCui** [comment]
https://mpflutter.com/zh/docs/lib-mp-file/
最新版本的 mp_file 已支持该功能
