### ISSUE TITLE
使用Image.network加载网络图片，如果不指定宽高图片会不显示

### ISSUE THREAD

**Issue by xiaoyao20084321** [mpflutter/mpflutter#159]
使用Image.network加载网络图片，如果不指定宽高图片会不显示

**Comment by PonyCui** [comment]
已在 https://github.com/mpflutter/mpflutter/commit/2c3718f68391963f3f03b2dde286550619440fac 中添加这一支持，这个问题可以修复，跟随下一版本发布。
