### ISSUE TITLE
输入框在setState后会失焦

### ISSUE THREAD

**Issue by kangfujushi** [mpflutter/mpflutter#165]
我想定制输入框，加入prefixIcon和suffixText，并且想要在编辑时高亮输入框。介于FocusNode目前还不能用，我尝试自己判断状态然后setState，但是会失去焦点，Getx我也试过不行。

还有，请问是否有群或者论坛，我想去交流一下。

**Comment by PonyCui** [comment]
有问题在 GitHub 交流就可以啦。
你提到的这个 setState 会失焦的问题是否可以提供一段可复现的代码到这里？

**Comment by kangfujushi** [comment]
import 'package:flutter/widgets.dart';
import 'package:mpcore/mpcore.dart';

class MyTextFPage extends StatefulWidget {
  @override
  State<MyTextFPage> createState() => _MyTextFPageState();
}

class _MyTextFPageState extends State<MyTextFPage> {
  final editingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      backgroundColor: Colors.white,
      body: Center(
          child: ListView(padding: EdgeInsets.all(20), children: [
        Container(
          height: 44,
          decoration: BoxDecoration(
            border: editingController.text.isNotEmpty
                ? Border.all(
                    color: Colors.purple,
                    width: 2,
                  )
                : Border.all(
                    color: Color.fromARGB(58, 90, 90, 90),
                    width: 1,
                  ),
            color: Colors.grey.withOpacity(0.30),
            borderRadius: BorderRadius.circular(12.0),
          ),
          child: Padding(
            padding: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: MPEditableText(
              controller: editingController,
              focusNode: FocusNode(),
              style: TextStyle(fontSize: 16, color: Colors.black),
              placeholder: 'Input the appBar title',
              onChanged: (value) {
                setState(() {});
              },
            ),
          ),
        ),
      ])),
    );
  }
}

以上是代码；
我试了一下，只在滚动组件会失焦，一般滚动组件和编辑框的组合是经常用得到的。

**Comment by kksqql** [comment]
这个其实是Listview复用导致的,你可以把MPEditableText套在一个StatefulWidget里面,再混入AutomaticKeepAliveClientMixin即可保存MPEditableText的状态

**Comment by kksqql** [comment]
这样写就可以了
class SingleInputWidget extends StatefulWidget {


  @override
  _SingleInputWidgetState createState() => _SingleInputWidgetState();
}

class _SingleInputWidgetState extends State<SingleInputWidget>
    with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    TextEditingController textEditingController = TextEditingController();
    
    return  MPEditableText(
      controller: textEditingController,
      focusNode: FocusNode(),
      style: TextStyle(fontSize: 16, color: Colors.black),
      placeholder: 'Input the appBar title',
      onChanged: (value) {
        setState(() {});
      },
    );
  }

  @override
  bool get wantKeepAlive => true;
}

**Comment by PonyCui** [comment]
@kksqql 我们在框架层面理应提供这个能力，默认就帮助开发者处理好这个场景，你的探索非常好。

**Comment by kksqql** [comment]
@PonyCui  这个主要原因是listview的复用问题,避免不了,除非限制Listview的复用能力,但是限制了Listview的复用能力又和Listview的原理相违背了, 我以前试过用key去处理,也没啥作用,而且这个问题应该不止会出现在setState,当列表过长,再滚动复用的时候应该也会出现这个问题,因为输入框的状态在复用的时候也改变了,所以让输入框能动态保存自己状态就可以解决,大佬可以往这个方向研究一下

**Comment by kangfujushi** [comment]
我试过了，AutomaticKeepAliveClientMixin能解决部分问题，但结合我的那份代码还是会失焦。我的目的是想小程序的效果尽量贴近原生，我感觉还是需要用到focusNode才行。

**Comment by PonyCui** [comment]
奇怪了，我在 sample 工程里用你的代码并不能重现问题。

**Comment by kksqql** [comment]
> 奇怪了，我在 sample 工程里用你的代码并不能重现问题。

我用AutomaticKeepAliveClientMixin也没出现这个问题

**Comment by kangfujushi** [comment]
import 'package:flutter/widgets.dart';
import 'package:mpcore/mpcore.dart';

class MyTextFPage extends StatefulWidget {
  @override
  _MyTextFPageState createState() => _MyTextFPageState();
}

class _MyTextFPageState extends State with AutomaticKeepAliveClientMixin {
  final editingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      backgroundColor: Colors.white,
      body: Center(
        //行
        // child: TextF(),

        //行
        // child: Column(
        //   children: [TextF()],
        // ),

        //不行
        child: ListView(children: [
          TextF(),
        ]),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}

class TextF extends StatefulWidget {
  TextF({Key? key}) : super(key: key);

  @override
  _TextFState createState() => _TextFState();
}

class _TextFState extends State with AutomaticKeepAliveClientMixin {
  final editingController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 44,
      width: 300,
      padding: const EdgeInsets.only(left: 8.0, right: 8.0),
      child: MPEditableText(
        controller: editingController,
        focusNode: FocusNode(),
        style: TextStyle(fontSize: 16, color: Colors.black),
        placeholder: 'Input the appBar title',
        onChanged: (value) {
          setState(() {});
        },
      ),
      decoration: BoxDecoration(
        border: editingController.text.isNotEmpty
            ? Border.all(
                color: Colors.purple,
                width: 2,
              )
            : Border.all(
                color: Color.fromARGB(58, 90, 90, 90),
                width: 1,
              ),
        color: Colors.grey.withOpacity(0.30),
        borderRadius: BorderRadius.circular(12.0),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}

我等了几天看到没反应就没看邮箱了，以上是我的测试代码。假定的场景是多信息输入并要求当前编辑框高亮。但是我知道我的做法太拙劣了，其实最好的办法还是通过监听FocusNode来实现，辛苦大佬了。

**Comment by PonyCui** [comment]
> 

你这个实现也没什么问题，当然后续 mpflutter 能支持 FocusNode 是更好的。

**Comment by PonyCui** [comment]
已在该 commit 添加 FocusNode 响应，跟下一版本发布。
