### ISSUE TITLE
MPDialog路由异常

### ISSUE THREAD

**Issue by kkowo** [mpflutter/mpflutter#166]
通过GestureDetector点击弹出一个MPDialog,MPDilaog的child也具有点击事件且该点击事件需要路由到其他界面时,当前MPDialog不会pop关闭,代码如下:
```
import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';
import 'package:get/get_core/src/get_main.dart';
import 'package:mpcore/mpcore.dart';
import 'package:qxp_app/util/log/log_util.dart';

class DialogPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      body: Center(
        child: Container(
          height: 100,
          width: 100,
          color: Colors.red,
          child: GestureDetector(
            onTap: () async {
              var result = await showMPDialog(
                barrierColor: Colors.black.withOpacity(0.5),
                barrierDismissible: true,
                context: context,
                builder: (context) {
                  return GestureDetector(
                    onTap: () {
                      // Get.back(result: 1);
                      Navigator.of(context).pop(1);
                    },
                    child: Column(
                      children: [
                        Expanded(child: SizedBox()),
                        Container(
                            height: 50,
                            width: 375,
                            alignment: Alignment.center,
                            decoration: BoxDecoration(
                              color: Colors.greenAccent,
                            ),
                            child: Text(
                              "1",
                              style: TextStyle(
                                color: Colors.black,
                              ),
                            )),
                      ],
                    ),
                  );
                },
              );
              if (result != null) {
                logUtil.e(result);
                Get.to(() => BugPage());
                //  Navigator.of(context).pushNamed("/bug");
              }
            },
          ),
        ),
      ),
    );
  }
}

class BugPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      backgroundColor: Colors.blue,
    );
  }
}
```

**Comment by kksqql** [comment]
我发现MPDialog只要是涉及到点击之后和路由有关的都有点问题,这就有点焦灼了

**Comment by PonyCui** [comment]
期望效果是 `Get.to(() => BugPage());` 后 dialog 自动消失？

**Comment by kksqql** [comment]
不是,正常应该是我弹出dialog,然后点击dialog中的选项,触发Get.back(result:result),这时dialog关闭,返回给外部一个result,我通过result去处理逻辑,现在这几步基础的都是好的,但是如果我在拿到result之后,进行和路由相关的操作,比如跳转到某一个界面,就会出现dialog无法关闭的问题,

**Comment by kksqql** [comment]
现在主要问题是拿到result之后,执行路由界面的逻辑,就会出现dialog无法关闭,但是其实dialog里面的Get.back(result:result)已经被调用了

**Comment by kksqql** [comment]
有没有办法创建透明界面,我使用flutter或者Get库的api,创建透明界面的路由,跳转的是一个纯黑的界面,

**Comment by kksqql** [comment]
> 期望效果是 `Get.to(() => BugPage());` 后 dialog 自动消失？

这里的先后顺序应该是,dialog关闭,拿到dialog的返回值,然后再执行Get.to(() => BugPage());跳转到BugPage

**Comment by dahvlhldle** [comment]
MPDilaog中添加导航到下一页。dialog不会消失。应该怎么办呀？ @PonyCui 即便是调用pop也不行

**Comment by PonyCui** [comment]
> MPDilaog中添加导航到下一页。dialog不会消失。应该怎么办呀？ @PonyCui 即便是调用pop也不行

提供一下 Demo 代码？

**Comment by dahvlhldle** [comment]
`import 'package:flutter/widgets.dart';
import 'package:get/get.dart';
import 'package:mpcore/mpcore.dart';

void main() {
  runApp(MyApp());
  MPCore().connectToHostChannel();
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMPApp(
      navigatorObservers: [MPCore.getNavigationObserver()],
      home: Home(),
      routes: <String, WidgetBuilder>{
        '/': (context) => const Home(),
      },
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance?.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      body: GestureDetector(
        child: Text("page1"),
        onTap: () {
          showMPDialog(
            barrierColor: Colors.black.withOpacity(0.5),
            barrierDismissible: true,
            context: context,
            builder: (context) {
              return Stack(
                children: [
                  Positioned(
                    bottom: 0,
                    child: GestureDetector(
                      onTap: () {
                        Get.back();
                        Get.to(SecondPage());
                      },
                      child: ClipOval(
                        child: Container(
                          width: 44,
                          height: 44,
                          color: Colors.blue,
                        ),
                      ),
                    ),
                  )
                ],
              );
            },
          );
        },
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      body: Text("page2"),
    );
  }
}
`

dialog  并没有消失

**Comment by dahvlhldle** [comment]
> > MPDilaog中添加导航到下一页。dialog不会消失。应该怎么办呀？ @PonyCui 即便是调用pop也不行
> 
> 提供一下 Demo 代码？

 麻烦大佬帮忙看看怎么解决，非常感谢！ @PonyCui

**Comment by PonyCui** [comment]
使用 0.18.2 可以解决这个问题的，不需要代码中使用延时处理。
