### ISSUE TITLE
想问问作者，啥时候能有demo预览

### ISSUE THREAD

**Issue by Kimxu** [mpflutter/mpflutter#169]
感谢作者能给出flutter方案来写小程序，真心解决了开发小程序又不想学vue的痛点。
但是还是有几点疑问想问一下作者
1.啥时候能提供演示demo。可以看到各个控件的效果
2.这个项目维护状况啥是怎么样的，会不会后期突然的跑路了。
3.目前版本的mpflutter能否在线上项目中使用，会遇到哪些问题。

**Comment by PonyCui** [comment]
关于第一个问题，我们很快会推出一个独立应用，这个应用可以帮助大家在上面快速构建小工具。
可能会类似 JSBox 和 Scripten 这种工具。
第二个问题，我不能保证长期维护，往后可能会成立商业公司维护项目。
第三个问题，目前是有项目在线上使用的，问题集中在富交互的场景在小程序中很难实现。
