### ISSUE TITLE
scripts/help.dart

### ISSUE THREAD

**Issue by zhushuihua** [mpflutter/mpflutter#170]
dart scripts/help.dart
(flutter 3.0) 运行有问题。
../../flutter/.pub-cache/hosted/pub.mpflutter.com/win32-2.3.6/lib/src/structs.g.dart:661:31: Error: Member not found: 'UnicodeChar'.
  int get UnicodeChar => Char.UnicodeChar;
                              ^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.mpflutter.com/win32-2.3.6/lib/src/structs.g.dart:662:38: Error: Setter not found: 'UnicodeChar'.
  set UnicodeChar(int value) => Char.UnicodeChar = value;
                                     ^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.mpflutter.com/win32-2.3.6/lib/src/structs.g.dart:664:29: Error: Member not found: 'AsciiChar'.
  int get AsciiChar => Char.AsciiChar;
                            ^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.mpflutter.com/win32-2.3.6/lib/src/structs.g.dart:665:36: Error: Setter not found: 'AsciiChar'.
  set AsciiChar(int value) => Char.AsciiChar = value;
                                   ^^^^^^^^^

**Comment by zhushuihua** [comment]
新版本 flutter 3.0

**Comment by PonyCui** [comment]
flutter 3.0 兼容性问题，待统一处理。
