### ISSUE TITLE
shared_preferences & url_lancher

### ISSUE THREAD

**Issue by zhushuihua** [mpflutter/mpflutter#171]
我们应该还至少需要shared_preferences 和 url_lancher 这两个库件。

**Comment by kksqql** [comment]
sp已经提供了,可引用shared_preferences: ^2.0.8

**Comment by zhushuihua** [comment]
Thanks, 怎样navigate 到外部网站（如果不用？url_lancher)

**Comment by PonyCui** [comment]
可以用 a 标签，为了方便开发者，考虑新增一个 MPPlatformRouter 的 API，可以 navigate 到外部网站这样。

**Comment by PonyCui** [comment]
> Thanks, 怎样navigate 到外部网站（如果不用？url_lancher)

https://github.com/mpflutter/mpflutter/issues/107
