### ISSUE TITLE
MPEditableText 的 expands 属性

### ISSUE THREAD

**Issue by moseyah** [mpflutter/mpflutter#175]
因为MPEditableText所继承的EditableText有如下断言
`assert(
          !expands || (maxLines == null && minLines == null),
          'minLines and maxLines must be null when expands is true.'
        )`
所以当expands为true时，需要maxLines和minLines两属性同时为空。
但是MPEditableText的maxLines属性为int类型而非int?类型，不能置空，导致expand属性形同虚设。

我不知道这是否是出于MPEditableText需要手动限制高度的妥协，但是现在我需要一个根据内容自动适应高度的文本框，将expands属性置为true时发现了这个问题。

我尝试过根据内容文字的长度来手动变更文本框的高度，但是由于TextEditingController无法获得行数这个信息，当中英文混杂的时候，每行的字数不尽相同，效果并不理想。

**Comment by PonyCui** [comment]
OK 这确实是存在问题，expands 的实现估计需要更多兼容的工作，稍后会完善一下。
