### ISSUE TITLE
安装了rosetta之后运行出错

### ISSUE THREAD

**Issue by kksqql** [mpflutter/mpflutter#176]
昨天安装了rosetta之后程序编译成功,但是运行一直都是白屏

**Comment by PonyCui** [comment]
我手上没有 m1 机器，没有办法重现问题，你可以具体描述一下错误细节。

**Comment by PonyCui** [comment]
> 昨天安装了rosetta之后程序编译成功,但是运行一直都是白屏

也有可能是 jsdelivr 的问题 https://github.com/mpflutter/mpflutter/issues/177

**Comment by kksqql** [comment]
确实可能是jsdelivr 的问题
