### ISSUE TITLE
jsdelivr 在中国大陆访问受阻

### ISSUE THREAD

**Issue by PonyCui** [mpflutter/mpflutter#177]
MPFlutter 是深度依赖 jsdelivr 进行资源分发的，至少有以下资源会受影响。
- web 端的 js 及 css
- web 端的依赖库加载
- upgrade 脚本下载新版本资源
- MPIcon 图标资源加载

我们正在迁移这些资源到 dist.mpflutter.com 域名中，该域名已通过备案，并托管到腾讯云 cos 及 cdn 上，速度有保证。

为此，作者购买了 100G 的年流量包，希望够用。

预计会在 2022.05.19 发布 v0.15.1 版本解决问题。

**Comment by PonyCui** [comment]
如果你的网站流量特别大，又不希望自建托管服务的话，赞助一下作者购买流量包也是一个选择哦。

**Comment by PonyCui** [comment]
解决方法，升级 mpflutter 至 0.15.2 重新编译可以解决 jsdelivr 资源问题。

旧有的 web/index.html 需要手动替换 css js 地址
```
<link rel="stylesheet" href="https://dist.mpflutter.com/dist/0.15.2/dist_web/mp_web_features.css" />
<script src="https://dist.mpflutter.com/dist/0.15.2/dist_web/mpdom.min.js"></script>
<script src="https://dist.mpflutter.com/dist/0.15.2/dist_web/mp_web_features.min.js"></script>
```

**Comment by AriesHoo** [comment]
巧了这不是，我昨天才升级了一个版本提交了。就是感觉icon有时候加载不出来，然后项目使用的icon很少(30个左右)。就把对应的svg下载下来扔到七牛云上了

**Comment by PonyCui** [comment]
长远来看，我们应该在编译配置中允许开发者设置自己的资源路径，开发者可以自行建立资源镜像。
