### ISSUE TITLE
MPFlutter做一个小程序并发布上线遇到问题记录

### ISSUE THREAD

**Issue by AriesHoo** [mpflutter/mpflutter#181]
最近使用MPFlutter框架将公司官网做成了一个小程序并发布上线。自己看着做的，UI略丑请轻喷。

| ![image.png](https://upload-images.jianshu.io/upload_images/2828782-ce48d04df6e8a484.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240) | ![image.png](https://upload-images.jianshu.io/upload_images/2828782-e21d6d830d4f090b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240) | ![image.png](https://upload-images.jianshu.io/upload_images/2828782-a2f2cb7cafa63a6d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)|
| --- | --- | --- |
| ![image.png](https://upload-images.jianshu.io/upload_images/2828782-a984bbc6b69cfd9a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)| ![image.png](https://upload-images.jianshu.io/upload_images/2828782-201f41e3fab83b77.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240) |  ![image.png](https://upload-images.jianshu.io/upload_images/2828782-095ae49cc37db927.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)|
| ![image.png](https://upload-images.jianshu.io/upload_images/2828782-5c2daa41fa93ad5b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240) | ![image.png](https://upload-images.jianshu.io/upload_images/2828782-add1254c47991eea.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240) | ![image.png](https://upload-images.jianshu.io/upload_images/2828782-c0acaa523199585d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)|
|![image.png](https://upload-images.jianshu.io/upload_images/2828782-dc8ed91e27c383a1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)|![image.png](https://upload-images.jianshu.io/upload_images/2828782-1dce2ee2085edf31.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)|![image.png](https://upload-images.jianshu.io/upload_images/2828782-6e38445f6326493b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)|

感谢作者开源这个框架,让Flutter有更多的可能,在开发过程也遇到些问题在此记录探讨

1、进入新页面时间略长对比`一兜糖`设置页面(`50ms`左右)我做的搜索页面(`150ms`左右)俩页面均是`静态页面`未做网络请求的。如果进入页面做网络请求时间更长,`一兜糖`耗费时间更短。是否在`build_weapp`后对打包文件还做了其它操作？---目前解决方案是在微信小程序端做一个`loading`效果,`Flutter`端做相同的`loading`效果感觉上近似于页面在加载让用户不至于看到白屏(黑屏)

```
<page-meta><navigation-bar title="{{pageMeta.naviBar.title}}" loading="{{pageMeta.naviBar.loading}}" ></navigation-bar></page-meta>
    <view class="loading">
          <view class="loading-css"/>
     </view>
<element wx:if="{{pageId}}" class="miniprogram-root" data-private-node-id="e-body" data-private-page-id="{{pageId}}" >
</element>
```

css样式如下
```
.loading{
  position: absolute;
  top: 120;
  left: 0;
  width: 100%;
  height: 100%;
  flex-direction: column;
  align-items: center;
  align-content: center;
  display:flex;
  align-self: center;
  justify-self: center;
  justify-content: center;
}

.loading-css {
  box-sizing: border-box;
  width: 2.075rem;
  height: 2.075rem;
  display: inline-block;
  border: 0.2rem solid #00000000;
  border-top: 0.2rem solid #2196F3;
  border-radius: 100%;
  /* 动画旋转效果 */
  animation: rotate-360 0.8s infinite linear;
}

@keyframes rotate-360 {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
```
2、`MPKit`里的组件太少太过简单,`Button`这种组件也需要自定义,目前使用`GestureDetector`+`Container`实现而且暂未找到实现按下状态实现思路。本想通过 `onLongPress` 实现结果监听了 `onLongPress` 后 `onTap`点击不响应了，不知是否自己操作问题。

3、`Flutter`原生支持了的`darkMode`被废弃了，目前通过微信文档[darkMode文档](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/darkmode.html) + `MPFlutter` `universal_miniprogram_api` 库监听 `onThemeChange` 状态再修改,但是`MPMainTabView`的背景色总是不能及时切换。最终将`MPMainTabView`背景色设置成透明让其直接显示子Widget的背景色解决

4、小程序分享后再打开后的逻辑在文档中未做明确说明，最后还是在[issue79](https://github.com/mpflutter/mpflutter/issues/79)中找到 分享后参数可通过`Uri.parse(settings.name ?? '')`获取,建议可将该功能放在MPFlutter文档 `微信小程序`
下注明; 如分享资讯详情别人点击进去会进入资讯详情,正常情况下顶部返回icon会变成一个返回主页面icon

![image.png](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9b49c10e9ad04dfbad371851ce8513a6~tplv-k3u1fbpfcp-watermark.image?)
但是我分享后顶部始终是返回icon,但是又返回不回去。最终解决方案是所有分享页面先进入主页再二次跳转到目标页面

5、`dio` `Windows`下 `post`请求 `body` 丢失 [issue152](https://github.com/mpflutter/mpflutter/issues/152),目前做法让后台给小程序单独做一份将 `post`改 `get`的接口

6、`simple_html_css` 渲染html支持太弱-简单的图片可以渲染,图文稍多就渲染不出来了--后面试了下在Flutter环境下app也是渲染不出来的。最后参考 `flutter_html` 库 调用 `csslib`库自己解析。因为项目涉及到的html比较简单可以这么做。

7、因项目设计后台编辑涉及到`TextField`自适应功能,`MPEditableText`无法高度自适应[issue175](https://github.com/mpflutter/mpflutter/issues/175) 待大佬解决,目前解决方案:是固定一个minHeight

希望作者一直做下去，项目越来越完善。

**Comment by PonyCui** [comment]
Good 非常感谢你的反馈，以上这些问题争取在本周落实解决。
以下是 Buglist 记录
- [ ] https://github.com/mpflutter/mpflutter/issues/182
- [ ] https://github.com/mpflutter/mpflutter/issues/175
- [ ] https://github.com/mpflutter/mpflutter/issues/183
- [ ] https://github.com/mpflutter/mpflutter/issues/184

**Comment by jsyanyang** [comment]
@AriesHoo 代码开源不

**Comment by AriesHoo** [comment]
@jsyanyang  公司的项目不能开源的

**Comment by ThisBin** [comment]
关于第二点”按钮点击效果”现在有相应的方案吗？ 像InkWell水波纹能实现吗 @PonyCui
