### ISSUE TITLE
小程序无法编译

### ISSUE THREAD

**Issue by kksqql** [mpflutter/mpflutter#188]
很奇怪,我这里从0.15.3,一路切换到0.15.0都无法编译成小程序,异常如下
`lib/main.dart: Error: Error when reading '../../sdk/flutter/.pub-cache/hosted/pub.mpflutter.com/flutter-0.15.0/lib/src/dart_plugin_registrant.dart': No such file or directory
Target kernel_snapshot failed: Exception
Failed to build bundle.

Unhandled exception:
flutter build bundle 命令执行失败。
#0      _buildDartJS (package:mp_build_tools/build_weapp.dart:105:5)
#1      main (package:mp_build_tools/build_weapp.dart:24:3)
#2      main (file:///Users/keke/Desktop/development/project/qxp_app_mp/scripts/build_weapp.dart:4:11)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
`

**Comment by PonyCui** [comment]
要不你把你的 pubspec.yml 发出来看看？

**Comment by PonyCui** [comment]
尝试在 0.15.4 中修复该问题，请在版本发布后再试试。

**Comment by PonyCui** [comment]
0.15.4 已发布，可以尝试一下。
