### ISSUE TITLE
组件 未通过

### ISSUE THREAD

**Issue by msfm2018** [mpflutter/mpflutter#189]
wx开发者工具stable1.05.2204250 官网下的64位 win11系统 按照文档编译微信小程序，没有修改代码直接编译 代码质量页 显示 组件 启用组件按需注入   未通过  手机显示白屏  但是微信pc可以正常显示，更新一下 dart编译js吧 官网最新是 dart compile  希望给指点。

**Comment by PonyCui** [comment]
启用组件按需注入 未通过
暂时是会有这个问题的，不影响使用。
