### ISSUE TITLE
如果微信小程序要嵌入广告，要怎么实现？

### ISSUE THREAD

**Issue by OHeroJ** [mpflutter/mpflutter#195]
有变现能力的话，更容易推动 mpflutter 的发展。

**Comment by PonyCui** [comment]
对，之前有用户提过把 AD 组件封装到 universal_miniprogram_api 中，我觉得是可以的。
马上就干~ 👍

**Comment by PonyCui** [comment]
我想法是把微信小程序的各种广告 API 都封装出来，先仔细阅读一下相关文档。

**Comment by PonyCui** [comment]
请参考文档，已经提供啦。
https://mpflutter.com/zh/docs/weapp-ad/

**Comment by OHeroJ** [comment]
> 请参考文档，已经提供啦。 https://mpflutter.com/zh/docs/weapp-ad/

给力，🐂
