### ISSUE TITLE
能不能实现直接跳转网页，动态修改网页的title和url

### ISSUE THREAD

**Issue by rhgzs** [mpflutter/mpflutter#199]
目前mpflutter提供了一个可使用a标签的部件
https://mpflutter.com/zh/docs/web-a-tag
但这并不能满足我的需求
动态修改网页title
虽然可以通过改变 MPScaffold 的 name 实现的
但这也不是最好的解决方案
还是希望作者能尽快封装一些Web 常用的 API 出来

**Comment by rhgzs** [comment]
目前作者没有封装出Web 常用的 API 

可以自己编写一个 Web 扩展解决

使用
`dart scripts/help.dart`
命令可以直接生成一个扩展模板，自己修改一下就行，还是很好用的

https://mpflutter.com/zh/docs/web-plugin-method-channel

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter/issues/212
