### ISSUE TITLE
使用deferred as关键字打包后报错

### ISSUE THREAD

**Issue by rhgzs** [mpflutter/mpflutter#201]
调试状态下正常，打包web后报错。
deferred as关键字是否可用

**Comment by PonyCui** [comment]
看上去是 flutter 3.0 导致的 deferred as 功能失效了

**Comment by PonyCui** [comment]
已经在这个 commit 修复 https://github.com/mpflutter/mpflutter/commit/baa0a757ea95bceff15cc0f76774839a5a769e01
跟 0.16.1 版本发布
