### ISSUE TITLE
什么时候支持flutter3.0

### ISSUE THREAD

**Issue by waxudong** [mpflutter/mpflutter#204]

**Comment by PonyCui** [comment]
是需要 flutter 3.0 中的某项特性？

**Comment by 1056824847** [comment]
> 是需要flutter 3.0中的某项特性吗？

flutter 3.0的枚举增强挺有用的

**Comment by PonyCui** [comment]
MPFlutter 本身是支持 flutter 3.0 的，直接在本机安装、使用 flutter 3.0 及对应的 dart-sdk 就可以。
