### ISSUE TITLE
模版工程在ios/android平台上无法正常运行

### ISSUE THREAD

**Issue by WangYuTao3** [mpflutter/mpflutter#205]
template直接run在android上：
I/flutter (29524): Unccaught exception: FileSystemException: Cannot create file, path = './.mpflutter-dev-tools' (OS Error: Read-only file system, errno = 30), #0      _File.throwIfError (dart:io/file_impl.dart:635:7)
I/flutter (29524): #1      _File.createSync (dart:io/file_impl.dart:273:5)
I/flutter (29524): #2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:123:13)
I/flutter (29524): #3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:13)
I/flutter (29524): #4      ga (package:mpcore/ga.dart:3:12)
I/flutter (29524): #5      ga (package:mpcore/ga.dart)
I/flutter (29524): #6      MPChannel.setupHotReload (package:mpcore/channel/channel_io.dart:43:5)
I/flutter (29524): #7      MPCore.connectToHostChannel.<anonymous closure> (package:mpcore/mpcore.dart:103:29)
I/flutter (29524): #8      MPCore.connectToHostChannel.<anonymous closure> (package:mpcore/mpcore.dart:99:29)
I/flutter (29524): #9      _rootRun (dart:async/zone.dart:1426:13)
I/flutter (29524): #10     _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (29524): #11     _runZoned (dart:async/zone.dart:1861:10)
I/flutter (29524): #12     runZonedGuarded (dart:async/zone.dart:1849:12)
I/flutter (29524): #13     MPCore.connectToHostChannel (package:mpcore/mpcore.dart:99:13)
I/flutter (29524): #

flutter doctor：
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by WangYuTao3** [comment]
是不是我理解错了，ios/andorid上也是需要用browser访问的，而不能直接编译后run在相应的平台的？

**Comment by PonyCui** [comment]
> 是不是我理解错了，ios/andorid上也是需要用browser访问的，而不能直接编译后run在相应平台的？

iOS Android 的运行时目前还没有开放，需要运行在 WebView 或 Browser 上。
