### ISSUE TITLE
希望能扩展至抖音小程序

### ISSUE THREAD

**Issue by kangfujushi** [mpflutter/mpflutter#209]
抖音确实是挺大的一块市场，建议可以扩展至抖音小程序。

**Comment by PonyCui** [comment]
dart script/help.dart 里面有构建字节小程序，开发的过程也是和微信一致，template 中就有 tt 这个文件夹。

**Comment by kangfujushi** [comment]
我看到了，感谢。要是期间遇到什么问题，我会在这里反馈

**Comment by PonyCui** [comment]
现已正式支持字节小程序，需要使用 0.18.0 以上版本。
