### ISSUE TITLE
构建发布web应用时，使用MPPlatformView报错

### ISSUE THREAD

**Issue by moseyah** [mpflutter/mpflutter#211]
原本我的打算是用[A标签](https://mpflutter.com/zh/docs/web-a-tag)来完成跳转新页面的功能，在本地调试过程中也并未发现问题。
但是构建发布后，浏览器控制台会报错，且页面显示白屏。
![SCR-20220617-msu](https://user-images.githubusercontent.com/39937957/174259450-1021afe5-bddc-40ef-9073-3e2de1146269.png)
然后我想利用MPWebView进行妥协，发现结果是一样的（调试正常，发布后报错）。
考虑到MPWebView是继承自MPPlatformView，A标签也是利用了MPPlatformView，所以我怀疑是这里出现了问题。

**Comment by moseyah** [comment]
为了简化问题，我用的是下面这个代码测试的，版本库已升级至0.16.3
```dart
@override
  Widget build(BuildContext context) {
    return MPScaffold(
        body: MPPlatformView(
      viewType: 'mp_platform_view',
      viewAttributes: {
        'tag': 'a',
        'href': 'https://www.qq.com/',
      },
      child: Text(
        'Hello, World!\n你好，中国！',
        style: TextStyle(
          fontSize: 24,
          color: Colors.white,
          fontWeight: FontWeight.bold,
          fontStyle: FontStyle.italic,
        ),
      ),
    ));
  }
```

**Comment by moseyah** [comment]
为方便对比，我将调试和构建（利用http-server启动build文件夹）的两个界面放在这里
![SCR-20220617-nax](https://user-images.githubusercontent.com/39937957/174263517-c1a06146-20f9-4b5e-b53e-a020c68c4d80.png)
![SCR-20220617-ndp](https://user-images.githubusercontent.com/39937957/174263689-1a22c478-7d51-4493-90e2-e403621130ad.png)

**Comment by moseyah** [comment]
请问一下这个修复记录什么时候能release呢？或者怎样修改我本地的文件来提前用上这个修复？

**Comment by PonyCui** [comment]
0.16.4 已经可以使用啦～

**Comment by moseyah** [comment]
好的，已测试正常，再次感谢。

**Comment by ToZhanChi** [comment]
可是我的是0.17.1，任然出现这个问题
