### ISSUE TITLE
飞书开发者工具无法显示MPScaffold的body

### ISSUE THREAD

**Issue by iamshaunwu** [mpflutter/mpflutter#218]
想请问一下，字节小程序是否和飞书小程序一样？我用飞书开发者工具导入tt目录过后就出现红色的报错。MPScaffold的title有显示，在vscode更改title后也会即时在飞书开发者工具preview更新。但就是MPScaffold的body就一直不会显示。是否有哥哥姐姐可以开导一下吗？谢谢！

![Screenshot 2022-07-02 at 5 55 36 PM](https://user-images.githubusercontent.com/65869197/176995706-9bb8c4e2-5a2e-4a62-952a-baf3771d7ef5.png)

**Comment by PonyCui** [comment]
应该是 kbone 对飞书的支持还不太好，准备改进一下。

**Comment by iamshaunwu** [comment]
Thank you 哥哥！

**Comment by PonyCui** [comment]
现已支持飞书小程序，具体可参照 https://mpflutter.com/ 文档使用。
