### ISSUE TITLE
FlutterJsonBeanFactory插件报错

### ISSUE THREAD

**Issue by once10301** [mpflutter/mpflutter#219]
![image](https://user-images.githubusercontent.com/12422465/177147335-487f259e-2fb6-4b47-870f-a5cec99cb5ba.png)
插件版本4.4.5
![image](https://user-images.githubusercontent.com/12422465/177147428-13b2a2f7-fb2d-47e2-b0b4-660bb7d635d3.png)

**Comment by PonyCui** [comment]
请阅读该插件文档
https://github.com/fluttercandies/FlutterJsonBeanFactory

before:
```
environment:
  sdk: ">=2.12.0 <3.0.0"
```

after modification:

```
environment:
  sdk: ">=2.15.0 <3.0.0"
```
