### ISSUE TITLE
MPFlutter 多平台小程序支持

### ISSUE THREAD

**Issue by PonyCui** [mpflutter/mpflutter#226]
当前，MPFlutter 仅官方支持微信小程序，我们希望在 0.18.0 版本中支持更多平台的小程序。

以下平台是计划在 0.18.0 中支持的：

- 字节跳动小程序（抖音、西瓜视频、头条等）
- 飞书小程序
- 支付宝小程序
- 钉钉小程序
- 百度小程序

以下工作是需要完成的：

- [x] kbone 跨平台编译及支持
- [x] 重新调整模板应用开发流程
- [x] 添加各平台文档

这项工作预计会在 8 月 15 日前完成

关联 Issue：
https://github.com/mpflutter/mpflutter/issues/226
https://github.com/mpflutter/mpflutter/issues/12
https://github.com/mpflutter/mpflutter/issues/52
https://github.com/mpflutter/mpflutter/issues/13

**Comment by jeffreycool** [comment]
大佬，我想问下，为什么不支持继承flutter的diolog类？

**Comment by jeffreycool** [comment]
> 

那大佬意思是，还是要用到小程序的api么？

**Comment by jeffreycool** [comment]
你好，还有个问题，就是我想使用地图和调起扫码的功能，但是在官方文档找不到对应的资料，如果我需要从小程序里面提供api给mpflutter，请问这个具体需要怎么去实现？

**Comment by PonyCui** [comment]
@jeffreycool 
https://mpflutter.com/zh/docs/weapp-api

**Comment by PonyCui** [comment]
现已支持
字节跳动小程序（抖音、西瓜视频、头条等）
飞书小程序
