### ISSUE TITLE
在弹窗内使用输入框，当输入框获取到焦点后，就会出现异常报错

### ISSUE THREAD

**Issue by jeffreycool** [mpflutter/mpflutter#227]
在弹窗内使用输入框，当输入框获取到焦点后，就会出现异常报错，使用的是MPEditableText控件，异常信息如下：
<img width="830" alt="截屏2022-07-13 16 48 09" src="https://user-images.githubusercontent.com/108108418/178692064-80ef9a8c-1b35-45b9-838a-266bdd82fa75.png">

<img width="1272" alt="截屏2022-07-13 16 49 42" src="https://user-images.githubusercontent.com/108108418/178692234-fd4fe64b-4b3d-4436-a3ce-681ad62ab1e8.png">

**Comment by PonyCui** [comment]
有问题的代码贴一下？

**Comment by jeffreycool** [comment]
class AmountWidget extends StatelessWidget {
  final TextEditingController controller;
  final FocusNode node;

  const AmountWidget({
    required this.controller,
    required this.node,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 30.h,
      decoration: BoxDecoration(
        color: Colours.mainColor,
        borderRadius: BorderRadius.all(Radius.circular(5.w)),
      ),
      child: Row(
        children: [
          Expanded(
            child: GestureDetector(
              behavior: HitTestBehavior.translucent,
              onTap: () {
                int value = int.parse(controller.text);
                value--;
                value = value < 0 ? 0 : value;
                controller.text = '$value';
              },
              child: Text(
                '-',
                textAlign: TextAlign.center,
                style: TextStyles.whiteText20,
              ),
            ),
          ),
          Expanded(
            flex: 2,
            child: Container(
              height: 26.h,
              decoration: const BoxDecoration(color: Colors.white),
              child: MPEditableText(
                controller: controller,
                textAlign: TextAlign.center,
                keyboardType: TextInputType.number,
                style: TextStyles.mainColor16,
                focusNode: node,
              ),
            ),
          ),
          Expanded(
            child: GestureDetector(
              behavior: HitTestBehavior.translucent,
              onTap: () {
                int value = int.parse(controller.text);
                value++;
                value = value < 0 ? 0 : value;
                controller.text = '$value';
              },
              child: Text(
                '+',
                textAlign: TextAlign.center,
                style: TextStyles.whiteText20,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

**Comment by PonyCui** [comment]
> 

可以拉一下群看看

**Comment by fastcode555** [comment]
已经拉了，mpmath

**Comment by rhgzs** [comment]
将barrierDismissible设置为false即可

**Comment by fastcode555** [comment]
> 将barrierDismissible设置为false即可
嗯嗯，这样确实也可以解决，谢谢。
