### ISSUE TITLE
自定义appbar顶部安全区域无法获取

### ISSUE THREAD

**Issue by maisidicd** [mpflutter/mpflutter#238]
MediaQuery.of(context).padding.top获取的值是0.0
直接使用MPAppBar也存在问题。
<img width="327" alt="image" src="https://user-images.githubusercontent.com/94343956/180379488-7b187987-58bc-4011-9915-350d380a3293.png">

mpflutter版本0.17.1

**Comment by PonyCui** [comment]
具体说明问题的环境？

**Comment by PonyCui** [comment]
貌似我在本地 debug 下没有重现这个问题，如果有再次重现的场景请重开这个 issue。
