### ISSUE TITLE
「MPFlutter」开发一个日历小程序的体验分享

### ISSUE THREAD

**Issue by Kingtous** [mpflutter/mpflutter#242]
用mpflutter写了个简单的微信小程序《轮班工作日历》，目前也已审核上线，开心～

总体来说，能复用Flutter栈写微信小程序，对于我这种不太会ts、js的开发者来说，是个重磅功能。mpflutter给flutter写微信小程序提供了可能。总体谈一下个人体验的一些想法和优化思路哈。

体验：
1. hot reload works！好起来了。
2. 与微信小程序开发工具联动相当nice。

遇到的问题：
1. 第三方日历组件几乎全军覆没，因为没有PageController组件支持，mpflutter使用的是mpcontroller。最后只能自己用GridView造了个简单的日历组件。
2. 其他人分享了这个微信小程序，但是通过分享进入小程序，有时会遇到白屏情况。
3. 页面跳转比较慢，要个1-2s。
4. `void main()`函数改为async函数，在函数内调用一条`await`指令，无法启动小程序，点击debug后命令直接return 0。例如：
```dart
void main() async {
    WidgetsFlutterBinding.ensureInitialized();
   await initService();
   runApp(const MyAPP());
    MPCore.connectToChannel();
}
```

思考：
1. 基础组件感觉可以和GetX一样，通过阉割的形式改写，这样兼容性可能更好点（问题1可能就容易解决了）。如果直接改成MPxxx容易导致三方组件无法复用。
2. 可以增加一些Button组件（Container + GestureDetector）？目前好像没有Button组件了，mpflutter可以简单用GestureDetector封装一下一个简单的button组件，方便复用。

**Comment by NightFog007** [comment]
小程序叫什么名字呢?想试用下看看效果😄

**Comment by zeplee** [comment]
确实是，为什么不用原有的组件呢，就像flutter支持的那些android ,ios web,mac,windows,linux一样，只是添加平行的各种小程序支持，是不是更有前途呢
