### ISSUE TITLE
能否优化路由跳转

### ISSUE THREAD

**Issue by rhecs** [mpflutter/mpflutter#243]
路由跳转页面 打开等待的时间偏长了点 经常性2-3秒才能完成 能否优化？

**Comment by rhecs** [comment]
仔细研究了下 好像不是路由跳转的问题  路由还是很快就切换了 是页面载入速度很慢 页面切换完毕 然后载入需要2-3秒才行 包括首页的加载也偏慢 有什么好的优化思路么 感谢

**Comment by PonyCui** [comment]
跳转到新页面的时候，先用比较少的内容占位，例如一个简单的 loading，这样可以免去白屏的尴尬。

**Comment by rhecs** [comment]
嗯 感谢 您的产品很好  我已经借鉴之前issues内的策略 添加了loading 还是建议如果可以  优化载入  产品如果用于生产环境 我们这边很多领导习惯性的对比其他小程序的  到时候也肯定会要求我们优化载入…… 希望mpflutter越来越好

**Comment by rhecs** [comment]
方便的话 还是感觉拉个群好一些  qq群v群都可以 有技术也便于讨论

**Comment by jihchao** [comment]
哈喽，跳转慢的问题解决了吗？
我git拉的项目，代码未改的情况，直接运行，点击Hello, MPFlutter!大概页面空白了2秒钟才渲染出第二页的红色色块 Tap here。构建为 Web 应用，然后使用本机nginx代理测试的。电脑是 MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
是我哪里错了吗？

```
./mpflutter doctor      
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3 21E230 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
    ! Error: iPhone is busy: Fetching debug symbols for iPhone. Xcode will continue when Phone is finished. (code -10)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by PonyCui** [comment]
@jihchao 这个速度不太合理，你在什么浏览器上测试的结果 ？

**Comment by jihchao** [comment]
Safari 版本15.4 (17613.1.17.1.6)

> @jihchao 这个速度不太合理，你在什么浏览器上测试的结果 ？

**Comment by Ssiswent** [comment]
> 嗯 感谢 您的产品很好 我已经借鉴之前issues内的策略 添加了loading 还是建议如果可以 优化载入 产品如果用于生产环境 我们这边很多领导习惯性的对比其他小程序的 到时候也肯定会要求我们优化载入…… 希望mpflutter越来越好

你好，请问能具体说一下怎么实现跳转时添加loading解决跳转过慢的问题呢，感谢

**Comment by PonyCui** [comment]
> > 嗯 感谢 您的产品很好 我已经借鉴之前issues内的策略 添加了loading 还是建议如果可以 优化载入 产品如果用于生产环境 我们这边很多领导习惯性的对比其他小程序的 到时候也肯定会要求我们优化载入…… 希望mpflutter越来越好
> 
> 你好，请问能具体说一下怎么实现跳转时添加loading解决跳转过慢的问题呢，感谢

如果下一个页面在初始的 build 时就返回一个很复杂的 Widget 树，比较好的办法是在初始时先返回一个比较简单的 Widget 树，然后再延时 500ms 改变 state 返回复杂的 Widget 树。

**Comment by Ssiswent** [comment]
> > > 嗯 感谢 您的产品很好 我已经借鉴之前issues内的策略 添加了loading 还是建议如果可以 优化载入 产品如果用于生产环境 我们这边很多领导习惯性的对比其他小程序的 到时候也肯定会要求我们优化载入…… 希望mpflutter越来越好
> > 
> > 
> > 你好，请问能具体说一下怎么实现跳转时添加loading解决跳转过慢的问题呢，感谢
> 
> 如果下一个页面在初始的 build 时就返回一个很复杂的 Widget 树，比较好的办法是在初始时先返回一个比较简单的 Widget 树，然后再延时 500ms 改变 state 返回复杂的 Widget 树。

感谢作者的回复，我测试的是模板点击中间蓝色区域跳转，二级页面应该也是简单的Widget树了，但是还是有比较明显的延迟= =

**Comment by jihchao** [comment]
> > > > 嗯 感谢 您的产品很好 我已经借鉴之前issues内的策略 添加了loading 还是建议如果可以 优化载入 产品如果用于生产环境 我们这边很多领导习惯性的对比其他小程序的 到时候也肯定会要求我们优化载入…… 希望mpflutter越来越好
> > > 
> > > 
> > > 你好，请问能具体说一下怎么实现跳转时添加loading解决跳转过慢的问题呢，感谢
> > 
> > 
> > 如果下一个页面在初始的 build 时就返回一个很复杂的 Widget 树，比较好的办法是在初始时先返回一个比较简单的 Widget 树，然后再延时 500ms 改变 state 返回复杂的 Widget 树。
> 
> 感谢作者的回复，我测试的是模板点击中间蓝色区域跳转，二级页面应该也是简单的Widget树了，但是还是有比较明显的延迟= =

你应该和我是是同一个问题，都还没到build方法。我发现在网页上跳转要2秒多，编译为微信小程序后，似乎速度快了一些，1秒多。

**Comment by PonyCui** [comment]
换一个浏览器也如此？

**Comment by Ssiswent** [comment]
> 

主要我没学习过写小程序，在掘金看到一篇说加loading优化的方式，但是没有效果
[https://juejin.cn/post/7102244075537072135#heading-8](url)

**Comment by PonyCui** [comment]
问题应该修复了，可以使用0.18.1。

**Comment by Ssiswent** [comment]
> 问题应该修复了，可以使用0.18.1。

感觉跳转还是有明显的加载，使用的是0.18.11的版本，跑的demo

**Comment by PonyCui** [comment]
> > 问题应该修复了，可以使用0.18.1。
> 
> 感觉跳转还是有明显的加载，使用的是0.18.11的版本，跑的demo

是升级上去还是全新的 template 开发？

**Comment by Ssiswent** [comment]
> > > 问题应该修复了，可以使用0.18.1。
> > 
> > 
> > 感觉跳转还是有明显的加载，使用的是0.18.11的版本，跑的demo
> 
> 是升级上去还是全新的 template 开发？

全新的= =

**Comment by jihchao** [comment]
> 问题应该修复了，可以使用0.18.1。

速度确实快了很多，在pc上没有明显的跳转，在微信小程序上，就有明显的跳转（页面刷新），速度没啥问题了。
感觉做阅读类、新闻类、工具类的够用了。就是第三方组件比较麻烦，全不需要自己实现了。
