### ISSUE TITLE
previewImage  微信图，不支持长按？

### ISSUE THREAD

**Issue by OHeroJ** [mpflutter/mpflutter#244]
目的：图片是二维码可以长按识别

实际：图片长按无反应

**Comment by PonyCui** [comment]
showmenu | boolean | true | 否 | 是否显示长按菜单。

这个设置为 true 可以吗？

**Comment by PonyCui** [comment]
还是说这个组件的 https://developers.weixin.qq.com/miniprogram/dev/component/image.html 
show-menu-by-longpress 需要设置为 true?

**Comment by OHeroJ** [comment]
晚上测下 showmenu。https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.previewImage.html
