### ISSUE TITLE
关于开发小游戏的可能性

### ISSUE THREAD

**Issue by jihchao** [mpflutter/mpflutter#245]
Hi，这是一个了不起的项目，十分感谢作者。
我们正在调研mpflutter开发小游戏的可能性，目前发现不支持Flame，是否有支持Flame的计划，或者已经其他MPFlutter已经支持的游戏引擎吗？

**Comment by PonyCui** [comment]
MPFlutter 应该是不会支持小游戏的，另外开方向研究一下单独的 Flame 移植到小游戏平台吧。
