### ISSUE TITLE
Ras加密  这个rootBundle.loadString加载返回null

### ISSUE THREAD

**Issue by shlinyijun** [mpflutter/mpflutter#246]
String  publicPem = await rootBundle.loadString('assets/rsa/public.pem');

**Comment by shlinyijun** [comment]
![1662016015960](https://user-images.githubusercontent.com/51258995/187853138-1b62f3af-666c-4cf0-b13b-703c1c5c48e9.png)

**Comment by shlinyijun** [comment]
![1662086724293](https://user-images.githubusercontent.com/51258995/188048323-203bc324-f597-4816-b785-8e86ea04ad8f.png)
目前资源.pem没法加载 （1.DefaultAssetBundle.of() ，2.rootBundle.loadString ） 只能用笨办法了

**Comment by shlinyijun** [comment]
![1662087959705](https://user-images.githubusercontent.com/51258995/188050860-19d18ffd-953c-465b-8065-c726b01a2db6.png)
目前通过（1.rootBundle.loadString('assets/rsa/public.pem')，2.DefaultAssetBundle.of(context).loadString('assets/rsa/public.pem');）都无法获取.pem；只能使用笨办法了

**Comment by PonyCui** [comment]
升级至 0.17.2 可解决该问题
