### ISSUE TITLE
搭建报错

### ISSUE THREAD

**Issue by ToZhanChi** [mpflutter/mpflutter#248]
Tomcat环境；
第一张错误信息，第二三张使用的相关组件；

![微信图片_20220902172731](https://user-images.githubusercontent.com/33199875/188109494-24f85738-ca78-411d-8816-8fc2871d1237.jpg)
![微信截图_20220902172635](https://user-images.githubusercontent.com/33199875/188109724-4d064aad-4525-4cad-8386-65d957d21cb2.png)
![微信截图_20220902172612](https://user-images.githubusercontent.com/33199875/188109733-3a8383a8-6dbb-4c2d-a0b4-3fd21a3f84c1.png)

**Comment by ToZhanChi** [comment]
我定位到是如下代码问题：

          Obx(() {
            var inWX = logic.inWX.value;
            if (inWX) return SizedBox.shrink();
            return MPPlatformView(
              viewType: 'mp_platform_view',
              viewAttributes: {
                'tag': 'a',
                'target': '_blank',
                'href': 'https://www.baidu.com/',
              },
              child: Container(
                width: 120,
                height: 35,
                decoration: BoxDecoration(
                  color: Color(0xFF1ABC9C),
                  borderRadius: BorderRadius.circular(20),
                ),
                alignment: Alignment.center,
                child: Text(
                  '安装',
                  style: TextStyle(
                    fontSize: 14,
                    color: Colors.white,
                  ),
                ),
              ),
            );
          }),

**Comment by ToZhanChi** [comment]
确定到如下代码报错

MPPlatformView(
            viewType: 'mp_platform_view',
            viewAttributes: {
              'tag': 'a',
              'target': '_blank',
              'href': 'https://www.baidu.com/',
            },
            child: Text(
              '安装',
              style: TextStyle(
                fontSize: 14,
                color: Colors.white,
              ),
            ),
          ),

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter/issues/211
