### ISSUE TITLE
依赖拉取失败

### ISSUE THREAD

**Issue by lishoujieA** [mpflutter/mpflutter#251]
PS D:\BHWorkSpace\bh_wx> ./mpflutter packages get

D:\BHWorkSpace\bh_wx>set PUB_HOSTED_URL=https://pub.mpflutter.com

D:\BHWorkSpace\bh_wx>flutter packages get
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Warning: You are using these overridden dependencies:
! flutter 0.17.1
! flutter_web_plugins 0.17.1
! mpcore 0.17.1
Pub failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Running "flutter pub get" in bh_wx...
pub get failed (1; in the directory open in another application.)
你好 我运行./mpflutter packages get命令时报错 这个怎么解决啊

**Comment by PonyCui** [comment]
使用管理员模式打开 powershell

**Comment by dong-lufei** [comment]
#  % 13697 @ dlf16 in E:\test [23:07:42]
$  ./mpflutter packages get
./mpflutter: The term './mpflutter' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

#  % 13697 @ dlf16 in E:\test [23:07:49] C:1

**Comment by dong-lufei** [comment]
现在是使用管理员模式打开的 powershell

$  ./mpflutter packages get

E:\test\mpflutter_demo>set PUB_HOSTED_URL=https://pub.mpflutter.com

E:\test\mpflutter_demo>flutter packages get
Warning: You are using these overridden dependencies:
! flutter 1.0.0
! flutter_web_plugins 1.0.0
! mpcore 1.0.0
Running "flutter pub get" in mpflutter_demo...                      5.8s

#  % 13697 @ dlf16 in E:\test\mpflutter_demo on git:master [23:09:59]
