### ISSUE TITLE
大佬，跪求教一下，MacBook 终端下dart scripts/help.dart怎么选择各个选项呢？

### ISSUE THREAD

**Issue by Etermally** [mpflutter/mpflutter#254]
Mac dart scripts/help.dart命令行之后，怎么操作都无法选择《初始化 Android Studio 配置文件》选项，请问大佬，您能给说下吗？非常感谢
<img width="885" alt="WeChat7d52b89ea6bf8406d1ff19d4236223cd" src="https://user-images.githubusercontent.com/13942100/192495712-5e9f5705-992c-49f5-9832-23043b789bb9.png">

**Comment by Etermally** [comment]
看有的视频，windows下直接输入序号，mac也没有序号这些，上下箭头或者command+箭头都无效，求教，大神

**Comment by PonyCui** [comment]
换一个终端试试？zsh bash iTerm2?

**Comment by Etermally** [comment]
zsh bash iTerm2 三种方式都尝试了，都无法选择选项，大佬，您或者您的同事mac电脑，没有这种情况出现吗？好着急~！！

**Comment by Etermally** [comment]
昨天搞到挺晚都没有搞成事，现在完全懵逼状态

**Comment by PonyCui** [comment]
flutter --version 看看

**Comment by Etermally** [comment]
![Uploading WeChat17d885f5e01d6d5bf3370590ce214607.png…]()

**Comment by Etermally** [comment]
<img width="910" alt="WeChat17d885f5e01d6d5bf3370590ce214607" src="https://user-images.githubusercontent.com/13942100/192677357-a96b0115-cc75-4186-9366-caeb418658bb.png">

**Comment by PonyCui** [comment]
换 flutter 3.0 试试
mpflutter 版本号用 0.17.1

**Comment by Etermally** [comment]
<img width="1677" alt="截屏2022-09-28 上午11 31 24" src="https://user-images.githubusercontent.com/13942100/192681317-0bb15692-8cdd-44e7-b8f2-325204b17c4f.png">
目前您说的是这样吗？但是执行dart scripts/help.dart 报错了

**Comment by PonyCui** [comment]
> <img alt="截屏2022-09-28 上午11 31 24" width="1677" src="https://user-images.githubusercontent.com/13942100/192681317-0bb15692-8cdd-44e7-b8f2-325204b17c4f.png">
> 
> 目前您说的是这样吗？但是执行dart scripts/help.dart 报错了

重新拷一份新的 mpflutter_template 再试吧

**Comment by Etermally** [comment]
<img width="913" alt="截屏2022-09-28 下午2 53 43" src="https://user-images.githubusercontent.com/13942100/192708979-fe55debd-18ce-4e3e-9fb9-4fa15b3dfb96.png">
唉、、、还是一样，不能选择，这可咋整？

**Comment by Etermally** [comment]
我本人不是小程序开发出身，忽然看到了，flutter能做到，已经迫不及待的想尝试以及做实践了，没想到第一步都走不过去  😭

**Comment by Etermally** [comment]
我本人不是小程序开发出身，忽然看到了，flutter能做到，已经迫不及待的想尝试以及做实践了，没想到第一步都走不过去 😭，求救场，大佬

**Comment by Etermally** [comment]
您好，我看官网截图也是macBook的终端截图，您那边也是直接上下键直接切换这个选项的吗？o(╥﹏╥)o

**Comment by Etermally** [comment]
大佬，解决了，解决了，怪我的电脑终端，麻烦您了，这个问题解决办法是硬重置了一下，就可以正常选择了

**Comment by Etermally** [comment]
我这边直接关闭了，麻烦您了
