### ISSUE TITLE
dart2js 在dart 2.18中被移除，后续有无更新计划？

### ISSUE THREAD

**Issue by hydra1983** [mpflutter/mpflutter#255]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/488235/193776430-ab09fbf6-ede1-437a-87b7-cfa5f135c18c.png">

https://dart.dev/tools/dart2js

**Comment by PonyCui** [comment]
这个问题已经在最新的版本 0.17.1 中适配了，不再依赖 dart2js 命令行。
