### ISSUE TITLE
希望微信端能增加蓝牙相应的接口，以便连接蓝牙打印机

### ISSUE THREAD

**Issue by TonyLiuChina** [mpflutter/mpflutter#256]
首先这是很不错的产品，适合不会前端的我使用，非常感谢项目方。
最近在做一个小程序，经过多方比较mpflutter成了我的首选，再次感谢项目方。
看了已经有微信登录、支付、分享这些接口，确实非常方便。
目前我的项目中有需要连接蓝牙打印机，暂时没有发现对应的微信接口。希望微信端能增加蓝牙相应的接口，以便连接蓝牙打印机；希望项目方能抽空解决一下，谢谢了！

**Comment by PonyCui** [comment]
你可以先使用扩展 https://mpflutter.com/zh/docs/weapp-plugin-intro 自行封装一下

**Comment by PonyCui** [comment]
我们也会尽快提供官方封装的接口

**Comment by PonyCui** [comment]
https://mpflutter.com/zh/docs/weapp-api
已经提供蓝牙接口封装
