### ISSUE TITLE
flutter_web_plugins 一直无法成功，请问这是什么原因呢？

### ISSUE THREAD

**Issue by Etermally** [mpflutter/mpflutter#257]
flutter: "0.17.1"
  flutter_web_plugins: "0.17.1"
  mpcore: "0.17.1"

Running "flutter pub get" in awesome_project...                 
Because mpflutter_template depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...

**Comment by Etermally** [comment]
大佬能帮忙解答下吗？(╥╯^╰╥)

**Comment by Etermally** [comment]
一直是这样~这是网络问题还是什么情况呢？之前是没问题的


Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...

**Comment by Etermally** [comment]
一直是这样~这是网络问题还是什么情况呢？之前是没问题的，求大佬解答下，(╥╯^╰╥)

Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn/), version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn/), version solving failed.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn/), version solving failed.
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn/), version solving failed.
pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn/), version solving failed.
pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn/), version solving failed.
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn/), version solving failed.
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
Because apex_wechat depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.flutter-io.cn/), version solving failed.
pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...

**Comment by PonyCui** [comment]
./mpflutter packages get

**Comment by Etermally** [comment]
收到  谢谢  理解偏差了
