### ISSUE TITLE
MPAppbar 位置不对

### ISSUE THREAD

**Issue by duomitd** [mpflutter/mpflutter#261]
MPAppbar的位置为什么偏下，不是应该和右侧按钮在一行吗？
![image](https://user-images.githubusercontent.com/9610255/196025350-b30ce542-89b7-4ae5-8e27-0c729ac6f5ce.png)

**Comment by PonyCui** [comment]
如果你需要使用 MPAppBar，需要先设置 app.json 中小程序自带的 bar 隐藏。
