### ISSUE TITLE
需求问题，代码编译错误

### ISSUE THREAD

**Issue by ToZhanChi** [mpflutter/mpflutter#263]
APP有个需求，APP打开web页面，并监听web页面的点击事件。

用的这个插件：https://pub.flutter-io.cn/packages/webview_flutter
webview_flutter监听方法：javascriptChannels
官方实现案例：
  /// JavascriptChannel(name: 'Print', onMessageReceived: (JavascriptMessage message) { print(message.message); });
  /// JavaScript code can call:
  /// ```javascript
  /// Print.postMessage('Hello');

模仿着试了下，编译报错。如附件图片
![微信截图_20221023094225](https://user-images.githubusercontent.com/33199875/197369280-32875817-75ae-4b87-836d-3defa2f9e68d.png)
![微信截图_20221023094411](https://user-images.githubusercontent.com/33199875/197369281-14782f68-d9a9-443a-917f-7268ae301fa7.png)

**Comment by PonyCui** [comment]
参照这里写扩展 https://mpflutter.com/zh/docs/web-plugin-intro
