### ISSUE TITLE
您好 吸顶在小程序上没效果了

### ISSUE THREAD

**Issue by shaozhiqiang** [mpflutter/mpflutter#264]
app上没问题  移到小程序 appbar换成mpappbar运行看热门推荐那块不吸顶了

https://user-images.githubusercontent.com/5310028/197398821-a1b0c824-1e14-4dbe-b057-64f3164cc732.mp4

![Screenshot_2022_1023_222541](https://user-images.githubusercontent.com/5310028/197398849-244a3adf-837b-49ef-972a-441726a75f91.png)
![Screenshot_2022_1023_222633](https://user-images.githubusercontent.com/5310028/197398858-9ad572cc-def6-4578-ab67-3fd4734ab10b.png)

附件是运行效果 和热门推荐布局 mappbar布局

**Comment by PonyCui** [comment]
把那一页的完整代码发一下上来？

**Comment by shaozhiqiang** [comment]
@PonyCui 
class SearchInput extends StatelessWidget {
  const SearchInput({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final isDark = MediaQuery.of(context).platformBrightness == Brightness.dark;
    return MPScaffold(
      backgroundColor: isDark ? Colors.black : Color(0xfff2f2f2),
      appBar: _inputHead(context),
      body: CustomScrollView(
        slivers: [
          _buildHotWord(),
          _buildStickyBar(),
          Obx(() => Get.find<RecommendController>().isLoading.value
              ? SliverToBoxAdapter(
                  child: Container(
                    alignment: Alignment.center,
                    width: 100,
                    height: 100,
                    child: MPCircularProgressIndicator(),
                  ),
                )
              : _buildRec())
        ],
      ),
    );
  }
}

///输入页头部
PreferredSizeWidget _inputHead(context) {
  return MPAppBar(
    backgroundColor: Colors.white,
    primary: false,
    context: context,
    title: Center(
      child: Container(
        width: 250,
        height: 34,
        decoration: BoxDecoration(
          color: Colors.grey.withOpacity(0.30),
          borderRadius: BorderRadius.circular(12.0),
        ),
        child: Padding(
          padding: const EdgeInsets.only(left: 8.0, right: 8.0),
          child: MPEditableText(
            controller: TextEditingController(),
            focusNode: FocusNode(),
            style: TextStyle(fontSize: 16, color: Colors.black),
            placeholder: '请输入搜索内容',
            placeholderStyle: TextStyle(color: Color(0x60000000)),
          ),
        ),
      ),
    ),
    leading: Container(
      alignment: Alignment.center,
      width: 44,
      height: 44,
      child: MPIcon(MaterialIcons.arrow_back),
    ),
    trailing: Container(
      alignment: Alignment.center,
      width: 44,
      height: 44,
      child: Text(
        "搜索",
        style: TextStyle(fontSize: 16, color: Colors.black),
      ),
    ), // 右侧按钮
  );
}

///热搜词内容
Widget _buildHotWord() {
  return SliverToBoxAdapter(
    child: Column(
      children: [
        Container(
          color: Colors.white,
          padding: const EdgeInsets.only(left: 8, bottom: 12),
          alignment: Alignment.topLeft,
          child: const Text(
            "搜索发现",
            style: TextStyle(
                color: Colors.black, fontSize: 16, fontWeight: FontWeight.bold),
          ),
        ),
        Container(
          width: double.infinity,
          color: Colors.white,
          padding: const EdgeInsets.only(left: 8, right: 8, bottom: 8),
          child: Obx(
            () => Wrap(
                runSpacing: 8,
                spacing: 8,
                children: itemHotWord(Get.find<WordController>().hotWordList)),
          ),
        ),
      ],
    ),
  );
}

///热门推荐吸顶布局
Widget _buildStickyBar() {
  return SliverPersistentHeader(
    pinned: true,
    floating: true,
    delegate: SliverAppBarDelegate(
        minHeight: 40,
        maxHeight: 40,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: EdgeInsets.only(left: 10, top: 10),
              child: Text(
                "热门推荐",
                style: TextStyle(
                    color: Color(0xffff5500),
                    fontSize: 16,
                    fontWeight: FontWeight.bold),
              ),
            ),
            Container(
              margin: EdgeInsets.only(left: 30),
              height: 5,
              width: 20,
              decoration: BoxDecoration(color: Color(0xffff5500)),
            )
          ],
        )),
  );
}

///热门推荐内容
Widget _buildRec() {
  return SliverPadding(
    padding: EdgeInsets.all(10),
    sliver: SliverWaterfall.count(
      crossAxisCount: 2,
      mainAxisSpacing: 10,
      crossAxisSpacing: 10,
      children: itemWaterCard(Get.find<RecommendController>().skulist),
    ),
  );
}

**Comment by PonyCui** [comment]
升级至 0.17.2 可解决该问题

**Comment by shaozhiqiang** [comment]
> 升级至 0.17.2 可解决该问题

您好 升级到最新版本了  界面有问题  上次我用mpkit下面的MPAppBarPinned 能吸顶 也是这样的界面 
![20221025202030617](https://user-images.githubusercontent.com/5310028/197773837-ca137c48-ddd7-4967-80ae-51798024ffae.png)
