### ISSUE TITLE
微信小程序原生广告问题

### ISSUE THREAD

**Issue by OHeroJ** [mpflutter/mpflutter#265]
使用了 `WechatAdCustom`, 在流量主那边配置了广告模板，但是将其添加入后，并未显示该模板的广告。而是一个单图的。

选择的模板：

![image](https://user-images.githubusercontent.com/12316547/197483539-5c01052f-765f-4de3-bac1-51678695c0c7.png)

小程序的显示：

<img width="480" alt="image" src="https://user-images.githubusercontent.com/12316547/197478899-39deab03-94e5-4639-88cc-3467c806b63f.png">

嵌入 [WechatAdCustom](https://github.com/mpflutter-plugins/universal_miniprogram_api/blob/f0b036f5b1/lib/wechat_mini_program/ad_custom.dart) 代码：

```dart
class NativeAdView extends StatefulWidget {
  final String adId;
  const NativeAdView({Key? key, required this.adId}) : super(key: key);

  @override
  State<NativeAdView> createState() => _NativeAdViewState();
}

class _NativeAdViewState extends State<NativeAdView> {
  bool adError = false;

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      margin: EdgeInsets.only(top: 16),
      width: MediaQuery.of(context).size.width,
      color: Colors.grey[100],
      height: adError ? 0 : MediaQuery.of(context).size.width * 9 / 16,
      child: WechatAdCustom(
        unitId: widget.adId,
        onLoad: (details) {
          print("广告： $details");
        },
        onError: (details) {
          setState(() {
            adError = true;
          });
        },
      ),
    );
  }
}
```

定位器：

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/12316547/197485062-51a8973b-b802-4833-91b1-775225e0d549.png">

应该是生成 [ad-custom](https://developers.weixin.qq.com/miniprogram/dev/component/ad-custom.html) 标签的，而不是 ad 标签

**Comment by PonyCui** [comment]
使用 0.0.5 就可以了
