### ISSUE TITLE
吸顶界面问题

### ISSUE THREAD

**Issue by shaozhiqiang** [mpflutter/mpflutter#266]
您好 上个问题https://github.com/mpflutter/mpflutter/issues/264#issuecomment-1289288835 升级到最新版本了 但是界面有问题 
上次用mpkit下面的MPAppBarPinned  也是这样的
![20221025202030617](https://user-images.githubusercontent.com/5310028/197775317-99ea2aee-8d3e-4245-af57-ea9afd4a2900.png)

**Comment by PonyCui** [comment]
方便把完整代码打包发送到我邮箱不 cuis#vip.qq.com
不然有点难定位问题

**Comment by shaozhiqiang** [comment]
> 方便把完整代码打包发送到我邮箱不 cuis#vip.qq.com
> 不然有点难定位问题

已发送

**Comment by PonyCui** [comment]
升级 mpflutter 要严格按照文档说明操作
https://mpflutter.com/zh/docs/upgrade-core
