### ISSUE TITLE
是不是有帧率限制，使用StreamBuilder局部更新数据，会发生跳帧现象或白屏现象。

### ISSUE THREAD

**Issue by C-Kristal** [mpflutter/mpflutter#267]
当每次更新Duration为300ms以下时,每次更新 一个数字。会发生跳帧。只有在300ms，才正常。
300ms以下，打印的数据，速度是正常的，但就是渲染不出来或跳帧，设置为100ms以下还可能发生白屏无法渲染。

**Comment by PonyCui** [comment]
小程序文本测量耗时较长，会导致你描述的问题。
