### ISSUE TITLE
will it  support cupertino and material widgets?

### ISSUE THREAD

**Issue by adamin1990** [mpflutter/mpflutter#27]

**Comment by adamin1990** [comment]
and what flutter version does it depend on?is 0.8.5 the flutter official version ?

**Comment by PonyCui** [comment]
No, will not support. Use material and cupertino library will generate a really large size javascript code.
We depends on flutter 2.2.0+, need null-safety.

**Comment by PonyCui** [comment]
Maybe a compact layer will provide.

**Comment by adamin1990** [comment]
Okay,continuous attention，加油！
