### ISSUE TITLE
分享提交审核时候遇到的一些权限问题

### ISSUE THREAD

**Issue by pirder** [mpflutter/mpflutter#271]
本人遇到的是：提交隐私协议的时候，说我使用到了摄像头和麦克风，要我填写对应的内容。
大家直接 build出产品 在build文件中删除掉对应的组件即可。
我删除了，camera,live-pusher,voip-room
https://developers.weixin.qq.com/miniprogram/dev/component/camera.html
<img width="380" alt="image" src="https://user-images.githubusercontent.com/29139348/199164109-6720146f-a88b-489f-aa7b-59b2b7489997.png">

**Comment by pirder** [comment]
> 本人遇到的是：提交隐私协议的时候，说我使用到了摄像头和麦克风，要我填写对应的内容。
> 大家直接 build出产品 在build文件中删除掉对应的组件即可。
> 我删除了，camera,live-pusher,voip-room
> https://developers.weixin.qq.com/miniprogram/dev/component/camera.html
> <img alt="image" width="380" src="https://user-images.githubusercontent.com/29139348/199164109-6720146f-a88b-489f-aa7b-59b2b7489997.png">

前提是大家 确确实实没用到 如果删除了 也许会导致对应调用的失败

**Comment by PonyCui** [comment]
是的，这是目前的解决方案，kbone 这个框架导致的问题。
我们会在 mpflutter 0.18.0 提供一个 tree-shark 工具，自动将没有使用到的组件移除掉。
