### ISSUE TITLE
初始化报错，瞬间不想往操作了，

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#292]
报错信息：
![image](https://user-images.githubusercontent.com/15965000/202984979-20f39968-6c92-4678-97cc-8f1e894dc721.png)
![image](https://user-images.githubusercontent.com/15965000/202985086-bfd958e5-f12c-4198-b102-bfce53ad52d9.png)

版本信息：
![image](https://user-images.githubusercontent.com/15965000/202985411-2e415b29-bb63-45a4-b8d2-cf65a83032cd.png)

官方文档能把你们自己打包初始化运行的打印的代码也附上就好了。

**Comment by PonyCui** [comment]
./mpflutter packages get

**Comment by songds** [comment]
用的是这个命令，你bat文件里面执行的就是flutter packages get

**Comment by songds** [comment]
执行./mpflutter packages get 自动打印出来的

![企业微信截图_16690287594431](https://user-images.githubusercontent.com/15965000/203035748-c00ea1c2-e525-42ba-af6c-6e0d3fa79316.png)

**Comment by songds** [comment]
> ./mpflutter packages get 文档里有说的 https://mpflutter.com/zh/docs/first-app-vs


执行./mpflutter packages get 自动打印出来的
![image](https://user-images.githubusercontent.com/15965000/203035962-ff0b9b09-87dd-4f2c-84a6-d44fd0ab33b3.png)
