### ISSUE TITLE
命令没毛病是按照步骤来得，你可以自己直接命名执行截图给我一下

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#293]
执行你会自动打印两条命令出来
![image](https://user-images.githubusercontent.com/15965000/203038669-ab10d16d-2a63-48ed-9777-50fdaeda7b81.png)

![企业微信截图_16690297552963](https://user-images.githubusercontent.com/15965000/203038516-df5c5142-c88b-426c-bd06-f1e48ed35b6a.png)

![企业微信截图_16690297552963](https://user-images.githubusercontent.com/15965000/203038397-6da5489f-1c12-4279-83d6-4398bc90d259.png)

**Comment by PonyCui** [comment]
如果是在 windows 上使用，请使用管理员模式打开 powershell。

**Comment by songds** [comment]
执行命令之后，在Android studio 里面看不到MpFlutter的启动模板

![image](https://user-images.githubusercontent.com/15965000/203218637-41e2271b-a9e6-40b0-91cb-dd30cc988f7c.png)

![image](https://user-images.githubusercontent.com/15965000/203218705-8e92c754-1431-4e93-8b1a-196f742e143b.png)

![image](https://user-images.githubusercontent.com/15965000/203218854-53062375-569c-45d5-b953-5cfc84c43aca.png)

**Comment by songds** [comment]
牛逼解决了，框架真牛逼

**Comment by songds** [comment]
强大
