### ISSUE TITLE
可以加入flutter webrtc吗

### ISSUE THREAD

**Issue by xiangxud** [mpflutter/mpflutter#295]
可以加入flutter webrtc吗，最近做小程序音视频rtc播放,选型方案，本框架支持这个设想吗

**Comment by PonyCui** [comment]
你可以参照微信文档实现 https://developers.weixin.qq.com/miniprogram/dev/component/live-player.html

**Comment by PonyCui** [comment]
过于垂直的领域，我们应该不会提供封装，你可以按照 mpflutter 编写扩展的方式实现的，flutter pub 上的 rtc 库肯定是不能用的。

**Comment by xiangxud** [comment]
感谢指点，不过感觉难度还是比较大

**Comment by PonyCui** [comment]
应该还好，微信的 live-player 本身就支持 webrtc，实在不懂如何封装可以看看教程。
