### ISSUE TITLE
Text无法单行缩略

### ISSUE THREAD

**Issue by tangbincheng** [mpflutter/mpflutter#298]
`Text(
                's我萨达打撒萨达阿三大苏打大苏打撒旦啊实打实大苏打实打实打算啊实打实打算我萨达打撒萨达阿三大苏打大苏打撒旦啊实打实大苏打实打实打算啊实打实打算我萨达打撒萨达阿三大苏打大苏打撒旦啊实打实大苏打实打实打算啊实打实打算',
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: TextStyle(fontSize: 16),
              )`

![微信截图_20221130155039](https://user-images.githubusercontent.com/13461281/204738018-de460e37-566b-4e02-be2c-267607d63d4f.png)
我使用以下版本 
 flutter: "0.18.1"
  flutter_web_plugins: "0.18.1"
  mpcore: "0.18.1"
  mp_build_tools: "0.18.1"

**Comment by tangbincheng** [comment]
换了MPText 也不行

**Comment by PonyCui** [comment]
使用 0.18.2 即可
