### ISSUE TITLE
编译小程序错误

### ISSUE THREAD

**Issue by Ben56** [mpflutter/mpflutter#3]
![image](https://user-images.githubusercontent.com/19664147/131443877-0b256d2e-8990-42db-a8ec-7f0b4b2529d5.png)
编译时会自动删除/build/assets文件夹

**Comment by PonyCui** [comment]
还未在 windows 上完整测试过，可能在未来数天内完善。

**Comment by PonyCui** [comment]
这个问题在 0.5.1 版本中已经修复
