### ISSUE TITLE
微信小程序导航栏左侧内容也不能定制，MPAppBar只能在导航拦下面定制内，有什么办法实现吗？

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#300]

**Comment by dahvlhldle** [comment]
app.json页面

"window": {
    ...
    "navigationStyle": "custom"
},

**Comment by songds** [comment]
要手动改一下是吧

**Comment by songds** [comment]
> app.json页面
> 
> "window": { ... "navigationStyle": "custom" },



> app.json页面
> 
> "window": { ... "navigationStyle": "custom" },

要手动改一下定制是吧

**Comment by dahvlhldle** [comment]
> 

是呀，weapp里面自定义

**Comment by songds** [comment]
> 是呀，weapp里面自定义

Thanks，待会试试，希望这框架越来越强大
