### ISSUE TITLE
ListView.builder 的reverse 属性没有效果。

### ISSUE THREAD

**Issue by dahvlhldle** [mpflutter/mpflutter#301]
聊天界面需要倒序排列。

**Comment by PonyCui** [comment]
OK，这个 Feature 应该会在这两天发布的 0.18.3 中提供。

**Comment by PonyCui** [comment]
已经提供 0.18.3 版本

**Comment by dahvlhldle** [comment]
@PonyCui 你好！当ListView使用reverse的时候，ScrollController也应该倒序。不然无法显示最新消息，每次都会滚动到最旧的一条消息。
