### ISSUE TITLE
支付宝小程序有确定时间支持吗

### ISSUE THREAD

**Issue by enjkvbej** [mpflutter/mpflutter#303]
因为项目需要支持支付宝小程序 谢谢

**Comment by PonyCui** [comment]
支付宝应该在今年内不会支持，支付宝小程序的编译环境存在性能问题，暂未找到解决方案。

**Comment by enjkvbej** [comment]
要是能支持编译成taro就好了

**Comment by enjkvbej** [comment]
您好  支付宝小程序我们愿意一起来实现 我理解技术上是可以实现的吧？用kbone来做 希望回复下 谢谢

**Comment by PonyCui** [comment]
主要卡点在于生成的 main.dart.js 比较大，在支付宝小程序里，预览和编译时，会走到 ast analyser，这个 analyser 会非常耗时，机器的 CPU 资源全被吃掉了，难以 Debug。

**Comment by enjkvbej** [comment]
感谢作者答疑 那我们是否可以直接将flutter转化成taro呢 这样各个端小程序就都支持了 而不用一一开发支持

**Comment by PonyCui** [comment]
> 感谢作者答疑 那我们是否可以直接将flutter转化成taro呢 这样各个端小程序就都支持了 而不用一一开发支持

同样是有这个问题的，只要是从 dart 编译出来的，都会生成这个大大的文件，比较好的方法是找到方法直接跳过静态检查。

**Comment by PonyCui** [comment]
> 想问下 我们的app已经用flutter开发 如果迁移至mpflutter工作量大吗 app偏工具类型 数据展示和流程表单为主 上传拍照是最复杂的功能了

应该问题不大，如果有需要的话你可以通过付费技术咨询提问，解答会更实时。

**Comment by getong** [comment]
2024年了，支付宝小程序还考虑支持吗？
