### ISSUE TITLE
mpflutter运行在android模拟器上显示白屏

### ISSUE THREAD

**Issue by 15629199786** [mpflutter/mpflutter#312]
I/flutter ( 8561): Unccaught exception: FileSystemException: Cannot create file, path = './.mpflutter-dev-tools' (OS Error: Read-only file system, errno = 30), #0      _File.throwIfError (dart:io/file_impl.dart:635:7)
I/flutter ( 8561): #1      _File.createSync (dart:io/file_impl.dart:273:5)
I/flutter ( 8561): #2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:123:13)
I/flutter ( 8561): #3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:13)
I/flutter ( 8561): #4      ga (package:mpcore/ga.dart:3:12)
I/flutter ( 8561): #5      ga (package:mpcore/ga.dart)
I/flutter ( 8561): #6      MPChannel.setupHotReload (package:mpcore/channel/channel_io.dart:43:5)
I/flutter ( 8561): #7      MPCore.connectToHostChannel.<anonymous closure> (package:mpcore/mpcore.dart:134:29)
I/flutter ( 8561): #8      MPCore.connectToHostChannel.<anonymous closure> (package:mpcore/mpcore.dart:129:29)
I/flutter ( 8561): #9      _rootRun (dart:async/zone.dart:1428:13)
I/flutter ( 8561): #10     _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter ( 8561): #11     _runZoned (dart:async/zone.dart:1863:10)
I/flutter ( 8561): #12     runZonedGuarded (dart:async/zone.dart:1851:12)
I/flutter ( 8561): #13     MPCore.connectToHostChannel (package:mpcore/mpcore.dart:129:13)

**Comment by PonyCui** [comment]
你运行程序的方法有误，请参考文档跑一遍。
