### ISSUE TITLE
本地资源在构建后无法加载

### ISSUE THREAD

**Issue by randomjoho** [mpflutter/mpflutter#313]
按照教程【https://mpflutter.com/zh/docs/ui-assets】
在项目根目录 [assets/images/menu/work.svg] 添加了一个svg图片
在pubspec.yaml 声明了 
`assets:
  - assets/images/menu/work.svg`
 
代码中调用
`Image.asset(
                    'assets/images/menu/work.svg',
                    width: 24,
                    height: 24,
                  )`

在debug环境，图片正常显示.

使用命令构建: dart scripts/build_weapp.dart
在微信开发工具加载 /build 目录，发现资源无法加载。
报错如下
`[渲染层网络层错误] Failed to load local image resource /assets/assets/images/menu/work.svg 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
(env: macOS,mp,1.06.2206090; lib: 2.18.0)`

Flutter : 2.10.2
MPFlutter: 1.8.3

看到报错的路径我以为我写多了一个assets，但是我检查了并没有。

<a href="https://ibb.co/4mnzhxt"><img src="https://i.ibb.co/Gx4yzjp/QQ20221211-171128-2x.png" alt="QQ20221211-171128-2x" border="0" /></a>

**Comment by PonyCui** [comment]
看上去是微信开发者工具的问题，重启试试。

**Comment by randomjoho** [comment]
@PonyCui  您好，我这边把微信开发者工具升级到最新，开发者工具清除缓存，clean了项目重新build，依然存在这个问题。即使我上传到小程序体验版用手机打开也是一样。

**Comment by PonyCui** [comment]
打包 build 文件夹发到这里看看

**Comment by randomjoho** [comment]
[build.zip](https://github.com/mpflutter/mpflutter/files/10202072/build.zip)

**Comment by randomjoho** [comment]
抱歉居然是这里出了问题。谢谢解答
