### ISSUE TITLE
屏幕适配问题

### ISSUE THREAD

**Issue by chen412115** [mpflutter/mpflutter#314]
我设置小程序的屏幕尺寸为414 * 896
每次运行小程序的或者热重载的时候
通过MediaQuery.of(context).size获取的屏幕宽度都是375

通过小程序右上方按钮“重新进入小程序”，获取的屏幕宽度才会变成414

**Comment by PonyCui** [comment]
MediaQuery.of(context).size 获取的位置是在哪里呢

**Comment by chen412115** [comment]
> MediaQuery.of(context).size 获取的位置是在哪里呢

在页面的build方法中

**Comment by PonyCui** [comment]
你可以把重现步骤再具体一点描述一下不

**Comment by chen412115** [comment]
我运行的是template代码
<img width="918" alt="图片" src="https://user-images.githubusercontent.com/20555613/207812131-63910869-fd5b-4f7a-bf21-5adeb681d2b0.png">

这个是我选择的模拟器
<img width="486" alt="图片" src="https://user-images.githubusercontent.com/20555613/207812233-73484387-e5b4-4288-b78c-d7fab6004497.png">
第一次直接运行时，打印的屏幕width为375


然后我在微信里边重新运行小程序
<img width="425" alt="图片" src="https://user-images.githubusercontent.com/20555613/207812452-54df913d-23c9-4b86-b741-ca3313272a98.png">

打印的就变成了414
<img width="698" alt="图片" src="https://user-images.githubusercontent.com/20555613/207812670-670f11b0-74d8-418d-bcf3-5642351108e3.png">
