### ISSUE TITLE
Add a script for the person who wants to run the sample locally

### ISSUE THREAD

**Issue by huang12zheng** [mpflutter/mpflutter#317]
In `/Users/huangzheng/web/mpflutter/packages/mpflutter_sample/`
`flutter run lib/main.dart`
It just shows a white screen, which makes me confusing.

---

- [ ] I think something is needed as follow.
'/Users/huangzheng/web/mpflutter/packages/mpflutter_sample/pre_install.sh'
```
set -e
if [ -n "`which browserify|grep 'not found'`" ] || [ -n "`which tsc|grep 'not found'`" ] || [ -n "`which terser|grep 'not found'`" ]; then
echo "Install dependencies"
npm install -g browserify uglify-js typescript terser
fi

FOLDER_PATH=$(cd "$(dirname "$0")"; pwd)

cd $FOLDER_PATH
cd ../../
# sh build.sh

cd packages/mp_dom_runtime/
npm install
npm run build
cd packages/mp_web_features
npm install
npm run build
```

- [ ] Let someone knows that there is a sample to learn from,
And tell them, how to startup

I'm not sure where to put it, maybe a README, or something where people might see it

---

* Second edit

The `build.sh` script, in addition to not installing dependencies,
which I found doing the above.
Of course, it would be nice to add judgment to whether the current "Node" is 16 or not.
```
if [ -z "`node --version|grep v16.`" ]; then
echo "please use node 16"
exit 1;
fi
```

**Comment by PonyCui** [comment]
Thanks for the suggestion, maybe you can create a PR and I'll merge it as soon as possible.
