### ISSUE TITLE
是否应该让mpkit的组件是const 构造方法?

### ISSUE THREAD

**Issue by huang12zheng** [mpflutter/mpflutter#319]
```
使用 const Widget，以此得到一个类似「缓存」的效果。虽然 Flutter 本身也会尽量的复用 Element
```
我发现许多mpkit的构造函数没有加上const限制.
在迁移代码过程中,  可能需要将原本的代码加上的const,在mpflutter这里去掉.

我认为这会增加一定的迁移成本与抵触心理.

一个例子:MPCircularProgressIndicator()

**Comment by PonyCui** [comment]
嗯，如果是从迁移代码的角度来看，确实是有这个问题。

**Comment by huang12zheng** [comment]
计划直接使用WebView的方式,关闭这个issue
