### ISSUE TITLE
在ListView.custom上mpflutter 与flutter是不匹配的

### ISSUE THREAD

**Issue by huang12zheng** [mpflutter/mpflutter#323]
比较如下两个repo
https://github.com/huang12zheng/mpflutter/tree/list_custom_error
and
https://dartpad.cn/?id=e75b493dae1287757c5e1d77a0dc73f1

可以发现:
1. flutter 里的 ListView.custom只取了 50个item
2. 而mpflutter里会一直取下去.

<img width="1680" alt="截屏2022-12-23 10 49 18" src="https://user-images.githubusercontent.com/28038074/209261109-91c85210-fa0f-4de2-a95e-b4ab4baf1943.png">

![截屏2022-12-23 10 49 18 (2)](https://user-images.githubusercontent.com/28038074/209261116-2769320b-1a3f-43be-93ae-1293f6657098.png)

这可能应该算是 #324 的一个小问题

**Comment by PonyCui** [comment]
这是 MPFluter 的一个 feature，我们会全量获取 ListView 中的所有内容，不会边滚动边获取。

**Comment by huang12zheng** [comment]
> 这是 MPFluter 的一个 feature，我们会全量获取 ListView 中的所有内容，不会边滚动边获取。

我之前以为是bug,还找了一下原因在哪里-_-||
说实话,我不喜欢这个feature.
因为它让我原来在FLutter上正常执行的代码, 在MPFlutter上无法执行.
更进一步,如下模式(状态更新)的代码将变得 只有坏处,没有好处...
```dart
        childrenDelegate: SliverChildBuilderDelegate((context, index) {
....
                 final packageList = ref.watch(
                   fetchPackagesProvider(
                     page: page,
                     search: searchController.text,
                   ),
                 );
....
                  return packageList.when(
                   error: (err, stack) => Text('Error $err'),
                   loading: () => const PackageItemShimmer(),
                      if (indexInPage >= packages.length) return null;
```

最后, 能介绍一下这个feature产生的原因吗? 我没有发现它的优点.

**Comment by PonyCui** [comment]
MPFlutter 对于 List 的处理是以空间换时间，Flutter 对于 List 的处理是以时间换空间。
简单来说：
Flutter 在 Native 渲染时，List 中的 Cell 是逐步渲染的，一般情况下只会渲染 2 ～ 3 屏，在滚动的过程中会继续渲染下方不可见区域的内容。
但是这种方式在 Flutter For Web 中会造成非常严重的卡顿，原因在于，如果需要让 JS 处理如此频繁的滚动事件，并且要在滚动事件中完成 Layout 等操作，可怜的 JS 一定会卡顿。
MPFlutter 则与 Flutter 做法相反。
