### ISSUE TITLE
MPFlutter可视化能够支持吗？是否有对应的charts_flutter呢？

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#325]

**Comment by PonyCui** [comment]
正在尝试兼容 fl_chart，已经有一点进展了。

**Comment by songds** [comment]
强

**Comment by songds** [comment]
大概什么时间点能落地呢？

**Comment by PonyCui** [comment]
估计 2 月上旬，大体效果有了。
<img width="422" alt="截屏2023-02-04 23 37 33" src="https://user-images.githubusercontent.com/5013664/216776216-4984d99e-6df8-42d4-8d13-b4a16414b1be.png">

**Comment by PonyCui** [comment]
已支持 fl-chart
https://mpflutter.com/zh/docs/lib-flchart
