### ISSUE TITLE
版本更新迭代有点慢呢，社区不够大

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#326]

**Comment by PonyCui** [comment]
目前还是起步阶段，个人也是兼职维护，社区确实还没有培养起来，明年会投入更多精力打理这一块。

**Comment by songds** [comment]
MPFlutter可视化数据报表框架支持Flutter pub.dev的那个版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mpflutter/mpflutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mpflutter/mpflutter] 版本更新迭代有点慢呢，社区不够大 (Issue #326)





 
目前还是起步阶段，个人也是兼职维护，社区确实还没有培养起来，明年会投入更多精力打理这一块。
