### ISSUE TITLE
down下来安装依赖失败，我这win11的flutter环境可以正常跑flutter项目的，但是拉mpflutter跑就报错下面：

### ISSUE THREAD

**Issue by dong-lufei** [mpflutter/mpflutter#329]
$ ./mpflutter packages get

E:\test\awesome_project>set PUB_HOSTED_URL=https://pub.mpflutter.com

E:\test\awesome_project>flutter packages get
Warning: You are using these overridden dependencies:
! flutter 0.19.0 (1.0.0 available)
! flutter_web_plugins 0.19.0 (1.0.0 available)
! mpcore 0.19.0 (1.0.0 available)
Pub failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Running "flutter pub get" in awesome_project...
pub get failed (1; in the directory open in another application.)

**Comment by dong-lufei** [comment]
上面是从gitee拉的，现在从GitHub拉跑报错下面：
Warning: You are using these overridden dependencies:
! flutter 1.0.0
! flutter_web_plugins 1.0.0
! mpcore 1.0.0
Pub failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Running "flutter pub get" in mpflutter_demo...
pub get failed (1; in the directory open in another application.)

**Comment by dong-lufei** [comment]
$ flutter  --version
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (3 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

# 13697 @ dlf16 in E:\test\mpflutter_demo on git:master [17:16:04]
$ git --version
git version 2.39.0.windows.2

# 13697 @ dlf16 in E:\test\mpflutter_demo on git:master [17:16:16]
$ host

Name             : ConsoleHost
Version          : 7.3.1
InstanceId       : bbe0cc20-8060-4b11-97bb-4761c610c223
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : zh-CN
CurrentUICulture : zh-CN
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace



# 13697 @ dlf16 in E:\test\mpflutter_demo on git:master [17:16:24]
$ node -v
v16.19.0

# 13697 @ dlf16 in E:\test\mpflutter_demo on git:master [17:16:48]
$ npm -v
8.19.3

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter/issues/251

**Comment by dong-lufei** [comment]
> #251

用管理员身份打开 powershell 运行还是没跑起来：

# 13697 @ dlf16 in E:\test\mpflutter_demo on git:master [10:31:41]
$ ./mpflutter packages get

E:\test\mpflutter_demo>set PUB_HOSTED_URL=https://pub.mpflutter.com

E:\test\mpflutter_demo>flutter packages get
Warning: You are using these overridden dependencies:
! flutter 1.0.0
! flutter_web_plugins 1.0.0
! mpcore 1.0.0
Running "flutter pub get" in mpflutter_demo...                     564ms

# 13697 @ dlf16 in E:\test\mpflutter_demo on git:master [10:31:47]

**Comment by PonyCui** [comment]
> 

你这里的提示是已经完成依赖摘取了

**Comment by dong-lufei** [comment]
怎么运行呀？上面执行命令 ./mpflutter packages get 有在监听端口吗

**Comment by dong-lufei** [comment]
找到了
在VSCode 只能F5 或者命令 dart lib/main.dart  运行么
