### ISSUE TITLE
微信小程序运行有警告

### ISSUE THREAD

**Issue by dong-lufei** [mpflutter/mpflutter#330]
无效的 app.json ["newFramework"]

WASubContext.js?t=wechat&s=1672885286646&v=2.29.0:1 Free data with key "kboneRender" of page "pages/index/index" seems not a simple value. Result of deep cloning this value in page instantiation may be unexpected. Consider assigning this value at the beginning of onLoad method.

[代码依赖分析] 找到 2 个依赖异常情况，可能会导致对应文件无法加载，请检查。
require function is used in a way in which dependencies cannot be statically extracted (/mpdom.min.js:1:2610)
the request of a dependency is an expression (/mpdom.min.js:1:2625)
如需关闭依赖分析请在 project.config.json setting 字段中增加 "ignoreDevUnusedFiles": false 和 "ignoreUploadUnusedFiles": false

**Comment by PonyCui** [comment]
忽略就可以了
