### ISSUE TITLE
小程序页面加载速度，平均在3秒上下

### ISSUE THREAD

**Issue by JimmyLee05** [mpflutter/mpflutter#35]
![WechatIMG209](https://user-images.githubusercontent.com/13815229/144792730-2858c333-9019-42ba-a163-1978c1570a15.jpeg)

查看了官方的线上小程序，从首页进入 装修设计、福利团页面，加载时间都在3秒以上。
点击 我 页面加载速度在2秒以上。

这个加载速度是否可优化 目前页面的加载体验 感觉还有提升空间

**Comment by PonyCui** [comment]
有优化的空间，有部分页面是后端数据获取较慢导致，前端页面在 setData 这一环节有优化的空间。

**Comment by JimmyLee05** [comment]
> 

了然

小程序其它的操作体验挺不错，UI设计也挺美观。

感谢开源

**Comment by PonyCui** [comment]
目前正在优化 RenderObject 的 Diff 更新，文本测量的速度优化，一旦这两项工作完成，小程序的初始渲染速度有望提升 50%。
