### ISSUE TITLE
使用AndroidStudio不显示项目的目录，不能hotreload

### ISSUE THREAD

**Issue by yougeyouge90** [mpflutter/mpflutter#350]
作者大大你好，我使用你的最新模板， 通过命令 初始化 MPFlutter 模板工程，初始化 Android Studio 配置文件，之后再去使用AS打开项目，但是AndroidStudio不显示项目的目录，不能hotreload，现在好像运行起来的web页面也无法通过浏览器打开。我的AS的版本号如图所示，项目显示也如下图所示，可否优化一下？目前VsCode是可以正常使用的。

<img width="1511" alt="WechatIMG2759" src="https://user-images.githubusercontent.com/46983059/213377122-f01c7b39-37c2-4bc1-a148-f8a5aa834e40.png">

**Comment by PonyCui** [comment]
先保证你的 android studio 可以正常运行普通的 flutter 项目。

**Comment by yougeyouge90** [comment]
我的As是可以运行的呢，就是作者大大，你可以下载个最新的mac的AS版本试试看吗，确实不能用呢

**Comment by PonyCui** [comment]
我的 Android Studio 信息如下，安装 Dart 插件，没有问题，你可以试试？
Android Studio Bumblebee | 2021.1.1 Canary 11
Build #AI-211.7628.21.2111.7676841, built on August 26, 2021
Runtime version: 11.0.11+0-b60-7590822 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 10
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.bytedance.tools.wrangler (2.1.1), com.bytedance.pluginx (1.0), Dart (211.7817)

**Comment by yougeyouge90** [comment]
好的，谢谢作者大大
