### ISSUE TITLE
无法使用GetX的路由跳转

### ISSUE THREAD

**Issue by yougeyouge90** [mpflutter/mpflutter#351]
作者大大，能不能支持一下Get.to()或者Get.toName(),希望支持getx的跳转的参数如下：
arguments,
transition，
preventDuplicates
opaque,
fullscreenDialog

**Comment by PonyCui** [comment]
可以使用 GetX 的路径跳转的，但不支持配置路由动画，也不支持使用 fullscreenDialog，请使用 MPDialog。
