### ISSUE TITLE
请问怎么配置 页面渲染完成之前的加载视图

### ISSUE THREAD

**Issue by dahvlhldle** [mpflutter/mpflutter#355]
[页面渲染完成之前的加载视图](https://developers.weixin.qq.com/miniprogram/kbone/docs/guide/advanced.html#%E9%A1%B5%E9%9D%A2%E6%B8%B2%E6%9F%93%E5%AE%8C%E6%88%90%E4%B9%8B%E5%89%8D%E7%9A%84%E5%8A%A0%E8%BD%BD%E8%A7%86%E5%9B%BE)

**Comment by PonyCui** [comment]
https://mpflutter.com/zh/docs/weapp-loading-view
已支持该功能
