### ISSUE TITLE
请问是否提供了调用摄像头的api

### ISSUE THREAD

**Issue by 18598925736** [mpflutter/mpflutter#356]

**Comment by 18598925736** [comment]
比如扫码，拍照，文件选择器选照片之后识别

**Comment by PonyCui** [comment]
使用 universal_miniprogram_api 调用 scanCode, chooseMedia 就可以 https://developers.weixin.qq.com/miniprogram/dev/api/device/scan/wx.scanCode.html
https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html

**Comment by 18598925736** [comment]
了解，谢谢大佬，回复的太快了，哈哈哈
