### ISSUE TITLE
 Error: The getter 'platformDispatcher' isn't defined for the class 'WidgetsBinding'.

### ISSUE THREAD

**Issue by QixianWu** [mpflutter/mpflutter#359]
小程序构建生产环境会报错。

../../../Library/Flutter/.pub-cache/hosted/pub.mpflutter.com/url_launcher_platform_interface-2.1.1/lib/link.dart:92:13: Error: The getter 'platformDispatcher' isn't defined for the class 'WidgetsBinding'.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Library/Flutter/.pub-cache/hosted/pub.mpflutter.com/flutter-1.0.2/lib/src/widgets/binding.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'platformDispatcher'.
          ?.platformDispatcher
            ^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
Failed to build bundle.

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale
    zh-Hans-CN)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by PonyCui** [comment]
使用了 url_launcher_platform_interface 依赖？

**Comment by QixianWu** [comment]
是的，我检查了lock文件，确实存在这个依赖，是其他库导致的，我移除后可以成功build了。
