### ISSUE TITLE
中文乱码，页面偏移

### ISSUE THREAD

**Issue by jijkbird** [mpflutter/mpflutter#360]
使用  dart scripts/build_weapp.dart 构建程序，
微信开发工具再开build目录，页面整体向左偏移，且中文乱码

**Comment by jijkbird** [comment]
中文乱码好像是从服务端获取的文字，本地写死的文字没有乱码

**Comment by jijkbird** [comment]
因为代码集成度高，敏感信息太多了，不过我可以提供截图

**Comment by jijkbird** [comment]
![WX20230201-163907](https://user-images.githubusercontent.com/20245625/215993021-62ec7ce0-2a97-48f0-8b28-1413ef418964.png)
![WX20230201-163940](https://user-images.githubusercontent.com/20245625/215993039-e464374b-4216-499d-bbd9-0b5a662a8674.png)

**Comment by jijkbird** [comment]
左边是生产模式，右边是调试模式

**Comment by jijkbird** [comment]
name: fishing_mp
description: A new MPFlutter project.
publish_to: "none"
version: 1.0.0+1
playbox:
  name: 模板工程
  description: 
  icon: school
  background: blue
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: "1.0.0"
  flutter_web_plugins: "1.0.0"
  mpcore: "1.0.0"
  mp_build_tools: "1.0.0"
  parse_server_sdk:
    path: mod/parse_server_sdk
  get: ^4.3.9
  universal_miniprogram_api: ^0.1.0
  # shared_preferences: ^2.0.8
  barcode_widget:
    git:
      url: https://github.com/mpflutter-plugins/dart_barcode
      path: flutter
dependency_overrides:
  meta: ^1.7.0
  flutter: "1.0.0"
  mpcore: "1.0.0"
  flutter_web_plugins: "1.0.0"

**Comment by jijkbird** [comment]
import 'package:fishing_mp/page/mallInfo.dart';
import 'package:fishing_mp/page/sousuo.dart';
import 'package:flutter/widgets.dart';
import 'package:get/get.dart';
import 'package:mpcore/mpkit/mpkit.dart';
import 'package:parse_server_sdk/parse_server_sdk.dart';

class Mall extends StatefulWidget {
  const Mall({Key? key}) : super(key: key);

  @override
  _MallState createState() => _MallState();
}

class _MallState extends State<Mall> {
  List<ParseObject>? dataList;
  List<ParseObject>? titleList;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    init();
  }

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      name: "商城",
      body: dataList != null
          ? Container(
              width: Get.width,
              child: SingleChildScrollView(
                child: Column(
                  children: [
                    // Container(
                    //   height: 50,
                    //   alignment: Alignment.center,
                    //   child: Text(
                    //     "商城",
                    //     style: TextStyle(fontSize: 16),
                    //   ),
                    // ),
                    GestureDetector(
                      onTap: () {
                        Get.to(() => SouSuo());
                      },
                      child: Container(
                        margin: EdgeInsets.symmetric(horizontal: 16),
                        padding:
                            EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                        decoration: BoxDecoration(
                            borderRadius: BorderRadius.all(Radius.circular(20)),
                            border: Border.all(width: 1, color: Colors.blue)),
                        child: Row(
                          children: [
                            MPIcon(
                              MaterialIcons.search,
                              color: Colors.grey,
                              size: 20,
                            ),
                            SizedBox(
                              width: 10,
                            ),
                            Expanded(
                                child: Text(
                              "输入你想要找的商品 ",
                              style:
                                  TextStyle(fontSize: 14, color: Colors.grey),
                            )),
                            Text(
                              "搜索 ",
                              style:
                                  TextStyle(fontSize: 14, color: Colors.blue),
                            )
                          ],
                        ),
                      ),
                    ),
                    titleList != null
                        ? Container(
                            height: 90,
                            padding: EdgeInsets.symmetric(horizontal: 10),
                            child: ListView(
                              scrollDirection: Axis.horizontal,
                              children: List.generate(
                                  titleList!.length,
                                  (index) => GestureDetector(
                                        child: Container(
                                          padding: EdgeInsets.symmetric(
                                              horizontal: 10, vertical: 10),
                                          child: Column(
                                            children: [
                                              Image.network(
                                                titleList![index]["pic"],
                                                height: 46,
                                                width: 46,
                                              ),
                                              SizedBox(
                                                height: 2,
                                              ),
                                              Text(
                                                "${titleList![index]["name"]} ",
                                                style: TextStyle(fontSize: 14),
                                              )
                                            ],
                                          ),
                                        ),
                                      )),
                            ),
                          )
                        : Container(),
                    Container(
                      padding: EdgeInsets.symmetric(horizontal: 10),
                      child: GridView.builder(
                          itemCount: dataList!.length,
                          shrinkWrap: true,
                          physics: NeverScrollableScrollPhysics(),
                          gridDelegate:
                              const SliverGridDelegateWithFixedCrossAxisCount(
                                  mainAxisSpacing: 0,
                                  crossAxisSpacing: 0,
                                  childAspectRatio: 1 / 1.4,
                                  crossAxisCount: 2),
                          itemBuilder: (context, index) {
                            return GestureDetector(
                              onTap: () {
                                Get.to(() =>
                                    MallInfo(parseObject: dataList![index]));
                              },
                              child: Container(
                                margin: EdgeInsets.symmetric(
                                    horizontal: 6, vertical: 6),
                                decoration: BoxDecoration(
                                    color: Colors.white,
                                    borderRadius: BorderRadius.only(
                                        topLeft: Radius.circular(10),
                                        topRight: Radius.circular(10)),
                                    boxShadow: [
                                      BoxShadow(
                                          offset: Offset(0, 0),
                                          blurRadius: 10,
                                          color: Colors.grey.withOpacity(0.2))
                                    ]),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Expanded(
                                        child: ClipRRect(
                                      borderRadius: BorderRadius.only(
                                          topLeft: Radius.circular(10),
                                          topRight: Radius.circular(10)),
                                      child: Image.network(
                                        dataList![index]["pic"],
                                        fit: BoxFit.cover,
                                        width: Get.width,
                                        height: Get.height,
                                        // height: double.infinity,
                                      ),
                                    )),
                                    Container(
                                      padding: EdgeInsets.all(10),
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            dataList![index]["name"],
                                            style: TextStyle(fontSize: 14),
                                            maxLines: 1,
                                          ),
                                          Row(
                                            crossAxisAlignment:
                                                CrossAxisAlignment.end,
                                            children: [
                                              Container(
                                                margin:
                                                    EdgeInsets.only(bottom: 4),
                                                child: Text(
                                                  "¥",
                                                  style: TextStyle(
                                                      fontSize: 12,
                                                      color: Colors.red),
                                                ),
                                              ),
                                              Text(
                                                dataList![index]["new_price"]
                                                    .toString(),
                                                style: TextStyle(
                                                    fontSize: 20,
                                                    color: Colors.red),
                                              ),
                                              SizedBox(
                                                width: 10,
                                              ),
                                              Container(
                                                margin:
                                                    EdgeInsets.only(bottom: 4),
                                                child: Text(
                                                  "¥ ${dataList![index]["old_price"]}",
                                                  style: TextStyle(
                                                    fontSize: 12,
                                                    color: Colors.grey,
                                                    decoration: TextDecoration
                                                        .lineThrough,
                                                    decorationStyle:
                                                        TextDecorationStyle
                                                            .solid,
                                                    decorationColor:
                                                        Colors.grey,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          )
                                        ],
                                      ),
                                    )
                                  ],
                                ),
                              ),
                            );
                          }),
                    ),
                    SizedBox(
                      height: 100,
                    )
                  ],
                ),
              ),
            )
          : MPCircularProgressIndicator(
              color: Colors.blue,
            ),
    );
  }

  void init() async {
    QueryBuilder<ParseObject> post = QueryBuilder(ParseObject("Mall"));
    post.setLimit(20);
    post.orderByDescending("createdAt");
    dataList = await post.find();
    setState(() {});
    QueryBuilder<ParseObject> post1 = QueryBuilder(ParseObject("MallClass"));

    titleList = await post1.find();
    setState(() {});
  }
}

**Comment by jijkbird** [comment]
这是商城页面的代码

**Comment by PonyCui** [comment]
你看看服务端返回编码是不是有问题吧，不是框架本身的问题。

**Comment by jijkbird** [comment]
这个编码问题我再看一下，不过这个页面偏移该怎么处理呢

**Comment by PonyCui** [comment]
MPScaffold 不需要拿一个 Container 包着，更不需要使用 Get.width。

**Comment by jijkbird** [comment]
好的 我试试

**Comment by jijkbird** [comment]
@PonyCui  能提供一个邮箱吗，我发源码给你看看，搞了很久，一直没搞定这个问题

**Comment by jijkbird** [comment]
[finshing_mp.zip](https://github.com/mpflutter/mpflutter/files/10715047/finshing_mp.zip)
@PonyCui ,还是直接发上面吧

**Comment by jijkbird** [comment]
大佬帮忙看看是啥问题，debug和release的页面错位和中文乱码

**Comment by PonyCui** [comment]
是 http 库的问题，已经修正并发布 0.13.5 版本。
在你的项目中使用 `./mpflutter packages upgrade` 更新依赖就可以。

**Comment by jijkbird** [comment]
@PonyCui  好的 我试试  谢谢大佬

**Comment by jijkbird** [comment]
@PonyCui  大佬，中文乱码问题解决了，不过页面还是偏的，感觉右边有空隙，在iphon6屏幕下，右边的边距更大，感觉像是屏幕的宽度跟显示屏不一致，这种情况有解决的办法吗，谢谢大佬了

**Comment by jijkbird** [comment]
我在入口页面打印屏幕宽度 
Widget build(BuildContext context) {
    print(MediaQuery.of(context).size);

debug模式下，屏幕大小的变更会及时更新
Size(390.0, 844.0)
Size(320.0, 568.0)

但是在release模式下，屏幕不管怎么变更都只会打印
Size(375.0, 667.0)，


这个有办法解决吗

@PonyCui

**Comment by PonyCui** [comment]
宽度问题使用 mpflutter 1.1.1 可以解决

**Comment by jijkbird** [comment]
@PonyCui   谢谢大佬，已解决
