### ISSUE TITLE
AutomaticKeepAliveClientMixin之后，相应的页面还是会重建

### ISSUE THREAD

**Issue by yougeyouge90** [mpflutter/mpflutter#361]
作者大大，当我使用IndexStack之后，子页面使用bool get wantKeepAlive => true;但是切换相邻子页面发现，子页面会重建。貌似keepAlive没有生效？

**Comment by PonyCui** [comment]
目前是显示哪个就重建哪个。

**Comment by yougeyouge90** [comment]
好吧，可不可以后续支持一下keepAlive不？

**Comment by PonyCui** [comment]
可以

**Comment by PonyCui** [comment]
IndexedStack 新增 keepAlive 选项，使用 1.1.0 版本可用。
