### ISSUE TITLE
开发微信时候，希望列表既可以下拉刷新又可以上拉加载更多

### ISSUE THREAD

**Issue by yougeyouge90** [mpflutter/mpflutter#362]
作者大大，我在开发微信小程序时候，我想让一个列表既可以下拉刷新又可以上拉加载更多比较困难，这个有没有什么好的解决方法呢？

**Comment by PonyCui** [comment]
https://mpflutter.com/zh/docs/mp-scaffold 有 onReachBottom → Function?
用于响应页面到达底部时的回调
非必填

**Comment by yougeyouge90** [comment]
嗯嗯，好的感谢。
