### ISSUE TITLE
这个功能的前端代码可以贡献出来吗？

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#368]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/15965000/216797253-6c7e1a10-d18d-4b4c-8f90-30a8285ed3fe.png">

**Comment by ev11ccaatt** [comment]
什么功能，描述清楚一点？

**Comment by songds** [comment]
> 什么功能，描述清楚一点？
1.首页关注、推荐这个滚动tab功能；
2.首页关注、推荐最右边的点击的自定义样式MPPicker功能。
