### ISSUE TITLE
Flutter 3.7.1 issue?

### ISSUE THREAD

**Issue by jackie099** [mpflutter/mpflutter#369]
../../.pub-cache/hosted/pub.mpflutter.com/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' has fewer named arguments than those of overridden method 'File.create'.
  Future<File> create({bool recursive = false});

Downgrading to 3.3.10 fixes it

**Comment by PonyCui** [comment]
Flutter 3.7.0 以上版本已支持，升级 MPFlutter 到 1.2.0 版本即可。
