### ISSUE TITLE
WebGL 实现

### ISSUE THREAD

**Issue by PonyCui** [mpflutter/mpflutter#37]
当前 CustomPaint 提供的是 2D 绘图接口，平台实现也是通过 Canvas 2D API 实现的。
但在实际开发中，确实有需要用到 WebGL，我们需要设计一个新的 MPKit Widget，专用于 WebGL 绘制。
近期计划是支持大部分的 WebGL 1.0 API 使用，中期计划是支持使用 three.js 作为插件，结合 WebGL Widget 实现 3D 绘制及交互。

**Comment by MacroShaw** [comment]
现在支持使用three.js 了吗

**Comment by PonyCui** [comment]
未有 three.js 支持计划

**Comment by MacroShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ppphp** [comment]
现在有canvas的组件吗，没有的话，怎么参考加上

**Comment by MacroShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by PonyCui** [comment]
> 现在有canvas的组件吗，没有的话，怎么参考加上

使用 Flutter 的 CustomPaint

**Comment by MacroShaw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
