### ISSUE TITLE
作者大大，开发小程序完成之后，真机调试一直显示连接中

### ISSUE THREAD

**Issue by yougeyouge90** [mpflutter/mpflutter#370]
作者大大，开发小程序完成之后，真机调试一直显示连接中
![WechatIMG33](https://user-images.githubusercontent.com/46983059/216900793-92a3df40-b828-479e-8352-40b0fa64d8a9.jpeg)

**Comment by PonyCui** [comment]
在 app.js 修改 IP。
https://mpflutter.com/zh/docs/weapp-debug-and-release

**Comment by yougeyouge90** [comment]
嗯嗯
