### ISSUE TITLE
作者大大，小程序可否支持一下pull_to_refresh这个库呢

### ISSUE THREAD

**Issue by yougeyouge90** [mpflutter/mpflutter#373]
作者大大，我觉得pull_to_refresh这个蛮好用，可否支持一下依赖这个第三方库

**Comment by PonyCui** [comment]
小程序本身限制，无法支持。

**Comment by PonyCui** [comment]
relate issue https://github.com/mpflutter/mpflutter/issues/374 .
close this issue, reply to https://github.com/mpflutter/mpflutter/issues/374 .
