### ISSUE TITLE
SingleChildScrollView和ListView滚动问题,SingleChildScrollView嵌入Row横向滚动宽度越界异常,ListView滚动导致,滚动事件穿透

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#375]
1.SingleChildScrollView嵌入Row横向滚动宽度越界异常,拉宽整个屏幕;
2.使用showMPDialogshi弹出层ListView滚动导致,滚动事件穿透下层组件,导致滚动混乱.

**Comment by PonyCui** [comment]
Row mainAxisSize 设置为 min

**Comment by PonyCui** [comment]
AbsorbPointer 包裹 ListView

**Comment by songds** [comment]
> Row mainAxisSize 设置为 min

不行，还是滚动异常

**Comment by PonyCui** [comment]
提供一下有问题的代码，最好有一个完整的 demo。

**Comment by songds** [comment]
项目代码，可以直接运行，第一个页面的头部，你都可以点击一下，滚动异常和滚动事件穿透还是存在的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mpflutter/mpflutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月8日(星期三) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mpflutter/mpflutter] SingleChildScrollView和ListView滚动问题,SingleChildScrollView嵌入Row横向滚动宽度越界异常,ListView滚动导致,滚动事件穿透 (Issue #375)





 
提供一下有问题的代码，最好有一个完整的 demo。

**Comment by songds** [comment]
> 提供一下有问题的代码，最好有一个完整的 demo。

源代码通过邮件发送给你了，麻烦查收

**Comment by songds** [comment]
> 提供一下有问题的代码，最好有一个完整的 demo。

所有问题还是存在

**Comment by songds** [comment]
> 提供一下有问题的代码，最好有一个完整的 demo。

有结果了吗？

**Comment by PonyCui** [comment]
没收到源码

**Comment by songds** [comment]
> 没收到源码

![image](https://user-images.githubusercontent.com/15965000/217772094-845c0956-dbfd-4711-8787-02e7b7b4370d.png)

**Comment by PonyCui** [comment]
这个邮箱我收不到的，你还是在这里列出一个最小化的 demo 吧。

**Comment by songds** [comment]
> 这个邮箱我收不到的，你还是在这里列出一个最小化的 demo 吧。

import 'package:farming_wx_h5/common/styles/common_colors.dart';
import 'package:farming_wx_h5/common/styles/common_icons.dart';
import 'package:farming_wx_h5/common/styles/common_styles.dart';
import 'package:farming_wx_h5/widgets/common/tabs_menus.dart';
import 'package:farming_wx_h5/widgets/common/wx_tabbar_view.dart';
import 'package:farming_wx_h5/widgets/common_widgets.dart';
import 'package:flutter/widgets.dart';
import 'package:mpcore/mpcore.dart';

class HomeSupplyPage extends StatefulWidget {
  @override
  State<HomeSupplyPage> createState() => _HomeSupplyPageState();
}

class _HomeSupplyPageState extends State<HomeSupplyPage> {
  bool showMenu = false;

  List<String> classSubs = [
    '玉竹',
    '土茯苓',
    '太子参',
    '天花粉',
    '天冬',
    '乌药',
    '徐长卿下院',
    '香附',
    '续断',
    '西洋参',
    '细辛',
    '玄参',
    /*'夏天无',
    '元胡',
    '郁金',
    '延胡索',
    '薤白',
    '泽泻',
    '朱砂根',
    '知母',
    '藏木香',
    '紫草',
    '紫菀',*/
  ];

  List<String> tabs = [
    '推荐',
    '根茎类',
    '果实籽仁类',
    '全草类',
    '花类',
    '叶类',
    '动物类',
    '树皮类',
    '藤木类',
    '矿物菌脂类',
  ];

  List<Widget> _createMenuTabs(context) {
    bool active = false;
    return tabs.map((e) {
      if (active) {
        return TabsMenus(
          title: e,
          active: false,
        );
      } else {
        setState(() => {active = true});
        return TabsMenus(
          title: e,
          active: active,
        );
      }
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      name: '供应信息',
      body: Column(
        children: [
          Container(
            padding: EdgeInsets.fromLTRB(0, 5, 0, 0),
            alignment: Alignment.centerLeft,
            width: MediaQuery.of(context).size.width,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Container(
                  width: MediaQuery.of(context).size.width - 300,
                  child: SingleChildScrollView(
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: _createMenuTabs(context),
                    ),
                  ),
                ),
                GestureDetector(
                  child: Container(
                    padding: EdgeInsets.fromLTRB(10, 0, 10, 5),
                    alignment: Alignment.center,
                    child: CommonIcons.DEFAULT_MENU,
                  ),
                  onTap: () {
                    showMPDialog(
                      barrierColor: CommonColors.black1.withOpacity(0.5),
                      barrierDismissible: false,
                      context: context,
                      builder: (context) {
                        return Stack(
                          children: [
                            Positioned(
                              bottom: 0,
                              child: Container(
                                width: MediaQuery.of(context).size.width,
                                height:
                                    MediaQuery.of(context).size.height - 100,
                                padding: EdgeInsets.all(10),
                                decoration: BoxDecoration(
                                  boxShadow: [CommonStyles.defaultShadow],
                                  color: CommonColors.white,
                                  borderRadius: BorderRadius.only(
                                      topLeft: Radius.circular(10),
                                      topRight: Radius.circular(10)),
                                ),
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      height: 30,
                                      child: Stack(
                                        children: [
                                          Container(
                                              width: MediaQuery.of(context)
                                                  .size
                                                  .width,
                                              alignment: Alignment.topCenter,
                                              child: Text(
                                                '推荐',
                                                style:
                                                    CommonStyles.tSBlackBold_18,
                                              )),
                                          Positioned(
                                            right: 0,
                                            top: 0,
                                            child: GestureDetector(
                                              onTap: () {
                                                Navigator.of(context).pop();
                                              },
                                              child: CommonIcons.DEFAULT_CLOSE,
                                            ),
                                          )
                                        ],
                                      ),
                                    ),
                                    Expanded(
                                      child: AbsorbPointer(
                                        child: ListView.builder(
                                          scrollDirection: Axis.vertical,
                                          itemBuilder: _classItemBuilderTwo,
                                          itemCount: classSubs.length,
                                        ),
                                      ),
                                    )
                                  ],
                                ),
                              ),
                            )
                          ],
                        );
                      },
                    );
                  },
                ),
              ],
            ),
          ),
          Container(
            decoration: BoxDecoration(boxShadow: [CommonStyles.defaultShadow]),
            child: Row(
              children: [
                Container(
                  width: 100,
                  height: MediaQuery.of(context).size.height,
                  decoration: BoxDecoration(
                    color: CommonColors.grey.withOpacity(.2),
                    borderRadius: BorderRadius.only(
                      topRight: Radius.circular(20),
                    ),
                  ),
                  child: ListView.builder(
                    itemBuilder: _classItemBuilder,
                    itemCount: classSubs.length,
                  ),
                ),
                Container(
                  color: CommonColors.white,
                  height: MediaQuery.of(context).size.height,
                )
              ],
            ),
          )
        ],
      ),
    );
  }

  Widget _classItemBuilder(context, index) {
    return Container(
      alignment: Alignment.center,
      padding: EdgeInsets.fromLTRB(5, 10, 5, 0),
      child: Text(
        classSubs[index],
        style: TextStyle(fontSize: 14),
      ),
    );
  }

  Widget _classItemBuilderTwo(context, index) {
    return Container(
      alignment: Alignment.topLeft,
      padding: EdgeInsets.fromLTRB(5, 10, 5, 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'A',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'B',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'C',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'D',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'E',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'F',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
            ],
          ),
          dividerLine(),
          Container(
            padding: EdgeInsets.fromLTRB(0, 5, 0, 0),
            width: MediaQuery.of(context).size.width,
            child: Wrap(
              spacing: 8.0, // 主轴(水平)方向间距
              runSpacing: 4.0, // 纵轴（垂直）方向间距
              alignment: WrapAlignment.start, //沿主轴方向居中
              children: classSubs
                  .map(
                    (e) => GestureDetector(
                      onTap: () => {},
                      child: Container(
                        width: 80,
                        alignment: Alignment.center,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.all(Radius.circular(2)),
                          color: CommonColors.grey.withOpacity(0.2),
                        ),
                        padding: EdgeInsets.all(10),
                        child: Text(
                          e,
                          style: TextStyle(fontSize: 12),
                        ),
                      ),
                    ),
                  )
                  .toList(),
            ),
          )
        ],
      ),
    );
  }
}

**Comment by songds** [comment]
> 这个邮箱我收不到的，你还是在这里列出一个最小化的 demo 吧。
import 'package:farming_wx_h5/common/styles/common_colors.dart';
import 'package:farming_wx_h5/common/styles/common_icons.dart';
import 'package:farming_wx_h5/common/styles/common_styles.dart';
import 'package:farming_wx_h5/widgets/common/tabs_menus.dart';
import 'package:farming_wx_h5/widgets/common/wx_tabbar_view.dart';
import 'package:farming_wx_h5/widgets/common_widgets.dart';
import 'package:flutter/widgets.dart';
import 'package:mpcore/mpcore.dart';

class HomeSupplyPage extends StatefulWidget {
  @override
  State<HomeSupplyPage> createState() => _HomeSupplyPageState();
}

class _HomeSupplyPageState extends State<HomeSupplyPage> {
  bool showMenu = false;

  List<String> classSubs = [
    '玉竹',
    '土茯苓',
    '太子参',
    '天花粉',
    '天冬',
    '乌药',
    '徐长卿下院',
    '香附',
    '续断',
    '西洋参',
    '细辛',
    '玄参',
    /*'夏天无',
    '元胡',
    '郁金',
    '延胡索',
    '薤白',
    '泽泻',
    '朱砂根',
    '知母',
    '藏木香',
    '紫草',
    '紫菀',*/
  ];

  List<String> tabs = [
    '推荐',
    '根茎类',
    '果实籽仁类',
    '全草类',
    '花类',
    '叶类',
    '动物类',
    '树皮类',
    '藤木类',
    '矿物菌脂类',
  ];

  List<Widget> _createMenuTabs(context) {
    bool active = false;
    return tabs.map((e) {
      if (active) {
        return TabsMenus(
          title: e,
          active: false,
        );
      } else {
        setState(() => {active = true});
        return TabsMenus(
          title: e,
          active: active,
        );
      }
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      name: '供应信息',
      body: Column(
        children: [
          Container(
            padding: EdgeInsets.fromLTRB(0, 5, 0, 0),
            alignment: Alignment.centerLeft,
            width: MediaQuery.of(context).size.width,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Container(
                  width: MediaQuery.of(context).size.width - 300,
                  child: SingleChildScrollView(
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: _createMenuTabs(context),
                    ),
                  ),
                ),
                GestureDetector(
                  child: Container(
                    padding: EdgeInsets.fromLTRB(10, 0, 10, 5),
                    alignment: Alignment.center,
                    child: CommonIcons.DEFAULT_MENU,
                  ),
                  onTap: () {
                    showMPDialog(
                      barrierColor: CommonColors.black1.withOpacity(0.5),
                      barrierDismissible: false,
                      context: context,
                      builder: (context) {
                        return Stack(
                          children: [
                            Positioned(
                              bottom: 0,
                              child: Container(
                                width: MediaQuery.of(context).size.width,
                                height:
                                    MediaQuery.of(context).size.height - 100,
                                padding: EdgeInsets.all(10),
                                decoration: BoxDecoration(
                                  boxShadow: [CommonStyles.defaultShadow],
                                  color: CommonColors.white,
                                  borderRadius: BorderRadius.only(
                                      topLeft: Radius.circular(10),
                                      topRight: Radius.circular(10)),
                                ),
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      height: 30,
                                      child: Stack(
                                        children: [
                                          Container(
                                              width: MediaQuery.of(context)
                                                  .size
                                                  .width,
                                              alignment: Alignment.topCenter,
                                              child: Text(
                                                '推荐',
                                                style:
                                                    CommonStyles.tSBlackBold_18,
                                              )),
                                          Positioned(
                                            right: 0,
                                            top: 0,
                                            child: GestureDetector(
                                              onTap: () {
                                                Navigator.of(context).pop();
                                              },
                                              child: CommonIcons.DEFAULT_CLOSE,
                                            ),
                                          )
                                        ],
                                      ),
                                    ),
                                    Expanded(
                                      child: AbsorbPointer(
                                        child: ListView.builder(
                                          scrollDirection: Axis.vertical,
                                          itemBuilder: _classItemBuilderTwo,
                                          itemCount: classSubs.length,
                                        ),
                                      ),
                                    )
                                  ],
                                ),
                              ),
                            )
                          ],
                        );
                      },
                    );
                  },
                ),
              ],
            ),
          ),
          Container(
            decoration: BoxDecoration(boxShadow: [CommonStyles.defaultShadow]),
            child: Row(
              children: [
                Container(
                  width: 100,
                  height: MediaQuery.of(context).size.height,
                  decoration: BoxDecoration(
                    color: CommonColors.grey.withOpacity(.2),
                    borderRadius: BorderRadius.only(
                      topRight: Radius.circular(20),
                    ),
                  ),
                  child: ListView.builder(
                    itemBuilder: _classItemBuilder,
                    itemCount: classSubs.length,
                  ),
                ),
                Container(
                  color: CommonColors.white,
                  height: MediaQuery.of(context).size.height,
                )
              ],
            ),
          )
        ],
      ),
    );
  }

  Widget _classItemBuilder(context, index) {
    return Container(
      alignment: Alignment.center,
      padding: EdgeInsets.fromLTRB(5, 10, 5, 0),
      child: Text(
        classSubs[index],
        style: TextStyle(fontSize: 14),
      ),
    );
  }

  Widget _classItemBuilderTwo(context, index) {
    return Container(
      alignment: Alignment.topLeft,
      padding: EdgeInsets.fromLTRB(5, 10, 5, 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'A',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'B',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'C',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'D',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'E',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'F',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
            ],
          ),
          dividerLine(),
          Container(
            padding: EdgeInsets.fromLTRB(0, 5, 0, 0),
            width: MediaQuery.of(context).size.width,
            child: Wrap(
              spacing: 8.0, // 主轴(水平)方向间距
              runSpacing: 4.0, // 纵轴（垂直）方向间距
              alignment: WrapAlignment.start, //沿主轴方向居中
              children: classSubs
                  .map(
                    (e) => GestureDetector(
                      onTap: () => {},
                      child: Container(
                        width: 80,
                        alignment: Alignment.center,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.all(Radius.circular(2)),
                          color: CommonColors.grey.withOpacity(0.2),
                        ),
                        padding: EdgeInsets.all(10),
                        child: Text(
                          e,
                          style: TextStyle(fontSize: 12),
                        ),
                      ),
                    ),
                  )
                  .toList(),
            ),
          )
        ],
      ),
    );
  }
}

**Comment by songds** [comment]
> 这个邮箱我收不到的，你还是在这里列出一个最小化的 demo 吧。

有结果了吗？

**Comment by PonyCui** [comment]
你发这个邮箱我是收不到附件的

**Comment by songds** [comment]
> 你发这个邮箱我是收不到附件的

我单独在评论区给您发了demo的代码呢
import 'package:farming_wx_h5/common/styles/common_colors.dart';
import 'package:farming_wx_h5/common/styles/common_icons.dart';
import 'package:farming_wx_h5/common/styles/common_styles.dart';
import 'package:farming_wx_h5/widgets/common/tabs_menus.dart';
import 'package:farming_wx_h5/widgets/common/wx_tabbar_view.dart';
import 'package:farming_wx_h5/widgets/common_widgets.dart';
import 'package:flutter/widgets.dart';
import 'package:mpcore/mpcore.dart';

class HomeSupplyPage extends StatefulWidget {
  @override
  State<HomeSupplyPage> createState() => _HomeSupplyPageState();
}

class _HomeSupplyPageState extends State<HomeSupplyPage> {
  bool showMenu = false;

  List<String> classSubs = [
    '玉竹',
    '土茯苓',
    '太子参',
    '天花粉',
    '天冬',
    '乌药',
    '徐长卿下院',
    '香附',
    '续断',
    '西洋参',
    '细辛',
    '玄参',
    /*'夏天无',
    '元胡',
    '郁金',
    '延胡索',
    '薤白',
    '泽泻',
    '朱砂根',
    '知母',
    '藏木香',
    '紫草',
    '紫菀',*/
  ];

  List<String> tabs = [
    '推荐',
    '根茎类',
    '果实籽仁类',
    '全草类',
    '花类',
    '叶类',
    '动物类',
    '树皮类',
    '藤木类',
    '矿物菌脂类',
  ];

  List<Widget> _createMenuTabs(context) {
    bool active = false;
    return tabs.map((e) {
      if (active) {
        return TabsMenus(
          title: e,
          active: false,
        );
      } else {
        setState(() => {active = true});
        return TabsMenus(
          title: e,
          active: active,
        );
      }
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
      name: '供应信息',
      body: Column(
        children: [
          Container(
            padding: EdgeInsets.fromLTRB(0, 5, 0, 0),
            alignment: Alignment.centerLeft,
            width: MediaQuery.of(context).size.width,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Container(
                  width: MediaQuery.of(context).size.width - 300,
                  child: SingleChildScrollView(
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: _createMenuTabs(context),
                    ),
                  ),
                ),
                GestureDetector(
                  child: Container(
                    padding: EdgeInsets.fromLTRB(10, 0, 10, 5),
                    alignment: Alignment.center,
                    child: CommonIcons.DEFAULT_MENU,
                  ),
                  onTap: () {
                    showMPDialog(
                      barrierColor: CommonColors.black1.withOpacity(0.5),
                      barrierDismissible: false,
                      context: context,
                      builder: (context) {
                        return Stack(
                          children: [
                            Positioned(
                              bottom: 0,
                              child: Container(
                                width: MediaQuery.of(context).size.width,
                                height:
                                    MediaQuery.of(context).size.height - 100,
                                padding: EdgeInsets.all(10),
                                decoration: BoxDecoration(
                                  boxShadow: [CommonStyles.defaultShadow],
                                  color: CommonColors.white,
                                  borderRadius: BorderRadius.only(
                                      topLeft: Radius.circular(10),
                                      topRight: Radius.circular(10)),
                                ),
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      height: 30,
                                      child: Stack(
                                        children: [
                                          Container(
                                              width: MediaQuery.of(context)
                                                  .size
                                                  .width,
                                              alignment: Alignment.topCenter,
                                              child: Text(
                                                '推荐',
                                                style:
                                                    CommonStyles.tSBlackBold_18,
                                              )),
                                          Positioned(
                                            right: 0,
                                            top: 0,
                                            child: GestureDetector(
                                              onTap: () {
                                                Navigator.of(context).pop();
                                              },
                                              child: CommonIcons.DEFAULT_CLOSE,
                                            ),
                                          )
                                        ],
                                      ),
                                    ),
                                    Expanded(
                                      child: AbsorbPointer(
                                        child: ListView.builder(
                                          scrollDirection: Axis.vertical,
                                          itemBuilder: _classItemBuilderTwo,
                                          itemCount: classSubs.length,
                                        ),
                                      ),
                                    )
                                  ],
                                ),
                              ),
                            )
                          ],
                        );
                      },
                    );
                  },
                ),
              ],
            ),
          ),
          Container(
            decoration: BoxDecoration(boxShadow: [CommonStyles.defaultShadow]),
            child: Row(
              children: [
                Container(
                  width: 100,
                  height: MediaQuery.of(context).size.height,
                  decoration: BoxDecoration(
                    color: CommonColors.grey.withOpacity(.2),
                    borderRadius: BorderRadius.only(
                      topRight: Radius.circular(20),
                    ),
                  ),
                  child: ListView.builder(
                    itemBuilder: _classItemBuilder,
                    itemCount: classSubs.length,
                  ),
                ),
                Container(
                  color: CommonColors.white,
                  height: MediaQuery.of(context).size.height,
                )
              ],
            ),
          )
        ],
      ),
    );
  }

  Widget _classItemBuilder(context, index) {
    return Container(
      alignment: Alignment.center,
      padding: EdgeInsets.fromLTRB(5, 10, 5, 0),
      child: Text(
        classSubs[index],
        style: TextStyle(fontSize: 14),
      ),
    );
  }

  Widget _classItemBuilderTwo(context, index) {
    return Container(
      alignment: Alignment.topLeft,
      padding: EdgeInsets.fromLTRB(5, 10, 5, 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'A',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'B',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'C',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'D',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'E',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 0),
                child: Text(
                  'F',
                  style: CommonStyles.tSXBRedBlod_14,
                ),
              ),
            ],
          ),
          dividerLine(),
          Container(
            padding: EdgeInsets.fromLTRB(0, 5, 0, 0),
            width: MediaQuery.of(context).size.width,
            child: Wrap(
              spacing: 8.0, // 主轴(水平)方向间距
              runSpacing: 4.0, // 纵轴（垂直）方向间距
              alignment: WrapAlignment.start, //沿主轴方向居中
              children: classSubs
                  .map(
                    (e) => GestureDetector(
                      onTap: () => {},
                      child: Container(
                        width: 80,
                        alignment: Alignment.center,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.all(Radius.circular(2)),
                          color: CommonColors.grey.withOpacity(0.2),
                        ),
                        padding: EdgeInsets.all(10),
                        child: Text(
                          e,
                          style: TextStyle(fontSize: 12),
                        ),
                      ),
                    ),
                  )
                  .toList(),
            ),
          )
        ],
      ),
    );
  }
}

**Comment by PonyCui** [comment]
这种代码我没法调试

**Comment by songds** [comment]
> 这种代码我没法调试

给个邮箱我给您发过去代码

**Comment by songds** [comment]
> 这种代码我没法调试

给个邮箱我给您发过去代码，刚好我提了好多问题。你可以一起看

**Comment by songds** [comment]
> 这种代码我没法调试

通过什么方式可以联系你

**Comment by PonyCui** [comment]
没有敏感信息就打包发这里吧

**Comment by songds** [comment]
> 没有敏感信息就打包发这里吧
1.问题1 SingleChildScrollView和ListView滚动问题,SingleChildScrollView嵌入Row横向滚动宽度越界异常,ListView滚动导致,滚动事件穿透 #375   对应代码home_supply_page.dart
2.问题2 使用MPPageView时，把MPPageView做轮播图时放到Stack组件中使用，导致其他Positioned不生效 #392。对应代码product_detail.dart
3.问题3 SingleChildScrollView嵌套->Column在嵌套->WaterfallView，然后WaterfallView控制为1个数量时会多出很多高度，求解 #393。对应代码product_detail.dart

[farming_wx_h5.zip](https://github.com/mpflutter/mpflutter/files/10810582/farming_wx_h5.zip)

**Comment by songds** [comment]
> 没有敏感信息就打包发这里吧

有结果了吗？

**Comment by songds** [comment]
> 这种代码我没法调试



> 提供一下有问题的代码，最好有一个完整的 demo。

有结果了吗？

**Comment by PonyCui** [comment]
使用以下方法解决 buildMenus 布局问题
```dart
Container(
            width: MediaQuery.of(context).size.width - 44,
            height: 32,
            child: ListView(
              scrollDirection: Axis.horizontal,
              children: [..._createMenuTabs(context)],
            ),
          ),
```
