### ISSUE TITLE
会考虑mpflutter 小游戏吗？

### ISSUE THREAD

**Issue by DevinXiaoBai** [mpflutter/mpflutter#376]
你好 会考虑mpflutter 开发小游戏吗？
或者能给些思路吧flutter 代码转到微信小游戏？

**Comment by PonyCui** [comment]
mpflutter 不会考虑小游戏。
你可以尝试把 flame 移植到小游戏。

**Comment by DevinXiaoBai** [comment]
我尝试了几种办法 但是不知道怎么嫁接 能给点思路吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mpflutter/mpflutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月9日(星期四) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mpflutter/mpflutter] 会考虑mpflutter 小游戏吗？ (Issue #376)





 
mpflutter 不会考虑小游戏。
 你可以尝试把 flame 移植到小游戏。
