### ISSUE TITLE
web跨域不知道咋解决呢，作者大大

### ISSUE THREAD

**Issue by yougeyouge90** [mpflutter/mpflutter#378]
Access to XMLHttpRequest at 'https://www.wanandroid.com/banner/json' from origin 'http://103.151.217.215:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by PonyCui** [comment]
提问前看文档 https://mpflutter.com/zh/docs/web-cors
