### ISSUE TITLE
这个瀑布流功能可以前端代码贡献出来吗？flutter_staggered_grid_view，这个支持多少版本的呢？我试了最新版本不支持

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#379]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/15965000/218234333-2e9875b1-260a-4a60-a86c-fac1851aeb52.png">

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter/blob/master/packages/mpflutter_sample/lib/list/grid_view_waterfall_page.dart
