### ISSUE TITLE
release页面经常白屏

### ISSUE THREAD

**Issue by jijkbird** [mpflutter/mpflutter#386]
release页面经常白屏，网络请求的数据都到位了的，默认显示的无数据，请求到数据之后渲染到页面上，打开页面的时候显示的是无数据，然后数据请求到之后刷新就白屏了

**Comment by jijkbird** [comment]
好像出现异常的都是 MPPageView里面的页面

**Comment by PonyCui** [comment]
提供一个可复现问题的 Demo

**Comment by jijkbird** [comment]
@PonyCui  我现在已经改了页面了，不使用MPPageView了，不过顺便问问大佬，我想通过小程序获取照片上传，但是图片的地址都是虚拟地址，image组件能正常显示虚拟地址的图片，但是上传的话，没办法使用这个路径，有什么办法能解决吗

**Comment by PonyCui** [comment]
> @PonyCui 我现在已经改了页面了，不使用MPPageView了，不过顺便问问大佬，我想通过小程序获取照片上传，但是图片的地址都是虚拟地址，image组件能正常显示虚拟地址的图片，但是上传的话，没办法使用这个路径，有什么办法能解决吗

正在解决，应该会添加一些 Utils 方法。
