### ISSUE TITLE
通过mpflutter的套壳工程创建一个android的项目，运行起来报错

### ISSUE THREAD

**Issue by StevenYan88** [mpflutter/mpflutter#388]
通过mpflutter的套壳工程创建一个android的项目，运行起来报错
Unccaught exception: FileSystemException: Cannot create file, path = './.mpflutter-dev-tools' (OS Error: Read-only file system, errno = 30), #0      _File.throwIfError (dart:io/file_impl.dart:629:7)
    #1      _File.createSync (dart:io/file_impl.dart:289:5)
    #2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:123:13)
    #3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:13)
    #4      ga (package:mpcore/ga.dart:3:12)
    #5      ga (package:mpcore/ga.dart)
    #6      MPChannel.setupHotReload (package:mpcore/channel/channel_io.dart:43:5)
    #7      MPCore.connectToHostChannel.<anonymous closure> (package:mpcore/mpcore.dart:140:29)
    #8      _rootRun (dart:async/zone.dart:1398:13)
    #9      _CustomZone.run (dart:async/zone.dart:1300:19)
    #10     _runZoned (dart:async/zone.dart:1803:10)
    #11     runZonedGuarded (dart:async/zone.dart:1791:12)
    #12     MPCore.connectToHostChannel (package:mpcore/mpcore.dart:135:13)
    #13     main (package:mpflutter_template/main.dart:7:12)
    #14     _runMain.<anonymous closur

**Comment by PonyCui** [comment]
https://mpflutter.com/zh/docs/fn-intro

**Comment by PonyCui** [comment]
如果需要在 native 上运行 mpflutter 按照该文档操作 https://mpflutter.com/zh/docs/fn-intro
