### ISSUE TITLE
微信真机预览的时候Free data with key "kboneRender" of page "pages/index/index"

### ISSUE THREAD

**Issue by gitHubDujianfeng** [mpflutter/mpflutter#390]
微信真机预览的时候 、提示这个错误 、然后一直链接中、不知道是什么原因 。Free data with key "kboneRender" of page "pages/index/index" seems not a simple value. Result of deep cloning this value in page instantiation may be unexpected. Consider assigning this value at the beginning of onLoad method.

**Comment by PonyCui** [comment]
https://mpflutter.com/zh/docs/weapp-debug-and-release
| 你也可以在真机上调试应用，只需要将 app.js 中的 IP 替换成电脑局域网 IP 就可以了，原理也是一样的走 websocket。
