### ISSUE TITLE
SingleChildScrollView嵌套->Column在嵌套->WaterfallView，然后WaterfallView控制为1个数量时会多出很多高度，求解

### ISSUE THREAD

**Issue by songds** [mpflutter/mpflutter#393]
有问题代码
<img width="369" alt="image" src="https://user-images.githubusercontent.com/15965000/220536535-961d812e-88cc-43ac-8f4f-1077bff3ca2c.png">

Container(
                color: Colors.white,
                child: WaterfallView.builder(
                  shrinkWrap: true,
                  //收缩包装
                  physics: NeverScrollableScrollPhysics(),
                  //禁用滚动
                  gridDelegate: SliverWaterfallDelegate(
                    crossAxisCount: 2,
                  ),
                  itemBuilder: (context, index) {
                    return Container(
                      height: 10 + 20 * (index % 5),
                      color: Colors.blue,
                      child: Center(child: Text('Index - $index')),
                    );
                  },
                  itemCount: 1,
                ),
              )

**Comment by songds** [comment]
附上全部代码
import 'package:farming_wx_h5/common/styles/common_colors.dart';
import 'package:farming_wx_h5/common/styles/common_icons.dart';
import 'package:farming_wx_h5/common/styles/common_styles.dart';
import 'package:farming_wx_h5/widgets/common/Indicator.dart';
import 'package:farming_wx_h5/widgets/common_widgets.dart';
import 'package:flutter/widgets.dart';
import 'package:mpcore/mpcore.dart';

class ProductDetailPage extends StatefulWidget {
  @override
  State<ProductDetailPage> createState() => _ProductDetailState();
}

class _ProductDetailState extends State<ProductDetailPage> {
  ///是否显示注意提示
  bool _isNoticePrompt = true;
  final pageController = MPPageController(initialPage: 1);
  List<Image> images = [
    Image.network(
      "https://img.kmb2b.com/user/supply/20230219/20230219082123_26.jpg",
      fit: BoxFit.fitWidth,
    ),
    Image.network(
      "https://img.kmb2b.com/user/supply/20230219/20230219082207_198.jpg",
      fit: BoxFit.fitWidth,
    ),
    Image.network(
      "https://img.kmb2b.com/user/supply/20230218/20230218131547_767.jpg",
      fit: BoxFit.fitWidth,
    ),
  ];

  @override
  void initState() {
    super.initState();
    pageController.addListener(() {
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return MPScaffold(
        backgroundColor: CommonColors.grey7,
        body: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              _buildNoticePrompt(context),
              _buildSlideshow(context),
              _buildDetail(context),
              Container(
                alignment: Alignment.centerLeft,
                margin: EdgeInsets.fromLTRB(0, 10, 0, 0),
                padding: EdgeInsets.fromLTRB(0, 5, 0, 5),
                decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border(
                        bottom:
                            BorderSide(color: CommonColors.grey, width: 0.5))),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                    Container(
                      width: 2,
                      height: 20,
                      decoration: BoxDecoration(color: CommonColors.xbRed),
                    ),
                    Container(
                      margin: EdgeInsets.fromLTRB(10, 0, 0, 0),
                      child: Text(
                        'TA的其他供应信息',
                        style: CommonStyles.tSBlack_16,
                      ),
                    )
                  ],
                ),
              ),
              Container(
                color: Colors.white,
                child: WaterfallView.builder(
                  shrinkWrap: true,
                  //收缩包装
                  physics: NeverScrollableScrollPhysics(),
                  //禁用滚动
                  gridDelegate: SliverWaterfallDelegate(
                    crossAxisCount: 2,
                  ),
                  itemBuilder: (context, index) {
                    return Container(
                      height: 10 + 20 * (index % 5),
                      color: Colors.blue,
                      child: Center(child: Text('Index - $index')),
                    );
                  },
                  itemCount: 1,
                ),
              )
            ],
          ),
        ));
  }

  ///轮播图
  Widget _buildSlideshow(context) {
    return Stack(
      children: [
        Container(
          height: MediaQuery.of(context).size.width,
          child: MPPageView(
            loop: true,
            autoplay: true,
            controller: pageController,
            children: List<Widget>.generate(
                3,
                (index) => ConstrainedBox(
                      constraints: const BoxConstraints.expand(),
                      child: images[index],
                    )),
          ),
        ),
        Positioned(
          bottom: 5,
          child: Container(
            child: Indicator(
              controller: pageController,
              itemCount: 3,
              margin: EdgeInsets.fromLTRB(0, 0, 5, 0),
              normalColor: CommonColors.grey.withOpacity(0.6),
              selectedColor: CommonColors.xbRed,
            ),
          ),
        )
      ],
    );
  }

  ///警告信息
  Widget _buildNoticePrompt(context) {
    return _isNoticePrompt
        ? Container(
            color: CommonColors.yellow.withOpacity(0.1),
            padding: EdgeInsets.fromLTRB(15, 10, 15, 10),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  '请您注意甄别信息真伪，自主把控交易风险',
                  style: TextStyle(
                      color: CommonColors.xbRed.withOpacity(0.8),
                      fontSize: 14,
                      fontWeight: FontWeight.bold),
                ),
                GestureDetector(
                  onTap: () {
                    setState(() {
                      _isNoticePrompt = false;
                    });
                  },
                  child: MPIcon(CommonIcons.DEFAULT_CLOSE_ICON,
                      size: 20, color: CommonColors.xbRed.withOpacity(0.8)),
                )
              ],
            ),
          )
        : Container();
  }

  ///详细信息
  Widget _buildDetail(context) {
    return Container(
      color: Colors.white,
      margin: EdgeInsets.fromLTRB(0, 5, 0, 0),
      padding: EdgeInsets.fromLTRB(10, 0, 10, 20),
      width: MediaQuery.of(context).size.width,
      alignment: Alignment.centerLeft,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Container(
            width: MediaQuery.of(context).size.width,
            padding: EdgeInsets.fromLTRB(10, 0, 0, 10),
            child: Text(
              '淫羊藿',
              style: CommonStyles.tSBlackBold_20,
            ),
          ),
          titleText(
            margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
            leftText: Characters('价  格').join('\u{2006}'),
            rightText: '面议',
          ),
          titleText(
              margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
              leftText: Characters('规  格').join('\u{2006}'),
              rightText: '统',
              rightStyle: CommonStyles.tSBlack_14),
          titleText(
              margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
              leftText: Characters('产  地').join('\u{2006}'),
              rightText: '郴州',
              rightStyle: CommonStyles.tSBlack_14),
          titleText(
              margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
              leftText: Characters('数  量').join('\u{2006}'),
              rightText: '大货',
              rightStyle: CommonStyles.tSBlack_14),
          titleText(
              margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
              leftText: '仓储地',
              rightText: '湖南郴州桂阳莲塘镇仓库',
              rightStyle: CommonStyles.tSBlack_14),
          titleText(
              margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
              leftText: '档口号',
              rightText: '湖南郴州桂阳莲塘镇仓库',
              rightStyle: CommonStyles.tSBlack_14),
          titleText(
              margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
              leftText: Characters('备  注').join('\u{2006}'),
              rightText: '湖南郴州桂阳莲塘镇仓库',
              rightStyle: CommonStyles.tSBlack_14),
          SizedBox(
            height: 10,
          ),
          dividerLine(height: 0.5),
          Container(
            margin: EdgeInsets.fromLTRB(10, 5, 0, 5),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    headWidget(
                        'https://img.kmb2b.com/user/supply/20210830/20210830222719_465_4.jpg'),
                    Padding(
                      padding: EdgeInsets.only(left: 10),
                      child: Text(
                        '淫羊藿专营',
                        style: CommonStyles.tSBlackBold_16,
                      ),
                    )
                  ],
                ),
                Container(
                  child: commonBtn(
                    '进店逛逛',
                    onTap: () {},
                    colors: [CommonColors.red2, CommonColors.xbRed],
                  ),
                )
              ],
            ),
          ),
          dividerLine(height: 0.5),
          Column(
            children: [
              Container(
                  width: MediaQuery.of(context).size.width,
                  padding: EdgeInsets.fromLTRB(10, 10, 10, 10),
                  child: Text(
                    '联系信息',
                    style: CommonStyles.tSBlackBold_20,
                  )),
              titleText(
                  margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
                  leftText: Characters('认证信息').join('\u{2006}'),
                  rightText: '个人认证',
                  rightStyle: CommonStyles.tSBlack_14),
              titleText(
                  margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
                  leftText: Characters('联系人').join('\u{2006}'),
                  rightText: '廖老板',
                  rightStyle: CommonStyles.tSBlack_14),
              titleText(
                  margin: EdgeInsets.only(left: 10, top: 0, bottom: 0),
                  leftText: Characters('联系电话').join('\u{2006}'),
                  rightText: '183*******',
                  rightStyle: CommonStyles.tSBlack_14),
            ],
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    pageController.dispose();
  }
}

**Comment by PonyCui** [comment]
这个问题暂时无法解决，你可以使用 CustomScrollView 代替 SingleChildScrollView 临时解决。
