### ISSUE TITLE
对MPPageView提供controller 以用来获取当前index

### ISSUE THREAD

**Issue by itMcdull** [mpflutter/mpflutter#40]
对于现在MPPageView来说可能更像轮播图一样了

**Comment by itMcdull** [comment]
希望后续添加controller支持 谢谢

**Comment by PonyCui** [comment]
将在下一版本中添加

- [ ] 开发
- [ ] 用例
- [ ] 文档

**Comment by PonyCui** [comment]
https://mpflutter.com/zh/docs/mp-page-view
已支持，要求升级到 0.10.2。
