### ISSUE TITLE
clone模板程序后，f5开始调试，提示支持的语言最高到2.17，上网搜索后，运行了flutter clean，.dart-tool文件夹被删除，再次运行调试，报错

### ISSUE THREAD

**Issue by jsyanyang** [mpflutter/mpflutter#402]
![image](https://user-images.githubusercontent.com/94437201/223898594-ecfbe7e5-5291-4e50-a0a0-ce31292acf76.png)

**Comment by jsyanyang** [comment]
![image](https://user-images.githubusercontent.com/94437201/223899235-93a26fd7-d33f-40a7-8b31-c446dc906234.png)

**Comment by jsyanyang** [comment]
版本如下![image](https://user-images.githubusercontent.com/94437201/223899921-35650cd4-ae1f-423e-a7e8-c16ab958032b.png)

**Comment by PonyCui** [comment]
请检查 vscode 环境中的 flutter 与命令行中的 flutter 是否完全对应

**Comment by jsyanyang** [comment]
![image](https://user-images.githubusercontent.com/94437201/223909464-7f7b41a1-1b75-4ae6-b362-68c21d1aedf4.png)
![image](https://user-images.githubusercontent.com/94437201/223909529-3b0f8424-afd7-49f2-acad-d36db68a7076.png)
是vscode dart的版本的问题吗

**Comment by jsyanyang** [comment]
通过命令行单独跑dart scripts/build_plugins.dart和dart lib/main.dart发现可以跑起来
![image](https://user-images.githubusercontent.com/94437201/223911690-2f553de8-d274-4e53-a167-6077674987af.png)

**Comment by jsyanyang** [comment]
![image](https://user-images.githubusercontent.com/94437201/223911725-fbae7c41-8d85-4d31-8bd0-6f8d45ae3278.png)

**Comment by jsyanyang** [comment]
通过命令行无法启动的话没办法启动热重载吗大佬

**Comment by PonyCui** [comment]
那说明你的 vscode dart sdk location 是有问题的

**Comment by PonyCui** [comment]
你指的是 hot reload 还是 hot restart，命令行方式不需要任何改动就可以支持 hot reload。
