### ISSUE TITLE
请问 shared_perferances 调试时如何清空本地缓存

### ISSUE THREAD

**Issue by bigshezhang** [mpflutter/mpflutter#403]
在使用 sp 开发时需要调试，发现 sp 状态在重启调试时不会清除，请问如何清除它们

**Comment by PonyCui** [comment]
小程序还是 Web 呢？

**Comment by bigshezhang** [comment]
> 

是 web

**Comment by PonyCui** [comment]
你在 Chrome 或 Safari 当前网页控制台里，输入以下命令就可以。
```
localStorage.clear()
```

**Comment by bigshezhang** [comment]
> 你在 Chrome 或 Safari 当前网页控制台里，输入以下命令就可以。
> 
> ```
> localStorage.clear()
> ```

好的谢谢你
