### ISSUE TITLE
请问flutter-native如何使用，按照文档没跑起来

### ISSUE THREAD

**Issue by jsyanyang** [mpflutter/mpflutter#404]
![image](https://user-images.githubusercontent.com/94437201/224017638-54593f41-4d28-4236-8c49-f3652fabbad1.png)
mpflutter是通过外部命令行的模式跑起来的，不是vscode的调试模式，不知道有没有影响
步骤：
1.在asome_project里面生成flutter_native目录
2.cd到flutter_native下
3.运行flutter pub get
4.运行flutter run
好像是socket链接问题，报错一直刷
![image](https://user-images.githubusercontent.com/94437201/224018367-174bc618-8001-48a6-b7d2-94ff57847df5.png)

**Comment by PonyCui** [comment]
安卓吗？安卓模拟器把 lib/main.dart 中的 127.0.0.1 改成 10.0.2.2

**Comment by jsyanyang** [comment]
只在lib/mp_config.dart找到127.0.0.1

**Comment by jsyanyang** [comment]
![image](https://user-images.githubusercontent.com/94437201/224461724-4771f109-ab11-4040-93c5-1db7e9880036.png)
改了hais还是不行，错误一直刷

**Comment by jsyanyang** [comment]
好像是scoket链接不上，而且他的端口号会一直变

**Comment by PonyCui** [comment]
端口号都是 9898 不会变的
