### ISSUE TITLE
界面渲染出来前屏幕是黑的

### ISSUE THREAD

**Issue by morebuff** [mpflutter/mpflutter#410]
界面渲染出来之前，屏幕发黑的，有什么好的解决方法吗？

**Comment by PonyCui** [comment]
请提供更多上下文

**Comment by morebuff** [comment]
GestureDetector(
                        onTap: () {
                          Navigator.of(context).pushNamed('/member');
                        },
                        child: SizedBox(
                          child: Column(
                            children: <Widget>[
                              MPIcon(
                                MaterialIcons.people_alt_round,
                                color: Colors.black54,
                                size: 35,
                              ),
                              Text(
                                '个人中心',
                                style: TextStyle(color: Colors.black54, fontSize: 14),
                              ),
                            ],
                          ),
                        ),
                      ),上面为上一个页面的按钮，点击后跳转到member路由界面,下一页的代码如下


import 'package:flutter/widgets.dart';
import 'package:get/get.dart';
import 'package:mpcore/mpcore.dart';
import 'package:space/member/member_controller.dart';

class MemberView extends GetView<MemberController>{
  @override
  Widget build(BuildContext context) {
    double _height = MediaQuery.of(context).size.height;
    return MPScaffold(
      backgroundColor: Colors.teal,
      name: '个人中心',
      appBarColor: Colors.teal,
      body: Container(
        child:Column(
          children: <Widget>[
            Container(
              height: 120,
              color: Colors.teal,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Container(
                    margin: EdgeInsets.only(left: 10),
                    child: Row(
                      children: <Widget>[
                        ClipRRect(
                          borderRadius: BorderRadius.circular(30),
                          child: Image.network(
                            "https://xxxxx.com/jpg",
                            width: 60,
                            height: 60,
                            fit: BoxFit.fill,
                          ),
                        ),
                        Container(
                          margin: EdgeInsets.only(left: 10),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: <Widget>[
                              Text('昵称',style: TextStyle(fontSize: 16,color: Colors.white),),
                              Text('15888888888',style: TextStyle(color: Colors.white)),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                  Container(
                    margin: EdgeInsets.only(right: 20),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: <Widget>[
                        Text('余额: 0.00',style: TextStyle(fontSize: 16,color: Colors.white),),
                        GestureDetector(
                          onTap: (){
                            Navigator.pushNamed(context, '/recharge');
                          },
                          child: Container(
                            margin: EdgeInsets.only(top: 5),
                            padding: EdgeInsets.only(left: 10,right: 10,top: 5,bottom: 5),
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(10),
                            ),
                            child: Text('充值',style: TextStyle(fontSize: 14,color: Colors.teal),),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            Container(
              height: _height - 120,
              margin: EdgeInsets.only(top: 10),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20),
                  topRight: Radius.circular(20),
                ),
              ),
              child: Column(
                ///ListTile
                children: <Widget>[
                  _buildListTile(title: "我的钱包", iconUel: MaterialIcons.shop_2_round, onTap: (){
                    Navigator.pushNamed(context, '/wallet');
                  }),
                  _buildListTile(title: "我的订单", iconUel: MaterialIcons.shop_2_round, onTap: (){
                    Navigator.pushNamed(context, '/order');
                  }),
                  _buildListTile(title: "我的优惠券", iconUel: MaterialIcons.shop_2_round, onTap: (){
                    Navigator.pushNamed(context, '/coupon');
                  }),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildListTile({required String title, required String iconUel, required void Function() onTap}) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        height: 50,
        margin: EdgeInsets.only(top: 10),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            Container(
              margin: EdgeInsets.only(left: 20),
              child: Row(
                children: <Widget>[
                  MPIcon(
                    iconUel,
                    color: Colors.black87,
                    size: 22,
                  ),
                  Container(
                    margin: EdgeInsets.only(left: 10),
                    child: Text(title,style: TextStyle(fontSize: 16,color: Colors.black87),),
                  ),
                ],
              ),
            ),
            Container(
              margin: EdgeInsets.only(right: 10),
              child: MPIcon(
                MaterialIcons.arrow_forward_ios,
                color: Colors.black87,
                size: 20,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

Controller代码如下
import 'package:get/get.dart';

class MemberController extends GetxController {

  bool isLogin = false;

  @override
  void onInit() {
    super.onInit();
    
  }
}
