### ISSUE TITLE
native的build文件夹flutter run后黑屏

### ISSUE THREAD

**Issue by jsyanyang** [mpflutter/mpflutter#413]
![image](https://user-images.githubusercontent.com/94437201/226093373-14980368-7c17-459d-aa40-b684d6603a36.png)
通过flutter_native 进行flutter run可以正常显示，然后通过scripts/build_flutter_native.dart生成了build文件夹，运行flutter pub get后，运行flutter run黑屏

**Comment by PonyCui** [comment]
请提供 mpflutter 以及 mp_flutter_runtime 的版本号信息
