### ISSUE TITLE
运行pub get命令时提示被占用，

### ISSUE THREAD

**Issue by qq531309724** [mpflutter/mpflutter#414]
E:\mpflutter_template>mpflutter pub get

E:\mpflutter_template>set PUB_HOSTED_URL=https://pub.mpflutter.com

E:\mpflutter_template>flutter pub get
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Warning: You are using these overridden dependencies:
! flutter 1.1.0 (1.2.1 available)
! flutter_web_plugins 1.1.0 (1.2.1 available)
! mpcore 1.1.0 (1.2.1 available)
Pub failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Running "flutter pub get" in mpflutter_template...
pub get failed (1; in the directory open in another application.)

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter/issues/74

**Comment by qq531309724** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
