### ISSUE TITLE
图片分享ShowShareImageMenuOption， 本地图片地址应该怎么取？

### ISSUE THREAD

**Issue by tripleLBeTaken** [mpflutter/mpflutter#416]
环境：
Flutter 3.7.6
{
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter: "1.2.0"
  flutter_web_plugins: "1.2.0"
  mpcore: "1.2.0"
  mp_build_tools: "1.2.0"
  universal_miniprogram_api: ^0.1.0
  dio: ^4.0.1
  shared_preferences: ^2.0.8
flutter:
  assets:
    - assets/share.png

dependency_overrides:
  flutter: "1.2.0"
  mpcore: "1.2.0"
  flutter_web_plugins: "1.2.0"
}
我在发起图片分享时遇到了一些问题, 尝试了几次都没找到正确的地址，
```
ShowShareImageMenuOption()
..setValues(
    path: 'asstes/share.png', // 这里的图片在widget里是没问题的。放到根目录下以../../../的方式取也不行。
    success: (result) {
                                
     },
    fail: (error) async{
           print(await error.errMsg); // 报了路径错误
     }
)
```

于是用了UniversalMiniProgramApi.uni.downloadFile(DownloadFileOption()这个api，想下载网络图片保存到临时地址，
但是这个接口也报了错，在success回调里，await downloadFileSuccessCallbackResult.filePath 取地址时报错，似乎是universal_miniprogram_api库里的类型转换错误。

**Comment by PonyCui** [comment]
提供一个完整的 demo zip 包上传到这里吧
