### ISSUE TITLE
调用广告api，监听方法报错：type 'JsObject' is not a subtype of type 'GeneralCallbackResult' of 'p0'

### ISSUE THREAD

**Issue by tripleLBeTaken** [mpflutter/mpflutter#417]
环境：
universal_miniprogram_api: ^0.1.6，
mpcore: "1.2.1"
我在调用广告api时遇到了问题
```
InterstitialAd ad = await UniversalMiniProgramApi.uni
          .createInterstitialAd(CreateInterstitialAdOption()
            ..setValues(adUnitId: 'xxx));
      ad.onClose((p0) {
        print(p0);
      });
      await ad.load().then((value) {
        ad.show();
      });
```
视屏激励广告的onClose, onLoad等监听事件也是类似的错误，是不是我的用法有误？

错误信息为：
type 'JsObject' is not a subtype of type 'GeneralCallbackResult' of 'p0'
Unccaught exception: type 'JsObject' is not a subtype of type 'GeneralCallbackResult' of 'p0', #0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:105:68)
#1      Function._apply (dart:core-patch/function_patch.dart:11:73)
#2      Function.apply (dart:core-patch/function_patch.dart:34:12)
#3      JsBridgeInvoker.makeResponse
mpjs.dart:60
#4      MPChannelBase.handleClientMessage
channel_base.dart:148
#5      _rootRunUnary (dart:async/zone.dart:1406:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
#14     _rootRunUnary (dart:async/zone.dart:1406:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#21     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
#22     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
#23     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#24     _rootRunUnary (dart:async/zone.dart:1406:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#30     _StreamController._add (dart:async/stream_controller.dart:648:7)
#31     _StreamController.add (dart:async/stream_controller.dart:596:5)
#32     _Socket._onData (dart:io-patch/socket_patch.dart:2355:41)
#33     _rootRunUnary (dart:async/zone.dart:1414:13)
#34     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#39     _StreamController._add (dart:async/stream_controller.dart:648:7)
#40     _StreamController.add (dart:async/stream_controller.dart:596:5)
#41     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1877:33)
#42     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1334:14)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by PonyCui** [comment]
用这个试试 https://github.com/mpflutter-plugins/universal_miniprogram_api/blob/master/lib/wechat_mini_program/interstitial_ad.dart

**Comment by tripleLBeTaken** [comment]
可以了，感谢

**Comment by tripleLBeTaken** [comment]
UniversalMiniProgramApi.uni.authPrivateMessage(AuthPrivateMessageOption()..setValues(
     success:(result)async{
     String iv = await result.iv;
     String encryptedData = await result.encryptedData;
     // 以上两句报错
    // result下的errMsg和valid又是可以正常取到的。
     }
))
我的package版本都是最新的，可是屡屡遇到此类错误。
想知道是什么原因导致的呢，这种有什么通用的解决方案吗？是我哪里编写不当导致的吗？

**Comment by PonyCui** [comment]
> 

https://developers.weixin.qq.com/miniprogram/dev/api/share/wx.authPrivateMessage.html

是不是忘了传 shareTicket 导致的？

**Comment by tripleLBeTaken** [comment]
不是，shareTicket是拿到并且传递了的，否则会走fail回调。

最重要的问题是release包会出现的白屏、加载失败的情况。这个也太致命了...我没法稳定复现这个问题，得到的经验就是，如果通过点击分享进入小程序的方式，出现的概率会大一点。

**Comment by tripleLBeTaken** [comment]
应该还是路由的问题

**Comment by tripleLBeTaken** [comment]
channel_base.dart文件里的onRouterTrigger函数，白屏问题会追溯到这里，看起来像是路由配置没有及时载入

**Comment by bigshezhang** [comment]
> 另外release包经常性出现白屏，调试台报错bad states,，从分享入口等其他非日常入口进入时出现的频率很大。 这个问题就真的很致命了...
> 
> 白屏时控制台报错： MiniProgramError Bad state: No element at a (app-service.js:3888:13016) at cn (app-service.js:3888:194894) at (app-service.js:3888:447316) at (app-service.js:3888:43964) at $2 (app-service.js:3888:225069) at r (app-service.js:3888:43640) at (app-service.js:3888:143177) at (app-service.js:3888:43964) at $2 (app-service.js:3888:225069) at r (app-service.js:3888:43640) at Mz (app-service.js:3888:136315) at $1 (app-service.js:3888:482047) at OV (app-service.js:3888:85234) at (app-service.js:3894:118532) at (app-service.js:3894:146582) at k (WASubContext.js:1:70041) at (app-service.js:3894:146520) at (app-service.js:3894:2013) at (app-service.js:3894:1044) at k (WASubContext.js:1:70041) at __awaiter (app-service.js:3894:804) at (app-service.js:3894:135083) at (app-service.js:3894:2013) at s (app-service.js:3894:846) at Q (WASubContext.js:1:68759) at (WASubContext.js:1:68981) at I (WASubContext.js:1:38458) at (WASubContext.js:1:52254) at x (WASubContext.js:1:52023) at (WASubContext.js:1:52061) at at (WASubContext.js:1:124456) at (WASubContext.js:1:154437) at p (WAServiceMainContext.js:1:158714) at (WAServiceMainContext.js:1:146943) _onNativeTimer@ global code@

我这边解决了，问题会发生在冷启动小程序后，通过分享链接再热启动时。
猜测问题：AppHide 的时候会调用 thePage 里的 onUnload，将 element 卸载导致热启动时找不到 element。
解决方法：将 mpdom.min.js 中 
`onUnload: function () { this.mpPage.viewId && n.router.disposeRoute(this.mpPage.viewId); }, `
的 onUnload 注释即可解决分享白屏问题。
