### ISSUE TITLE
tab切换页面，页面重复加载

### ISSUE THREAD

**Issue by JimmyLee05** [mpflutter/mpflutter#42]
例如首页切换到装修设计页面，再切换回首页，整个首页页面会重新加载。

**Comment by PonyCui** [comment]
可以考虑优化

**Comment by oom2android** [comment]
我现在是通过Visibility来缓存页面状态  ，暂时不知道会出现什么新问题

**Comment by PonyCui** [comment]
在 0.14.0 版本中，MainTabView 已添加 keepAlive 能力，设置 keepAlive 为 true 即可保存 Tab 页面状态。
