### ISSUE TITLE
navigator push的时候，argument的键值对里，值必须是int

### ISSUE THREAD

**Issue by ppphp** [mpflutter/mpflutter#420]
https://github.com/ppphp/mpflutter_template ，给示例加了一行argument

**Comment by ppphp** [comment]
示例push上了，昨天竟然没传

**Comment by PonyCui** [comment]
你提个 PR 到 mpflutter_template 仓库吧，感谢。

**Comment by ppphp** [comment]
> 你提个 PR 到 mpflutter_template 仓库吧，感谢。

哦哦，是有bug，那我周末研究一下这个问题
