### ISSUE TITLE
热重载无效

### ISSUE THREAD

**Issue by zhao004** [mpflutter/mpflutter#424]
版本：
![搜狗截图20230414200832](https://user-images.githubusercontent.com/82579833/232039543-ba32a886-8d38-4037-be96-7d91ca331f68.png)

效果：
https://user-images.githubusercontent.com/82579833/232040592-ece74baa-309b-42d3-b2df-f49b75143d50.mp4

说明：
mpflutter ctrl+s 保存后，不会热重载，需要重新运行项目才行
flutter版本：3.7.0
dart版本：2.19.0
mpflutter版本：1.2.1

**Comment by zhao004** [comment]
找到解决方法了：用调试运行启动就好了。
![搜狗截图20230415101913](https://user-images.githubusercontent.com/82579833/232178494-6453a497-3e03-41ed-9873-5afb32a581da.png)

**Comment by palorotolo** [comment]
应该文档备注下。
