### ISSUE TITLE
求教实现瀑布流中图片占位符的功能

### ISSUE THREAD

**Issue by bigshezhang** [mpflutter/mpflutter#427]
作者大大打扰了，我想实现瀑布流中图片占位符的功能，让图片渲染的时候不乱窜。目前使用了两个方法：
1. FadedImage，但是发现获取图片是否加载完成的回调不会出发，会直接边获取网络数据边刷新视图（效果是加载中的图片从顶部刷新到底部）
2. Dio 获取图片 Uint8 bytes 然后使用 Image.memory，处理速度慢，容易卡顿。

请问作者大大有比较好的针对 1 的解决方法吗？

**Comment by PonyCui** [comment]
能否提供一个 demo 方便重现问题？

**Comment by bigshezhang** [comment]
> 能否提供一个 demo 方便重现问题？
如下，两个 Builder 均无法进入
`Image.network(
                                      "https://www.arunningstar.com/head.png",
                                    frameBuilder: (BuildContext context, Widget child, frame, wasSynchronouslyLoaded) {
                                        print("frameBuilder");
                                        return child;
                              
                                    },
                                      loadingBuilder: (BuildContext context, Widget child, loadingProgress) {
                                        print("isLoading");
                                        if (loadingProgress == null) {
                                          // 如果下载过程中没有触发 ImageChunkEvent，则说明图片已经下载完成。
                                          return child;
                                        }
                                        // 下载过程中显示一个带有动画的 CircularProgressIndicator。
                                        return Center(
                                          child: MPCircularProgressIndicator(
                                          ),
                                        );
                                      },
                                  ),`
