### ISSUE TITLE
打包构建小程序长时间等待无报错信息

### ISSUE THREAD

**Issue by itMcdull** [mpflutter/mpflutter#43]
`[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] Connected device (2 available)
`
Dart
`Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "windows_x64"`
使用命令 dart scripts/build_weapp.dart
![image](https://user-images.githubusercontent.com/40596015/145930553-ec076af9-60d8-4793-b0b4-240dc142fb72.png)
尝试Ctrl+c 回车 都没反应

**Comment by PonyCui** [comment]
已知问题，准备修复。

**Comment by PonyCui** [comment]
已修复
https://github.com/mpflutter/mpflutter/commit/783d6dbf4a9232922b181cd9e160cc03027f9b9a
请使用 0.10.3 版本，或重新 clone mpflutter_template 尝试。

**Comment by philos3** [comment]
是否构建增加-v参数，支持打印log

**Comment by PonyCui** [comment]
目前尚未支持，后续会考虑添加更多参数支持。
