### ISSUE TITLE
微信小程序如何实现无顶部Bar的效果？

### ISSUE THREAD

**Issue by sunjianan9900** [mpflutter/mpflutter#437]
期望效果如图：
![IMG_1389](https://user-images.githubusercontent.com/10936316/235837391-540f2a8a-4d2c-4e7b-9e73-0ac0e51905a1.PNG)

但是目前不使用MPScaffold的话，页面直接白屏什么也不显示，
使用MPScaffold的情况下，默认就会有一个标题栏，无法把body透传到顶部
求指教

**Comment by sunjianan9900** [comment]
问题解决：在app.json里面的window增加navigationStyle:custom ,顶部导航栏就会消失,只保留右上角胶囊状的按钮
应该从小程序端思考，而不是在flutter端

**Comment by kuma0605** [comment]
小程序是可以实现的，有对应配置
`
export default definePageConfig({
    navigationBarTitleText: '车辆绑定',
    navigationStyle:"custom",
    "usingComponents": {
      "custom-status-bar": "../../components/nav/index"
    }
  })
`
`
// components/nav/nav.js
Component({

  /**
   * 页面的初始数据
   */
  data: {

  },
  properties:{
    showBack:{
      type:Boolean,
      value:false
    },
    bgColor:{
      type:String,
      value:'transparent'
    }
  },
  attached() {
    try {
      const res = wx.getSystemInfoSync()
      let statusBarHeight=res.statusBarHeight 
      const menubtn = wx.getMenuButtonBoundingClientRect();
      
      let diff = menubtn.top - statusBarHeight;
      
      let navHeight = menubtn.height;
      
      let topHeight = statusBarHeight+diff+navHeight
      this.setData({
        statusBarHeight:statusBarHeight+"px",
        navHeight:navHeight+"px",
        topHeight:topHeight+"px",
        diff:diff+"px"
      })
    } catch (e) {
      // Do something when catch error
      console.log(e.message)
    }
  },
})
`
