### ISSUE TITLE
not able to run after upgrade flutter to 3.10

### ISSUE THREAD

**Issue by ArchangelXu** [mpflutter/mpflutter#439]
console shows:
../../../../Library/flutter/.pub-cache/hosted/pub.mpflutter.com/flutter-1.2.1/lib/src/foundation/assertions.dart:626:22: Error: 'NullThrownError' isn't a type.
    if (exception is NullThrownError) {
                     ^^^^^^^^^^^^^^^

**Comment by ArchangelXu** [comment]
Made a quick fix. see https://github.com/mpflutter/mpflutter/pull/440

**Comment by stoneLee81** [comment]
@ArchangelXu 请问你使用的flutter 3.1对应的dart版本是多少，我在使用flutter 3.1.5, dart 3.0.3时在编译dart scripts/build_weapp.dart，会遇到喝多的错误

**Comment by ArchangelXu** [comment]
> @ArchangelXu 请问你使用的flutter 3.1对应的dart版本是多少，我在使用flutter 3.1.5, dart 3.0.3时在编译dart scripts/build_weapp.dart，会遇到喝多的错误

我用的是
Dart SDK version: 3.0.1 (stable) (Tue May 16 11:57:19 2023 +0000) on "macos_x64"

**Comment by stoneLee81** [comment]
问题比较奇怪，我clone了mpflutter的master项目到了本地，安装了node后，完成了build.sh，然后执行build_weapp.dart一直都会报错，我刚才关闭了vscode,重新打开项目，在编译build_webapp.dart,通过了。

**Comment by PonyCui** [comment]
已支持 https://mpflutter.com/zh/docs/dart3-support
