### ISSUE TITLE
微信小程序的webscoket  如何设置请求头   跪求大神提示

### ISSUE THREAD

**Issue by caicoder** [mpflutter/mpflutter#445]
await  UniversalMiniProgramApi.uni.connectSocket(ConnectSocketOption()..setValues(
        url: '${DrawUtil.webSocketUrl}${SpUtil.spUserEntity?.userId}',
      header: IAnyObject()
    ));

IAnyObject  如何设定值   

  UniversalMiniProgramApi.uni.onSocketMessage((p0) async {
      ToastUtils.show('unver  拿到数据了');
      // print(p0.data);
      var jsonStr = await  p0.data;
      print(jsonStr);
      _checkData(jsonStr);

    });

这个返回值 拿不到 是什么类型  打印不出来  data 的值

**Comment by 2018x5zzt** [comment]
同问
