### ISSUE TITLE
instantiateImageCodec 需要实现

### ISSUE THREAD

**Issue by HarrisonQi** [mpflutter/mpflutter#446]
`flutter-1.2.0/lib/ui/src/ui/painting.dart` 这个文件的`instantiateImageCodec()`直接抛出了异常，未实现。
<img width="366" alt="image" src="https://github.com/mpflutter/mpflutter/assets/33210899/4ca7dcbd-4ced-4c3d-b198-5330904ccd6c">

**Comment by HarrisonQi** [comment]
这里的功能是需要从`CustomPaint`中读取图片，在本地图片上面做标记使用（类似地图标记）。ui方面的功能还是比较常用的

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter/blob/master/packages/mpflutter_sample/lib/customs/custom_paint_page.dart
使用 MPDrawable 可以实现图片加载和绘制
