### ISSUE TITLE
MPMainTabView的tabs不显示

### ISSUE THREAD

**Issue by QingGuoQingChengYanXiaoMeng** [mpflutter/mpflutter#450]
我将MPMainTabView放在我的app的某个页面的Column中，作为页面中的一个小部件使用的时候，tabs不显示。我不知道是否可以这样使用，还是说必须得让MPMainTabView作为app的根视图

**Comment by helloworldjie** [comment]
放在Column中ListView估计也不显示， 你可以试试加个Expand

**Comment by sssolinjie** [comment]
我也不显示
