### ISSUE TITLE
告知一下作者近况

### ISSUE THREAD

**Issue by PonyCui** [mpflutter/mpflutter#451]
最近作者被拉到 B 公司的小黑屋里面干活了，基本上是 996 的节奏，因此 mpflutter 项目的 issue 回复几乎在停滞状态。
如果你遇到什么特别难解的问题，建议你先行通过阅读源码和文档解决，特别难以解决的问题建议你通过技术支援通道寻找作者解决。
这个状态大约会持续到 Q2 结束

**Comment by PonyCui** [comment]
最近已经开始回归 GitHub 了，存量的 issue 解决会提上日程。

**Comment by Silentdoer** [comment]
大佬，最近是在忙啥吗？感觉好久没有更新了
