### ISSUE TITLE
BLE 蓝牙的如何支持

### ISSUE THREAD

**Issue by joyhope** [mpflutter/mpflutter#455]
想用MPFLUTTER 作为平台, 但是BLE 的蓝牙部分, 只有纯JS的 微信接口, 这样 MPFLUTTER如何和这个BLE 的接口共存,或者完成调用关系.

**Comment by PonyCui** [comment]
你可以参考这篇文档扩展
https://mpflutter.com/zh/docs/weapp-plugin-intro

**Comment by joyhope** [comment]
目前有这样的插件的例子吗？ 或者可以参考的项目。

**Comment by joyhope** [comment]
看的不仔细，原来 https://github.com/mpflutter-plugins/universal_miniprogram_api  就是非常好的入口。感谢。

**Comment by PonyCui** [comment]
是的，你的理解是正确的。

**Comment by joyhope** [comment]
这个特性真好,  应该在介绍里面体现了.  整个WX 官方的 云函数, 和 API 都是已经完全支持了.

**Comment by caicoder** [comment]
不懂小程序端  好不好操作   里面有个IAnyObject   是怎么给它赋值的  大佬  能不能发点  使用案例  比如阿里云的图片上传
