### ISSUE TITLE
体验MP的说明

### ISSUE THREAD

**Issue by joyhope** [mpflutter/mpflutter#456]
https://mpflutter.com/zh/docs/first-app-vs,  根据这个文档执行, 无法正确运行.   

1. 报告MCORE的版本不对 (因为模板项目老了)
2. 我升级到1.2.1 依赖检查对了, 运行错误. 

希望更新一下教程, 或有可运行的项目可以体验一下.

我的flutter 是 3.10.x ,  应该是最新的版本导致的 .  不知道如何调整.

**Comment by joyhope** [comment]
../../../.pub-cache/hosted/pub.mpflutter.com/flutter-1.2.1/lib/src/foundation/assertions.dart:626:22: Error: 'NullThrownError' isn't a type.
    if (exception is NullThrownError) {
                     ^^^^^^^^^^^^^^^

看了最新的代码, 应是修改了.

**Comment by joyhope** [comment]
改用 path, 直接依赖, 或者git 依赖最新的仓库代码, 编译就可以了.

**Comment by ilmari-code** [comment]
@joyhope 修改哪个地方呢

**Comment by PonyCui** [comment]
已支持 dart3 https://mpflutter.com/zh/docs/dart3-support
