### ISSUE TITLE
目前mpflutter支持的第三方控件还比较少，有没有文档介绍怎么集成第三方控件的？

### ISSUE THREAD

**Issue by stoneLee81** [mpflutter/mpflutter#457]
将现有项目模块集成比较困难，主要在，常用的第三方控件和flutter自带的有些控件，mpflutter不支持。比如，常用的extend_img, screen_util, easy_loading等等，目前mpflutter都不支持，有没文档介绍，怎么集成的，这样后续方便扩充集成第三方的控件

**Comment by zafar427** [comment]
我也想了解一下如何扩展其他库
