### ISSUE TITLE
TextPainter不能使用

### ISSUE THREAD

**Issue by chuanchuan78** [mpflutter/mpflutter#458]
使用这个组件时，报错，是当前flutter版本不支持吗？应该如何解决？

![image](https://github.com/mpflutter/mpflutter/assets/97516141/af477793-3c29-480a-9aa8-3adfbe7bac72)

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter/blob/master/packages/mpflutter_sample/lib/customs/custom_paint_async_page.dart
TextPainter 的用法可以参照这里
