### ISSUE TITLE
MPWebDialogs.showToast失效

### ISSUE THREAD

**Issue by git-maven** [mpflutter/mpflutter#459]
直接运行git的mpflutter_sample
MPWebDialogs.showToast无法弹出toast

**Comment by git-maven** [comment]
![image](https://github.com/mpflutter/mpflutter/assets/45022397/afea7aa6-ed45-4526-a755-dce24cd1a97a)
控制台是报了这个错

**Comment by PonyCui** [comment]
是在小程序中还是 chrome 中呢？

**Comment by git-maven** [comment]
> chrome

后面发现直接跑chrome, 会报这个错, 打包成小程序正常

**Comment by bingweibi** [comment]
哥们，你们咋跑的 flutter 3.7.12 dart 2.19.6 直接按到demo 报错
![1689237804061](https://github.com/mpflutter/mpflutter/assets/20436611/a96930e3-859c-4517-8b5f-a3e471e27aeb)

**Comment by bingweibi** [comment]
可以了,使用管理员打开as pub get 成功
