### ISSUE TITLE
Because mpcore 1.2.0 depends on json_patch >=1.0.1 <3.0.0 which doesn't support null safety

### ISSUE THREAD

**Issue by LambGe** [mpflutter/mpflutter#464]
我的Dart 版本是3.0.2.

Because mpcore 1.2.0 depends on json_patch >=1.0.1 <3.0.0 which doesn't
  support null safety, mpcore 1.2.0 is forbidden.
So, because mpflutter_template depends on mpcore 1.2.0, version solving
  failed.
现在还有不支持空安全的库呢，尽快升级支持一下吧

**Comment by PonyCui** [comment]
> 作者可以更新一下新的flutter吗？因为新的dart确实加了很多实用的特性

本周会添加 dart 3.0 的支持代码

**Comment by zafar427** [comment]
期待作者的更新

**Comment by Silentdoer** [comment]
大佬，这个礼拜有空升级一下3.1嘛？

**Comment by PonyCui** [comment]
已支持 dart3 https://mpflutter.com/zh/docs/dart3-support
