### ISSUE TITLE
怎么获取从外界跳转到小程序所携带的参数呢

### ISSUE THREAD

**Issue by maxwellcatoo** [mpflutter/mpflutter#466]
小程序原生api是这样的用法：
onLoad: function (options) {
    // options的格式，其中q为扫描二维码获取的内容
    // { "q": " https://xxx.cn?name=520102400-156551201700/2", " scancode_ time": "44444" };
    var url = decodeURIComponent(options.q);
}

UniversalMiniProgramApi库中没看到这个onLoad这个方法。。。其他地方也没找到MPflutter中的具体方法

然后在代码仓搜“参数”看到了源码里的这行注释：

![image](https://github.com/mpflutter/mpflutter/assets/50536526/958adef5-aad3-4bd8-96df-59cd8b43ab7d)

请问这里说的不支持获取options参数是不是指不支持获取从外界传过来的参数吗？

**Comment by PonyCui** [comment]
用这个吧 https://developers.weixin.qq.com/miniprogram/dev/api/base/app/life-cycle/wx.getLaunchOptionsSync.html

**Comment by maxwellcatoo** [comment]
好的，非常感谢，回复好快，我试一下

**Comment by maxwellcatoo** [comment]
getLaunchOptionsSync方法好像不行
我访问的是体验版小程序路径是：pages/index/index?xid=1c0001450454107b1891

在main.dart 初始页面做了尝试都拿不到：
```
getQuery() async {
    var options = await WX.UniversalMiniProgramApi.uni.getLaunchOptionsSync();
    var path = await options.path;
    var query = await options.query;
    var referrerInfo = await options.referrerInfo;
    print("=================toJson: ${options.toJson()}");
    print("=================path: ${path}");
    print("=================query: ${query.toJson()}");
    print("=================referrerInfo_appId: ${await referrerInfo.appId}");
    print("=================referrerInfo_extraData: ${(await referrerInfo.extraData).toJson()}");
    print("=================referrerInfo: ${referrerInfo.toJson()}");
  }
```
返回值是：
![image](https://github.com/mpflutter/mpflutter/assets/50536526/7f9b1297-0831-47c9-9649-a70fb5c8c655)

**Comment by maxwellcatoo** [comment]
无意间发现这个方法可以：
```
@override
Widget build(BuildContext context) {
  final msg = ModalRoute.of(context)!.settings.arguments
  print("build了这个界面===================  $msg  ============");
  ...
}
```
输出：
![image](https://github.com/mpflutter/mpflutter/assets/50536526/acc4fc81-d47b-41eb-91ee-561aea96d0d8)
