### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by abdulhamidalokzai** [mpflutter/mpflutter#47]
Hi can someone please tell me, 
That. 
What will be the differences between Flutter normal web app and MPFlutter web app?
Are there any performance and initial loading improvements?

**Comment by PonyCui** [comment]
The MPFlutter performance is better than flutter for web.
The MPFlutter feature is less than flutter for web.
The MPFlutter is designed to web first but not native, we only introduce to China user now, and we will introduce to other country users if we ready to release 1.0.0 version. Also, we will provide more documentation and article for that.
Thank you for your interesting.
