### ISSUE TITLE
登录用户不是该小程序的开发者

### ISSUE THREAD

**Issue by JacksonNing** [mpflutter/mpflutter#470]
作者您好,项目跑起来点击微信小程序的真机调试''提示登录用户不是该小程序的开发者''.请问知道原因吗
![1695094687580](https://github.com/mpflutter/mpflutter/assets/20626566/4d202c22-750f-425f-b936-6b77d1b59e90)

**Comment by PonyCui** [comment]
换成自己的测试 appid 就可以
