### ISSUE TITLE
请教怎么做新版的微信小程序获取手机号？

### ISSUE THREAD

**Issue by TonyLiuChina** [mpflutter/mpflutter#472]
参考信息 https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html

**Comment by TonyLiuChina** [comment]
@PonyCui

**Comment by PonyCui** [comment]
用这个组件就可以 https://github.com/mpflutter/mpflutter/blob/master/packages/mpcore/lib/wechat_miniprogram/wechat_miniprogram_button.dart
