### ISSUE TITLE
Could not load content for org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_primitives.dart (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

### ISSUE THREAD

**Issue by Silentdoer** [mpflutter/mpflutter#481]
当Stack层级较多时（包装在不同组件里），会报这个问题（导致页面一直加载不出来）；但是在flutter里又没有这个问题

**Comment by PonyCui** [comment]
提供一个 demo

**Comment by Silentdoer** [comment]
[mpflutter_show_demo01.zip](https://github.com/mpflutter/mpflutter/files/12715557/mpflutter_show_demo01.zip)
可以看下这个简化后的，打开主页蓝色方块加载第二个页面要很久，实际上我的真实项目里第二个页面还会多两个stateful自定义组件，总共再多两层Stack（但是逻辑是很简单的），这个时候就完全卡半天出不来第二个页面了；
**目前这个项目里遇到的最大的问题还是GestureDetector的onPanStart，onPanUpdate，onPanEnd点击后没有触发的问题（flutter里和flutter web里是没问题的）**；
如果up有空也可以帮忙看下里面播放声音的，没有放声音出来。。

**Comment by Silentdoer** [comment]
环境是flutter 3.13.5，dart 3.1.2

**Comment by Silentdoer** [comment]
大佬，有空麻烦看一下
