### ISSUE TITLE
透露 MPFlutter 2.0 的一些动向

### ISSUE THREAD

**Issue by PonyCui** [mpflutter/mpflutter#488]
我最近正在专注于 MPFlutter 2.0 的开发，这里透露一些动向。

MPFlutter 2.0 未来会专注于服务微信小程序、抖音小程序开发，对于 Flutter Native 小程序会独立成另外一个产品。

针对 MPFlutter 1.0 的缺点，2.0 有以下改进：

- 不再移除 material 库，开发者可以完整使用 Flutter Framework 中的所有组件开发小程序。
- 完整兼容 pub.dev 生态，不需要使用 forked 的 pub.dev，官方 pub.dev 的依赖库也可以直接使用，不需要特殊修改。
- 性能更优，新方案使用 canvaskit 渲染，对于 UI 密集更新类小程序，其性能表现甚至优于官方 wxml 编码方式。
- 提供微信小游戏支持，开发者可以使用 Flame 开发游戏。

这个版本，预计 12 月会和大家见面。

**Comment by wf1992** [comment]
可以支持getx的binding吗？现有flutter项目使用getx的架构，改成mpflutter感觉改动太大了

**Comment by wf1992** [comment]
and，如果想和微信小程序现有代码做混编（业务页面中某些用小程序现有的小程序原生code），有可行性吗？或者给个文档之类的，谢谢。

**Comment by PonyCui** [comment]
回应 @wf1992 的提问：
1. 在 MPFlutter 2.0 所有的 flutter 依赖都可以使用，例如 getx 这种库。
2. 同一个页面混编不可以，单独的页面没有问题。

**Comment by zhangruiyu** [comment]
很赞

**Comment by liangdas** [comment]
canvaskit方案在微信小游戏是可以的，我实现了，小程序可能挑战比较大，主要是包体大小很难控制在4m内

**Comment by zhangruiyu** [comment]
正好准备写小程序了 本来准备taro的  要是能完美flutter形态 那肯定上mp

**Comment by PonyCui** [comment]
> canvaskit方案在微信小游戏是可以的，我实现了，小程序可能挑战比较大，主要是包体大小很难控制在4m内

小程序是主包 2M，难度是更大的。

**Comment by liangdas** [comment]
那就很期待了

**Comment by liangdas** [comment]
大佬可以加一下微信嘛，多做一些交流

**Comment by sfcecy7i** [comment]
awesome

**Comment by stoneLee81** [comment]
期待作者的更新版本，mpflutter补充了flutter在小程序这块的短板。

**Comment by PonyCui** [comment]
> 大佬可以加一下微信嘛，多做一些交流

后续会提供 MPFlutter 2.0 的讨论组

**Comment by chinacoder111** [comment]
准备年底开发一款小程序，坐等2.0了，其他不挑选了

**Comment by wookkkkk** [comment]
> > 大佬可以加一下微信嘛，多做一些交流
> 
> 后续会提供 MPFlutter 2.0 的讨论组

期待

**Comment by Silentdoer** [comment]
问下2.0到时候会默认基于flutter几版本呢？

**Comment by PonyCui** [comment]
> 问下2.0到时候会默认基于flutter几版本呢？

3.13

**Comment by sawwas** [comment]
有考虑做harmonyOS的扩展兼容么？

**Comment by zhangruiyu** [comment]
> 有考虑做harmonyOS的扩展兼容么？

不是已经有了吗

**Comment by zhangruiyu** [comment]
> 有考虑做harmonyOS的扩展兼容么？

而且这个就是专门做小程序的 考虑harmonyOS不是这个做的事啊

**Comment by ilmari-code** [comment]
期待

**Comment by zhao004** [comment]
期待

**Comment by Silentdoer** [comment]
flutter 3.16发布了，是不是可以默认基于这个版本

**Comment by PonyCui** [comment]
> flutter 3.16发布了，是不是可以默认基于这个版本

基于 3.13 并保证大于这个版本的 Flutter 都可以使用

**Comment by wengxianxun** [comment]
意思是用flutter开发的程序即可以打包app，也可以打包小程序， 不用做任何兼容修改？

**Comment by PonyCui** [comment]
> 意思是用flutter开发的程序即可以打包app，也可以打包小程序， 不用做任何兼容修改？

大部分代码可以复用，小部分如蓝牙、文件等微信小程序特定的 API 需要适配。

**Comment by a395726103** [comment]
2.0的模版代码需要更新吗

**Comment by PonyCui** [comment]
MPFlutter 2.0 Alpha 版本已发布
https://github.com/mpflutter/mpflutter/issues/497
