### ISSUE TITLE
用MPFlutter移植联机五子棋

### ISSUE THREAD

**Issue by fengdeyingzi** [mpflutter/mpflutter#491]
我尝试将自己Flutter写的联机五子棋项目移植到MPFlutter进行编译，将之前项目里的material控件都替换掉了，下面说一下主要遇到的问题：

1.MPFlutter上没有现成的音乐播放库，pub上找的audioplayer库好像也不能用；
2.没有WebSocket库，用dart调用js实现了基础的websocket，不足之处是我不会js回调dart代码，所以dart每次都getMessage来获取websocket的消息；
3.实现棋盘格的点击，用到了GestureDetector的onTapDown回调，试了很多次都调用不了，我也不会开发这种插件，所以用了一种笨办法实现。

目前初步移植完成，界面效果不是很好。
在线地址：http://app.yzjlb.net/game/gobang/

**Comment by PonyCui** [comment]
期待你到时候移植到 MPFlutter 2.0 上哈，效果应该会很好
