### ISSUE TITLE
Can't find variable: performance

### ISSUE THREAD

**Issue by Jokergz** [mpflutter/mpflutter#492]
满怀期待的clone后，真机跑不起来，一下子就没兴趣继续玩了
微信小程序，参照文档构建后
微信开发工具正常，真机预览白屏，
真机调试查看错误：Can't find variable: performance
查社区说的是什么 performance.now 小程序没有，小游戏真机才会有

Can't find variable: performance
ReferenceError: Can't find variable: performance
@https://usr//app-service.js:3834:271061
h@https://lib/WAServiceMainContext.js:1:41822
uh@https://usr//app-service.js:3834:271288
@https://usr//app-service.js:3834:272192
h@https://lib/WAServiceMainContext.js:1:41822
dO@https://usr//app-service.js:3834:272265
@https://usr//app-service.js:3834:924938
h@https://lib/WAServiceMainContext.js:1:41822
mJ@https://usr//app-service.js:3834:925721
@https://usr//app-service.js:3834:283772
h@https://lib/WAServiceMainContext.js:1:41822
E8@https://usr//app-service.js:3834:283990
@https://usr//app-service.js:3834:1623736
h@https://lib/WAServiceMainContext.js:1:41822
@https://usr//app-service.js:3834:1623774
@https://usr//app-service.js:3834:1622795
h@https://lib/WAServiceMainContext.js:1:41822
@https://usr//app-service.js:3834:1623179
@https://usr//app-service.js:3834:1623183
h@https://lib/WAServiceMainContext.js:1:41822
@https://usr//app-service.js:3834:1623813
@https://usr//app-service.js:3842:284892
h@https://lib/WAServiceMainContext.js:1:41822
_tmp6@https://usr//app-service.js:3842:284927
@https://usr//app-service.js:3842:289097
h@https://lib/WAServiceMainContext.js:1:41822
@https://usr//app-service.js:3842:289170
@https://usr//app-service.js:3850:872
h@https://lib/WAServiceMainContext.js:1:41822
onLaunch@https://usr//app-service.js:3850:1088
@https://lib/WASubContext.js:1:463559
bt@https://lib/WASubContext.js:1:464681
@https://lib/WASubContext.js:1:464805
@https://lib/WASubContext.js:1:441838
@https://usr//app-service.js:3850:270
@https://lib/WASubContext.js:1:510550
runWith@https://lib/WASubContext.js:1:500002
q@https://lib/WASubContext.js:1:510534
global code@https://usr//app-service.js:3852:17
@[native code]
evaluateScriptFile@https://lib/WAServiceMainContext.js:1:2521685
@https://lib/WAServiceMainContext.js:1:2528707
forEach@[native code]
L@https://lib/WAServiceMainContext.js:1:2528621
@https://lib/WAServiceMainContext.js:1:2529326
@https://lib/WAServiceMainContext.js:1:44661
G@https://lib/WAServiceMainContext.js:1:308070
@https://lib/WAServiceMainContext.js:1:308292
k@https://lib/WAServiceMainContext.js:1:277769
@https://lib/WAServiceMainContext.js:1:291591
E@https://lib/WAServiceMainContext.js:1:291360
@https://lib/WAServiceMainContext.js:1:291398
p@https://lib/WAServiceMainContext.js:1:399740
@https://lib/WAServiceMainContext.js:1:387742
_onNativeTimer@
global code@

**Comment by PonyCui** [comment]
本地 Flutter 版本号提供一下？

**Comment by Jokergz** [comment]
3.16.0

**Comment by Jokergz** [comment]
flutter: "1.3.0"
mpcore: "1.3.0"

**Comment by PonyCui** [comment]
问题已经修复，使用 1.3.1 可以解决
https://github.com/mpflutter/mpflutter/commit/67e87d634ab01987237cf9e369dfe569422d9c5a
