### ISSUE TITLE
凉了，一旦开始收费，在做技术选型的时候就无心选你了。

### ISSUE THREAD

**Issue by Jokergz** [mpflutter/mpflutter#498]
这个观点很扯淡，我可以主动给你钱，但你给我要钱性质就变了。像不像外边讨乞的

**Comment by Jokergz** [comment]
我只是负责技术选型，选一些 然后提交上去，上边人决定用哪个。开始收费后，怎么跟uniapp竞争呢，完全没优势了对于公司来讲

**Comment by a395726103** [comment]
白嫖怪，uniapp也有其他收费项目的

**Comment by malinops** [comment]
uniapp 已经够 扑该 了，也没见收费，这反倒还没开始 稳定就圈钱了，真够 lese

**Comment by PonyCui** [comment]
> uniapp 已经够 扑该 了，也没见收费，这反倒还没开始 稳定就圈钱了，真够 lese

如果你是个人用户，完全是免费的，如果你是商业用户，些许的授权费不是很合理？

况且，原理已经告诉你了，你完全可以自己抄一个。
