### ISSUE TITLE
🙏 功德无量～ 建议可以在README里面贴下打赏码，或者付费解锁项目Demo

### ISSUE THREAD

**Issue by sunjianan9900** [mpflutter/mpflutter#50]
这个项目，太棒了！！

另外希望能有完整项目的Demo代码（不是一兜糖，随便什么都可以，类似flutter组件演示那种演示APP）

可以接受付费解锁完整项目Demo代码

**Comment by PonyCui** [comment]
我们有一些项目正准备上线，是可以开源的。

**Comment by PonyCui** [comment]
你的建议非常好！

**Comment by PonyCui** [comment]
Showcase 代码将整理在这里
https://github.com/mpflutter-showcase
