### ISSUE TITLE
dart scripts/build_wechat.dart 报错

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#500]
特别提示你：
1. MPFlutter Build Tools 目前不是开源项目
2. 禁止反编译、修改 MPFlutter Build Tools 程序（在获得 MPFlutter 团队同意的情况下除外）
3. 禁止在未获取授权的情况下，移除 UNLICENSED 标识
4. MPFlutter Build Tools 会上传埋点信息，用于营销分析，如果你不同意该行为，应停止使用。
===========================================
[INFO] 正在构建 wechat 小程序
[INFO] 正在构建 flutter for web 产物
[ERROR] 构建失败，失败信息： ProcessException: 系统找不到指定的文件。

  Command: flutter build web --web-renderer canvaskit
PS D:\WorkSpace\Demo\awesome_project_20231212>

**Comment by PonyCui** [comment]
问题已知，稍后修复

**Comment by PonyCui** [comment]
问题已经修复，你可以先指定 mpflutter_build_tools 为 git: https://github.com/mpflutter/mpflutter_build_tools 使用
