### ISSUE TITLE
2.0的demo，下载下来就报错包体过大

### ISSUE THREAD

**Issue by sssolinjie** [mpflutter/mpflutter#501]
message：Error: 上传失败：网络请求错误 代码包大小超过限制,main package source size 4858KB exceed max limit 2MB [20231214 10:21:47][*********]
appid: *********
openid: o6zAJs-yTz8OihMLrKHDVEbVVE3M
ideVersion: 1.06.2308310
osType: darwin-arm64
time: 2023-12-14 10:21:50

**Comment by PonyCui** [comment]
awesome_project?

**Comment by sssolinjie** [comment]
> awesome_project?

是的，我把2.2MB的字体删了重新构建还是这个问题

**Comment by sssolinjie** [comment]
> awesome_project?

而且感觉调试没1.0方便 - -

**Comment by PonyCui** [comment]
你直接微信联系我吧，文档有联系方式
