### ISSUE TITLE
创作不易，官网说300以内一个公众号，质量方面靠谱的话并不算贵，目前发现预览版存在一些问题

### ISSUE THREAD

**Issue by yangfanyu** [mpflutter/mpflutter#503]
搞了两个简单页面，登录、扫码，目前发现预览版存在以下两个硬伤：

1、键盘的问题。登录页面点进去之后，键盘还是打开状态，`FocusScope.of(context).unfocus();`之类的操作无效。

2、小程序API的调用，如果在登录页没调用过wx相关的Api，进入第二个页面之后，调用wx....会报错。

其它的不重要的：

1、`mpflutter_build_tools` 在构建的时候，看了下替换脚本，一些字体是从`https://fonts.gstatic.com`加载的，如果能添加选项替换为自己的域名更好。

2、`MPNavigatorObserver`存在BUG，在  登录页发起异步请求前`Navigator.push`一个加载，异步请求返回后关闭loading ，直接卡死。如果不使用`MPNavigatorObserver`则无问题。

创作不易，感谢您的作品，希望越来越好。

**Comment by PonyCui** [comment]
感谢你的反馈，如果可以的话，微信私聊一下，看看 Demo 遇到的问题怎么解决。
