### ISSUE TITLE
建议2.0新开一个git项目 不要在老项目里面维护

### ISSUE THREAD

**Issue by fangkyi03** [mpflutter/mpflutter#504]
1.找一些问题变得很难 比如一些兼容问题 issue里面一堆老版本的跟2.0混在一起的 让人都分不清谁是谁
2.对于后面新功能迭代也更有好处 毕竟2.0的视线方式跟老版本是完全不一样的

**Comment by PonyCui** [comment]
文档里已经提到，2.0 不建议在 GitHub 提问，直接联系作者。

**Comment by PonyCui** [comment]
后续确实会新建一个仓库用于 2.0 迭代
