### ISSUE TITLE
runMPApp搭配ScreenUtilInit会导致页面白屏

### ISSUE THREAD

**Issue by fangkyi03** [mpflutter/mpflutter#505]
<img width="648" alt="image" src="https://github.com/mpflutter/mpflutter/assets/30390014/011f7b0a-c287-43e0-9570-de0ecc8f19d4">
如果使用runMPApp的方式 这边返回的size永远都是size.zero导致后面样式根本不会走下去

**Comment by ilmari-code** [comment]
我也遇到这个问题了，这个库不支持web，所以需要移除掉，自己适配一下.w

**Comment by stoneLee81** [comment]
flutter_screenutil是支持web的，也可以用下get的screen获取屏幕的属性

**Comment by PonyCui** [comment]
修复了 https://mpflutter.feishu.cn/wiki/LBtYwgw3Yi0BQzk6XTIcLOVrnZc 使用最新的 Alpha 版本
