### ISSUE TITLE
MPNavigatorObserver 导致web页面崩溃

### ISSUE THREAD

**Issue by fangkyi03** [mpflutter/mpflutter#506]
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2 23C64 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.1)

     /**
       * 务必保留 MPNavigatorObserver，否则小程序的路由会出问题。
       */
      navigatorObservers: [MPNavigatorObserver()],

加了这行代码 web运行就崩溃报错
<img width="656" alt="image" src="https://github.com/mpflutter/mpflutter/assets/30390014/f9bd81f9-6ed6-43fc-894f-8adc3728e873">
而且现在并没有办法能完全区分出是web还是小程序

**Comment by PonyCui** [comment]
已修复，使用 2.0.0 即可
