### ISSUE TITLE
Playground 只显示RUN，点击控制台报错

### ISSUE THREAD

**Issue by sunjianan9900** [mpflutter/mpflutter#51]
Uncaught SyntaxError: Illegal return statement
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/monaco-editor@0.30.1/min-maps/vs/editor/editor.main.js.map 的内容:加载超时导致加载取消
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/monaco-editor@0.30.1/min-maps/vs/loader.js.map 的内容:加载超时导致加载取消
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/monaco-editor@0.30.1/min-maps/vs/editor/editor.main.nls.js.map 的内容:加载超时导致加载取消
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/monaco-editor@0.30.1/min-maps/vs/editor/editor.main.js.map 的内容:加载超时导致加载取消

![image](https://user-images.githubusercontent.com/10936316/147868571-18dbb00d-d587-46de-b877-1ba87fdc04ce.png)
![image](https://user-images.githubusercontent.com/10936316/147868583-35d8bab3-bac1-4e90-88fe-84035282668c.png)

**Comment by PonyCui** [comment]
这个问题已经修正了，感谢反馈。

**Comment by mnock** [comment]
> 这个问题已经修正了，感谢反馈。

现在出现了一样的问题  请求超时

**Comment by PonyCui** [comment]
> 

有时 jsdelivr 会出问题，导致加载失败，重试一下就好了。

**Comment by mnock** [comment]
> > 
> 
> 有时 jsdelivr 会出问题，导致加载失败，重试一下就好了。

https://cdn.jsdelivr.net/gh/mpflutter/dist/0.14.2/dist_web/mp_web_features.min.js 是请求失败了 现在运行不了 白屏哈

**Comment by mnock** [comment]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/16587910/168717182-0963d4a1-f192-412b-a4b3-5ec5ca288992.png">

**Comment by PonyCui** [comment]
看上去是电信和移动网络访问 jsdelivr 有问题，联通还可以用。

**Comment by PonyCui** [comment]
已将资源文件切换到字节跳动 cdn 以及 dist.mpflutter.com cdn，后续不会再依赖 jsdelivr。
