### ISSUE TITLE
关于分享的问题

### ISSUE THREAD

**Issue by jijkbird** [mpflutter/mpflutter#511]
设置页面分享设置，尝试过pages/index/index,和生成原生路由的方式
 
onWechatMiniProgramShareAppMessage: (request) async {
   
        return MPWechatMiniProgramShareInfo(
            title: 'xx',
            // imageUrl: 'xxxxxx', // 
            customPath: "/xxxxx",
            routeParams: {
              'mall':xxxxx,
              'user': xxxxx
            });
      }

  @override
 Widget build(BuildContext context) {
    RouteSettings? msg = ModalRoute.of(context)!.settings;
    print(msg);

分享之后进入无法获取routeParams的值，index路由得到空map,原生的路由得到null，尝试过url参数，无法找到页面
只有 {$viewportWidth: 320, $viewportHeight: 568}  这个信息
!!! 但是 !!!
如果在小程序添加编译模式，无论哪种模式，添加的参数都能获取到
{mall: R7dCL0DBQO, user: cdcde, $viewportWidth: 320, $viewportHeight: 568}
唯独分享出去的获取不到参数

这种有办法解决吗，或者有临时解决办法吗，我想快点把项目交付了，后续用2.0

**Comment by PonyCui** [comment]
你可以在启动的时候用 wx 的 api，getLaunchOptionsSync 或者 getEnterOptionsSync 看看能获取到不

**Comment by PonyCui** [comment]
另外是，在 customPath 中你需要自行拼接完整的参数 routeParams 不会被编码进去。
例如 customPath: "/abc?a=1&b=2"

**Comment by jijkbird** [comment]
小程序的编译模式添加url后缀不行，但是实际代码运行中请求url是可行的
