### ISSUE TITLE
下载awesome_project后运行初始项目失败

### ISSUE THREAD

**Issue by QuanchaoSong** [mpflutter/mpflutter#513]
下载了项目，什么都没动，命令行运行`flutter pub get`，然后报错如下：
<img width="725" alt="Screenshot 2024-01-06 at 8 49 17 AM" src="https://github.com/mpflutter/mpflutter/assets/47345588/138bd8f6-4046-4bc3-bb0b-5b349508920d">

**Comment by QuanchaoSong** [comment]
但是编译之后，在小程序段可以正常运行。所以目前不支持热更新的，对吧？

<img width="565" alt="Screenshot 2024-01-06 at 9 06 39 AM" src="https://github.com/mpflutter/mpflutter/assets/47345588/f06ac68c-f00f-47d6-a9e1-eaadf630c04a">

**Comment by PonyCui** [comment]
https://mpflutter.feishu.cn/wiki/DvyKwkpVhinKaLkfXVecnlP9nAg

**Comment by PonyCui** [comment]
请确保 Flutter 调试目标选择的是 macOS / Windows / Linux
