### ISSUE TITLE
assets目录下的图片文件无法正常加载出来

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#515]
child: Image.asset(
                "assets/images/add_blue.png",
              ),
![image](https://github.com/mpflutter/mpflutter/assets/17779490/3fb4e48a-e93a-4de7-9beb-28ae8282c88b)
![image](https://github.com/mpflutter/mpflutter/assets/17779490/d7717162-a0ac-4d21-b32b-6db680d5cd77)
![image](https://github.com/mpflutter/mpflutter/assets/17779490/b1625eee-c4fe-45c5-8c93-52db0a4c81d8)

[awesome_project.zip](https://github.com/mpflutter/mpflutter/files/13856699/awesome_project.zip)
这是demo代码
打包环境window11，flutter版本3.16.5

**Comment by PonyCui** [comment]
可以了，用 Nightly 版本试试
https://mpflutter.feishu.cn/wiki/LBtYwgw3Yi0BQzk6XTIcLOVrnZc
