### ISSUE TITLE
IncludePointsOption中points没有提供set方法

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#518]
![image](https://github.com/mpflutter/mpflutter/assets/17779490/ec21832a-2432-4156-b745-aa6edc9caa4b)

**Comment by PonyCui** [comment]
已修复，请使用 nightly 版本验证
https://mpflutter.feishu.cn/wiki/LBtYwgw3Yi0BQzk6XTIcLOVrnZc
