### ISSUE TITLE
订阅消息需要点击触发，但是flutter的点击手势小程序不识别，无法正常弹出消息订阅对话框

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#520]
requestSubscribeMessage-------------=> fail requestSubscribeMessage:fail can only be invoked by user TAP gesture.
![image](https://github.com/mpflutter/mpflutter/assets/17779490/2c0db037-1292-4c53-af51-860c1775d633)

**Comment by PonyCui** [comment]
试试 button https://mpflutter.feishu.cn/wiki/T4ITw9uUKiWCb7kD0knc7FNenme

**Comment by a395726103** [comment]
> 试试 button https://mpflutter.feishu.cn/wiki/T4ITw9uUKiWCb7kD0knc7FNenme

使用button也会报同样的错误，以前1.0版本的时候是可以通过flutter手势点击触发订阅通知的

**Comment by PonyCui** [comment]
嗯，因为 button 没有开放 onTap 回调，我会在本周六提供一个更新。

**Comment by PonyCui** [comment]
https://mpflutter.feishu.cn/wiki/R0HbwZnz1ivmSkkmLdOcEWdan3i
