### ISSUE TITLE
MPFlutter_Wechat_WebView.open报错，真机和开发工具都无法打开webView

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#521]
![image](https://github.com/mpflutter/mpflutter/assets/17779490/af577256-3670-4f8d-b28e-17de96d8d9f9)
![image](https://github.com/mpflutter/mpflutter/assets/17779490/576f3e7f-ab67-4c00-9ce4-dc86fab6a1ab)

**Comment by PonyCui** [comment]
已修复，请使用 mpflutter_build_tools 2.1.1
