### ISSUE TITLE
wx.getFileSystemManager().writeFileSync报错

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#523]
![image](https://github.com/mpflutter/mpflutter/assets/17779490/589d8961-efb5-4fce-a297-a6bef2edfe35)

![image](https://github.com/mpflutter/mpflutter/assets/17779490/5848e73f-357f-4dac-84d8-af6ffdb6a429)

![f594c9aaf3e26ab20bb8f2b44bbee17](https://github.com/mpflutter/mpflutter/assets/17779490/674376cf-c6a1-42e1-8f90-a5df1e57af30)

**Comment by PonyCui** [comment]
这个问题已修复，你使用 nightly 就可以。
