### ISSUE TITLE
picture.toImage()，renderProxyBox.toImage()等方法会导致页面花屏，缓冲区溢出

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#525]
![image](https://github.com/mpflutter/mpflutter/assets/17779490/fbfd1720-0928-4c5c-b554-a49e45b01106)
![image](https://github.com/mpflutter/mpflutter/assets/17779490/baa78e0a-baf8-478d-be0c-576e390aebce)

**Comment by PonyCui** [comment]
估计是内存爆了，有没有可以必现的代码。

**Comment by a395726103** [comment]
> 估计是内存爆了，有没有可以必现的代码。

[awesome_project.zip](https://github.com/mpflutter/mpflutter/files/13915095/awesome_project.zip)
多画点，多点几次页面就花了，win11打包的
