### ISSUE TITLE
请支持FVM

### ISSUE THREAD

**Issue by kokocooler2020** [mpflutter/mpflutter#527]
在mpflutter2.0模板工程下使用fvm管理flutter版本，将flutter版本设置为3.15.0-15.1.pre (对应Dart： **3.2.0**)，
然后执行：fvm dart ./scripts/build_wechat.dart，输出：

====== 欢迎使用 MPFlutter Build Tools ======
特别提示你：
1. MPFlutter Build Tools 目前不是开源项目
2. 禁止反编译、修改 MPFlutter Build Tools 程序（在获得 MPFlutter 团队同意的情况下除外）
3. 禁止在未获取授权的情况下，移除 UNLICENSED 标识
4. MPFlutter Build Tools 会上传埋点信息，用于营销分析，如果你不同意该行为，应停止使用。
===========================================
[INFO] 正在构建 wechat 小程序
[INFO] 正在构建 flutter for web 产物
Resolving dependencies...

The current Dart SDK version is **3.0.3.**

Because awesome_project requires SDK version >=3.1.5 <4.0.0, version solving failed.

[ERROR] 构建失败，失败信息： exit code = 1

---------------------------------------------------

我本机正常安装了flutter3.10.3 (Dart：3.0.3)，但已经使用FVM将本工程的flutter版本设置为3.15.0-15.1.pre(对应Dart： **3.2.0**)，
build_wechat.dart脚本似乎没有识别FVM创建的相对符号链接。

我注意到mpflutter_build_tools-2.1.1/lib/main.dart::init()中读取了.dart_tool/package_config.json, 
也确认了package_config.json中引用的flutter路径是fvm所设置的flutter版本所在的路径，
但不知为何并未生效，而是去调用本机正常安装的flutter路径了。

**Comment by PonyCui** [comment]
已支持 fvm https://github.com/mpflutter/mpflutter_build_tools/commit/933e119e8ef9f74c7e75623d5950985a60a3d889
将在 2.6.0 中正式提供
