### ISSUE TITLE
模板工程更新依赖时出错

### ISSUE THREAD

**Issue by decker502** [mpflutter/mpflutter#53]
首先感谢作者提供这么好的项目，谢谢！

- 遇到的问题
按文档使用命令行，通过 git clone 方式克隆模板工程至目标目录后，执行 `./mpdart pub get` ，提示如下：

···
./mpdart pub get
Resolving dependencies... (1.3s)
Because mpflutter_template depends on path_provider >=0.4.0 which requires the Flutter
  SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `dart pub get`.
···

- 遇到问题的场景 (微信小程序或 Web 或其它？)

操作系统： ubuntu 20.04
IDE: vscode

- 重现方法（最好能提供一个 Demo，打包上传至 GitHub）

模板工程更新依赖时出现

- flutter 的版本
```
flutter --version
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (2 周前) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

dart --version
Dart SDK version: 2.15.1 (stable) (Unknown timestamp) on "linux_x64"

dart2js --version
Dart-to-JavaScript compiler (dart2js) version: 2.15.1

```
- mpflutter 的版本（ mpcore 的版本）

不确定是不是这样查看

```
./mpflutter --version
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (2 周前) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

```

**Comment by PonyCui** [comment]
你可以使用 ./mpflutter packages get 试试

**Comment by decker502** [comment]
执行后

```
./mpflutter packages get
Warning: You are using these overridden dependencies:
! flutter 0.11.1
! flutter_web_plugins 0.11.1
! mpcore 0.11.1
Running "flutter pub get" in awesome_project...                    467ms
```

再次执行 ` ./mpdart pub get ` 依然报错，`F5` 运行提示

```
vm-service: Error: Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request

Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request
Exited (255)

```

**Comment by decker502** [comment]
进一步尝试，点击 `Run code` 后，
···
lib/main.dart: Warning: Interpreting this as package URI, 'package:mpflutter_template/main.dart'.
Serve on 0.0.0.0:9898
Use browser open http://0.0.0.0:9898/index.html or use MiniProgram Developer Tools import './dist/weapp' for dev.
···

但直接访问会报 `CORS policy`错误，需要改为 127.0.0.1才可打开页面，此时热重载没有生效

**Comment by decker502** [comment]
@PonyCui issue close了?

**Comment by PonyCui** [comment]
./mpflutter packages get 
应该可以解决你的问题，另外的问题可以另开 issue。

**Comment by PonyCui** [comment]
> 进一步尝试，点击 `Run code` 后，
> 
> ```
> lib/main.dart: Warning: Interpreting this as package URI, 'package:mpflutter_template/main.dart'.
> Serve on 0.0.0.0:9898
> Use browser open http://0.0.0.0:9898/index.html or use MiniProgram Developer Tools import './dist/weapp' for dev.
> ```
> 
> 但直接访问会报 `CORS policy`错误，需要改为 127.0.0.1才可打开页面，此时热重载没有生效

对于这个问题，你可以尝试关闭代理软件后再试。

**Comment by decker502** [comment]
的确是代理软件的问题，没问题了，多谢！
