### ISSUE TITLE
使用getx库，如果页面使用了Platform View会导致GetxController释放失败，报错

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#531]
[awesome_project.zip](https://github.com/mpflutter/mpflutter/files/13945141/awesome_project.zip)
demo中地图页面第一次进去会正常初始化，返回页面够再进去GetxController因为没释放，所以不会初始化了，

![image](https://github.com/mpflutter/mpflutter/assets/17779490/cea67b2a-f80a-4f8d-8e4f-7999d472f57e)
![e869295b8a2215761aba34c504016a7](https://github.com/mpflutter/mpflutter/assets/17779490/75362c05-11f3-4586-9984-b888bb668668)

**Comment by PonyCui** [comment]
提供一下代码

**Comment by a395726103** [comment]
> 提供一下代码

上面发了代码

**Comment by PonyCui** [comment]
没用过 GetX，我也不知道这题怎么解，Controller 理应随页面结束而更换，没理由一直保持旧的 Controller 不变。

**Comment by Gavin0x0** [comment]
试试使用 binding 来管理 Controller  

```dart
// routes: {
//   '/map_demo': (context) => WXMapView(),
// },
getPages: [
  GetPage(
    name: "/map_demo",
    page: () => WXMapView(),
    binding: WXMapViewBinding(),
  ),
],
```

```dart
class WXMapViewBinding implements Bindings {
  @override
  void dependencies() {
    Get.lazyPut<WXMapViewController>(() => WXMapViewController());
  }
}
```

```dart
class WXMapView extends GetView<WXMapViewController> {
  WXMapView({super.key}) {}
  .......
```

**Comment by a395726103** [comment]
> 没用过 GetX，我也不知道这题怎么解，Controller 理应随页面结束而更换，没理由一直保持旧的 Controller 不变。

页面中有Platform View才会导致不能释放，没有Platform View可以正常释放

**Comment by a395726103** [comment]
> 试试使用 binding 来管理 Controller
> 
> ```dart
> // routes: {
> //   '/map_demo': (context) => WXMapView(),
> // },
> getPages: [
>   GetPage(
>     name: "/map_demo",
>     page: () => WXMapView(),
>     binding: WXMapViewBinding(),
>   ),
> ],
> ```
> 
> ```dart
> class WXMapViewBinding implements Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut<WXMapViewController>(() => WXMapViewController());
>   }
> }
> ```
> 
> ```dart
> class WXMapView extends GetView<WXMapViewController> {
>   WXMapView({super.key}) {}
>   .......
> ```

你这个只适合跳转的新页面，不适合一个页面嵌套多个页面的情况

**Comment by a395726103** [comment]
> 没用过 GetX，我也不知道这题怎么解，Controller 理应随页面结束而更换，没理由一直保持旧的 Controller 不变。

可不可以给Platform View提供一个主动释放的方法

**Comment by PonyCui** [comment]
> > 没用过 GetX，我也不知道这题怎么解，Controller 理应随页面结束而更换，没理由一直保持旧的 Controller 不变。
> 
> 可不可以给Platform View提供一个手动释放的函数

加个 dispose 应该可以

**Comment by PonyCui** [comment]
已修复，请使用
mpflutter_core: 2.1.2
mpflutter_build_tools: 2.1.2
mpflutter_wechat_api: 2.1.0
mpflutter_wechat_mapview: 0.0.3
