### ISSUE TITLE
MPFlutter 1.x 版本进入维护阶段

### ISSUE THREAD

**Issue by PonyCui** [mpflutter/mpflutter#536]
同学们，MPFlutter 2.0 版本已正式合入 master，迭代节奏大约是一周一个版本。
MPFlutter 1.x 版本进入维护阶段，相关 Issue 将关闭，除非 P0 级别 Bug，1.x 不再提交更新。
你仍然可以继续使用 1.x 版本，该版本将始终免费。

**Comment by maxwellcatoo** [comment]
请问下1.0版本的文档要在哪里看？2.0文档里跳转到1.0文档的链接，点击后，还是进入了2.0的文档

**Comment by PonyCui** [comment]
> 请问下1.0版本的文档要在哪里看？2.0文档里跳转到1.0文档的链接，点击后，还是进入了2.0的文档

1.0 已正式废弃，请勿阅读相关文档，如果有相关需求请联系我。

**Comment by PonyCui** [comment]
1.0 文档可通过 GitHub 阅读
https://github.com/mpflutter/mpflutter.github.io/tree/master/docs
