### ISSUE TITLE
main.dart.js除了分包还有其他的优化空间吗？

### ISSUE THREAD

**Issue by yanxinchen** [mpflutter/mpflutter#538]
是否有仅针对小程序，裁剪版的main.dart.js?

**Comment by PonyCui** [comment]
没有，分包吧，或者完全不用 material，这个选择权在开发者手中。

**Comment by yanxinchen** [comment]
好的，谢谢大大。还想问一下，在flutter端wx.request请求不到“https://api.weixin.qq.com”域名的数据，但是我在小程序idea中可以，是因为我在小程序的idea中设置了：不校验域名。这个设置无法在flutter中生效吗？
![WechatIMG361](https://github.com/mpflutter/mpflutter/assets/13480869/a63cf2e2-dc3a-4d97-b2d9-a9460a249819)

**Comment by PonyCui** [comment]
> 好的，谢谢大大。还想问一下，在flutter端wx.request请求不到“[https://api.weixin.qq.com”域名的数据，但是我在小程序idea中可以，是因为我在小程序的idea中设置了：不校验域名。这个设置无法在flutter中生效吗？](https://api.weixin.qq.com%E2%80%9D%E5%9F%9F%E5%90%8D%E7%9A%84%E6%95%B0%E6%8D%AE%EF%BC%8C%E4%BD%86%E6%98%AF%E6%88%91%E5%9C%A8%E5%B0%8F%E7%A8%8B%E5%BA%8Fidea%E4%B8%AD%E5%8F%AF%E4%BB%A5%EF%BC%8C%E6%98%AF%E5%9B%A0%E4%B8%BA%E6%88%91%E5%9C%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%9A%84idea%E4%B8%AD%E8%AE%BE%E7%BD%AE%E4%BA%86%EF%BC%9A%E4%B8%8D%E6%A0%A1%E9%AA%8C%E5%9F%9F%E5%90%8D%E3%80%82%E8%BF%99%E4%B8%AA%E8%AE%BE%E7%BD%AE%E6%97%A0%E6%B3%95%E5%9C%A8flutter%E4%B8%AD%E7%94%9F%E6%95%88%E5%90%97%EF%BC%9F) ![WechatIMG361](https://private-user-images.githubusercontent.com/13480869/301714470-a63cf2e2-dc3a-4d97-b2d9-a9460a249819.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTQyMjYsIm5iZiI6MTcwNjg1MzkyNiwicGF0aCI6Ii8xMzQ4MDg2OS8zMDE3MTQ0NzAtYTYzY2YyZTItZGMzYS00ZDk3LWIyZDktYTk0NjBhMjQ5ODE5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNjA1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2RjMTY2YTEwMDU0M2Q4YmM4NzU5NTU1YjkxNmJiZTE0NDM3ZmE0YzUzYzYyZTJjYzExZThhMDc3Njc4YzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GFU2xK_1K0tOlAOBst-0TWZJMBqLtdLPpw8o6kXnCio)

不同的问题需要另建 issue，给出 demo。

**Comment by yanxinchen** [comment]
好的
