### ISSUE TITLE
在flutter中调用wx.request收不到回调

### ISSUE THREAD

**Issue by yanxinchen** [mpflutter/mpflutter#539]
不知道是不是域名问题。但是我在小程序idea中可以，而且我也设置了不校验域名。以下是代码：
flutter：
`/// 微信登录，获取openId
  /// https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/user-login/code2Session.html
  wxLogin() {
    wx.login(LoginOption()
      ..success = (result) {
        // 1.获取登录code
        var code = result.code;
        // 2.获取登录openId（uid）+ session_key
        var url =
            "https://api.weixin.qq.com/sns/jscode2session?appid=wxc9750e7fc0be6060&secret=9f184eb16c4dad995d15ca007c1bb585&js_code=" +
                code +
                "&grant_type=authorization_code";
        Toast.show('url = ${url}');
        wx.request(RequestOption()
          ..url = url
          ..success = (result) {
            var code = result.data["errmsg"];
            var openId = result.data["openid"];
            Toast.show(
                'success result.data = ${result.data} openId: ${openId} errmsg: ${code}');
          }
          ..fail = (res) {
            Toast.show('fail result.data = ${res.errMsg}');
          });
      });
  }`
小程序代码：
`// app.js
App({
  onLaunch() {
    wx.login({
      success: (res) => {
        var url_str = 'https://api.weixin.qq.com/sns/jscode2session?appid=wxc9750e7fc0be6060&secret=9f184eb16c4dad995d15ca007c1bb585&js_code=' +
        res.code +
        '&grant_type=authorization_code'
        wx.request({
          url: url_str,
          success: (res) => {
            var openId = res.data.openid;
            console.log("cyxx success: openId="+openId)
          }
        })
      },
    })
  },
  globalData: {},
});
`

**Comment by yanxinchen** [comment]
![WechatIMG362](https://github.com/mpflutter/mpflutter/assets/13480869/ac6adefb-5822-4402-9c36-4ebad2c531b0)
![WechatIMG363](https://github.com/mpflutter/mpflutter/assets/13480869/023e3796-62a6-4577-b677-f438b6b6e837)
![WechatIMG361](https://github.com/mpflutter/mpflutter/assets/13480869/c2c1ab6c-a0bc-4433-885a-61899689296f)

**Comment by PonyCui** [comment]
你用 dio 或者 http 库不可以么？

**Comment by yanxinchen** [comment]
对的，用dio可以！但是为啥wx.request就不行呢？奇怪
