### ISSUE TITLE
请问一下获取昵称的input 组件目前是否支持？

### ISSUE THREAD

**Issue by yanxinchen** [mpflutter/mpflutter#540]
由于微信更换了获取昵称的方案：https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/userProfile.html。目前getUserInfo和getUserProfile无法正常获取昵称，需要input组件支持。

**Comment by PonyCui** [comment]
MPFlutter_Wechat_EditableInput
设置 keyboardType = TextInputType.name
