### ISSUE TITLE
将原有的项目适配到MPFlutter，发现的几个问题

### ISSUE THREAD

**Issue by Hwy152** [mpflutter/mpflutter#545]
开发环境
Flutter 版本号：Flutter (Channel stable, 3.16.7, on Microsoft Windows [版本 10.0.19045.4046], locale zh-CN)
MPFlutter 版本号：  mpflutter_core: ^2.3.0  mpflutter_build_tools: ^2.3.1  mpflutter_wechat_api: ^2.2.0
操作系统：Windows 10
IDE：AndroidStudio Flamingo | 2022.2.1 Patch 2
 
问题描述：
1.dio请求（^5.4.1），接口response返回为空或空串，Android手机预览会报接口报请求超时，模拟器和IOS都正常，Android请求超时实际服务器那边已经请求成功了，但是dio得不到响应

2.Android手机的返回键会直接退出小程序，不能一级一级返回页面

3.mpflutter_video组件播放视频，全屏不能旋转，设置了duration都没用，默认一直都是竖屏，播放中也不能暂停

4.使用flutter_widget_from_html_core加载html富文本，真机预览该组件会加载不出来，模拟器可以，暂时使用flutter_html_v3替代，但不如flutter_widget_from_html_core好用

**Comment by PonyCui** [comment]
最好能提供最小可复现问题的 demo

**Comment by Hwy152** [comment]
[Uploading demo.zip…]()

**Comment by Hwy152** [comment]
第三个问题是我这边代码的问题，其余的都能复现
[demo.zip](https://github.com/mpflutter/mpflutter/files/14444409/demo.zip)

**Comment by PonyCui** [comment]
第 1，第 4 问题已解决，请使用最新版本。
第 2 不能复现。
