### ISSUE TITLE
MPFlutterTextField设置TextInputType.number数字键盘在ios端还是可以返回输入别的符号,限制不住,安卓这边是正常的可以弹出微信的数字键盘

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#546]
![IMG20240301153502](https://github.com/mpflutter/mpflutter/assets/17779490/0c4d6594-2958-4c39-9bbf-ad62d60f4b60)

**Comment by PonyCui** [comment]
这是讯飞输入法自身的问题，该输入法没有响应 number 类型的正确布局，我们没有办法推动讯飞解决。
尝试使用另外的办法修正，目前在 MPFlutter 中没有正确处理 inputFormatter，通过补充该功能可以满足需求。

**Comment by PonyCui** [comment]
fixed at https://github.com/mpflutter/mpflutter_wechat_plugins/commit/2e4a57286245c6f4ce655617694f3f46ad4de0d7
使用 mpflutter_wechat_editable 0.0.5 版本
