### ISSUE TITLE
MPFlutterImageEncoder.encodeToBytes(image: image, format: MPFlutterImageByteFormat.png,)会导致页面阻塞卡死，有些ios设备甚至微信直接崩溃了

### ISSUE THREAD

**Issue by a395726103** [mpflutter/mpflutter#547]
demo包
[awesome_project.zip](https://github.com/mpflutter/mpflutter/files/14458998/awesome_project.zip)

**Comment by PonyCui** [comment]
fixed at https://github.com/mpflutter/mpflutter/commit/f2a6306ea7e3267b2105e16a8db975803f7764d5
问题原因，base64 decode 超长字符串会导致卡死，新增 encodeToFilePath 方法，可以避免长时间的卡顿。
https://mpflutter.feishu.cn/wiki/LMsrwveMQiwiRskKy8gcsAfWnUf
