### ISSUE TITLE
是否支持支付宝小程序？

### ISSUE THREAD

**Issue by liyafe1997** [mpflutter/mpflutter#548]
如题

**Comment by vmtest888** [comment]
+1

**Comment by PonyCui** [comment]
支付宝小程序对于 webassembly 的限制比较严格，只能在 worker 中执行，并且 worker 只允许企业用户使用。
https://opendocs.alipay.com/mini/0b2bz8
所以，2024 年不会考虑在支付宝中支持，除非支付宝对于 webassebly 有进一步的开放计划。
