### ISSUE TITLE
不能运行ios和安卓应用吗?

### ISSUE THREAD

**Issue by SheepYang1993** [mpflutter/mpflutter#549]
只能运行桌面端和小程序端？

**Comment by PonyCui** [comment]
Flutter 本身就支持 iOS 和 Android，不需要使用 MPFlutter。

**Comment by SheepYang1993** [comment]
我的意思是像同一个工程，既能运行ios/安卓，也能运行小程序。

目前MPFlutter工程只能运行微信小程序是吧。

**Comment by PonyCui** [comment]
> 期望是，同一个flutter工程，既能运行ios/安卓，也能运行小程序。
> 
> 但是目前MPFlutter工程只能运行微信小程序是吧。

你可以在同一个工程运行，使用 kIsMPFlutter 判读环境区分逻辑。
