### ISSUE TITLE
iamge在Column里必须要要指定宽高 不然会出现错位

### ISSUE THREAD

**Issue by zhangruiyu** [mpflutter/mpflutter#55]
@override
  Widget build(BuildContext context) {
    return MPScaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Text('***').fontSize(15),
            Text("1,****")
                .fontSize(15)
                .textStyle(TextStyle(decoration: TextDecoration.underline))
                .textColor(Colors.red)
                .padding(top: 10, bottom: 20)
                .gestures(onTap: () {
              Get.toNamed(Routers.androidFloatPage);
            }),
            Text('2,****)').padding(vertical: 10),
            Image.asset(
              '****',
              width: Get.width,
              height: 500,
            ),
          ],
        ).padding(horizontal: 20, bottom: 40, top: 20),
      ),
    );
  }

**Comment by zhangruiyu** [comment]
```
@override
  Widget build(BuildContext context) {
    return MPScaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Text('***').fontSize(15),
            Text("1,****")
                .fontSize(15)
                .textStyle(TextStyle(decoration: TextDecoration.underline))
                .textColor(Colors.red)
                .padding(top: 10, bottom: 20)
                .gestures(onTap: () {
              Get.toNamed(Routers.androidFloatPage);
            }),
            Text('2,****)').padding(vertical: 10),
            Image.asset(
              '****',
              width: Get.width,
              height: 500,
            ),
          ],
        ).padding(horizontal: 20, bottom: 40, top: 20),
      ),
    );
  }
```

**Comment by zhangruiyu** [comment]
如果给这行去掉,图片会错位
width: Get.width,
height: 500,

**Comment by PonyCui** [comment]
设计如此，Web 应用里必须指定图片宽高。

**Comment by PonyCui** [comment]
尤其是 asset 资源，目前是没有把宽高信息写入 JS 里的，所以就需要写死宽高了。

**Comment by zhangruiyu** [comment]
好的 感谢
