### ISSUE TITLE
mpflutter 2.0 使用 shared_preferences 报错

### ISSUE THREAD

**Issue by OHeroJ** [mpflutter/mpflutter#553]
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

flutter 版本 3.16.7

shared_preferences 2.2.2

**Comment by PonyCui** [comment]
flutter clean
flutter packages get 
然后再试试

**Comment by OHeroJ** [comment]
> flutter clean flutter packages get 然后再试试

有效
