### ISSUE TITLE
官方demo和自己的项目都无法运行进入页面就loading

### ISSUE THREAD

**Issue by mstestlp** [mpflutter/mpflutter#556]
Flutter 版本号：3.16.7
MPFlutter 版本号：2.5.0
操作系统：window
IDE：vscode
作者你好,官方demo和自己的项目都无法运行进入页面就loading,项目没有任何依赖,干干净净的项目,能处理下是什么问题吗
![image](https://github.com/mpflutter/mpflutter/assets/10651998/cb2dfb2e-a990-4ee8-8e5a-eb515b3ce356)

**Comment by PonyCui** [comment]
dart --version 看看版本号，请确认你的 flutter 不是通过 flutter downgrade 降级的，而是直接下载 3.16.7 zip 包解压。

**Comment by mstestlp** [comment]
> dart --version 看看版本号，请确认你的 flutter 不是通过 flutter downgrade 降级的，而是直接下载 3.16.7 zip 包解压。

是fvm的问题,不支持fvm,好像也不支持主题和语言切换

**Comment by PonyCui** [comment]
嗯，看来有必要尽快支持一下 fvm

**Comment by PonyCui** [comment]
这个 issue 先 close，fvm 的支持 issue 在此 https://github.com/mpflutter/mpflutter/issues/527
