### ISSUE TITLE
调用保存手机通讯录，选择创建新联系人时弹出2个保存页面

### ISSUE THREAD

**Issue by quan327886341** [mpflutter/mpflutter#558]
调用wx.addPhoneContact(wx.AddPhoneContactOption()
                                      ..mobilePhoneNumber ="1234567"
                                      ..firstName = "tests"
                                      );
选择创建新联系人会出现2个保存页面，关闭或者保存成功后还有一个保存页面
选择添加到现有联系人时正常
mpflutter_core: ^2.5.1
  mpflutter_build_tools: ^2.4.0
  mpflutter_wechat_api: ^2.2.2

**Comment by PonyCui** [comment]
微信的 BUG，请向微信官方反馈。
https://developers.weixin.qq.com/community/develop/doc/0006c0e2e380b057dcc06356d61000?highLine=wx.addPhoneContact
