### ISSUE TITLE
请问如果从官方的flutter web迁移到这个呢

### ISSUE THREAD

**Issue by zhangruiyu** [mpflutter/mpflutter#56]
mpflutter: // http://0.0.0.0:9898/index.html?route=/abcpage
官方 // http://0.0.0.0:9898/#/abcpage
现在我们移动端是写死的url 怎么兼容官方的处理呢 测试用老的方法onGenerateRoute都不回调

**Comment by PonyCui** [comment]
如果需要迁移的话，可以考虑在 index.html 中写一个中转规则，mpflutter 的 index.html 是可以修改的。

**Comment by PonyCui** [comment]
如果不需要迁移的话，则不用考虑这个问题，直接用新的就可以了。

**Comment by zhangruiyu** [comment]
很懵  没写过前端 完全不知道咋开始搞 index.html 里面怎么中转都不知道...

**Comment by zhangruiyu** [comment]
大佬能给个例子吗..

**Comment by PonyCui** [comment]
建议你可以先尝试开发，开发完成以后再考虑迁移问题，迁移过程有问题可以选择一对一技术支持，这是没有问题的。

**Comment by zhangruiyu** [comment]
其实我这边是做自己app的线上用(内容不复杂,做教程h5) 迁移原因是因为flutter web打包出来体积太大 加载太慢了
目前已经迁移到mp_flutter完了 但是就是这个和线上有冲突

**Comment by PonyCui** [comment]
你可以在 `web/index.html` 添加以下代码，应该可解决迁移问题。
```
    <script>
        if (window.location.hash) {
            window.location.href = "index.html?route=" + window.location.hash.replace("#", "");
        }
    </script>
```
如果仍然存在问题，你可以继续在这里提问，补充更多信息。

**Comment by zhangruiyu** [comment]
好的 真的非常感谢
