### ISSUE TITLE
flutter 3.19 支持有具体时间吗

### ISSUE THREAD

**Issue by BeiYinZhiNian** [mpflutter/mpflutter#569]
看起来不错，现在有项目想用，但是要flutter3.19，有没有具体时间

**Comment by PonyCui** [comment]
可能会通过 fvm 提供 3.19 和 3.22 的支持，具体还在研究中。

**Comment by jekiki** [comment]
3.22已经支持wasm编译了，会不会提供更简化的方式通过flutter来开发小程序。

**Comment by PonyCui** [comment]
> 3.22已经支持wasm编译了，会不会提供更简化的方式通过flutter来开发小程序。

不会，因为小程序宿主不太可能在短期内支持 wasm gc。

**Comment by Silentdoer** [comment]
直接支持flutter3.22吧，这个版本更新了很多有用的功能，安卓的升级为了impaller，支持了wasm gc，有了json宏

**Comment by PonyCui** [comment]
MPFlutter 2.7.0 版本已支持 Flutter SDK 3.22
