### ISSUE TITLE
build webapp 和 weapp时失败

### ISSUE THREAD

**Issue by lihehehehe** [mpflutter/mpflutter#57]
eMacBook-Pro-2 awesome_project % dart scripts/build_weapp.dart
正在构建...
/bin/sh: dart2js: command not found
Unhandled exception:
dart2js 命令执行失败。
#0      _buildDartJS (package:mp_build_tools/build_weapp.dart:74:5)
#1      main (package:mp_build_tools/build_weapp.dart:24:3)
#2      main (file:///Users/lihe/Develop/miniprogram_project/awesome_project/scripts/build_weapp.dart:4:11)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by lihehehehe** [comment]
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (3 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

**Comment by lihehehehe** [comment]
小程序和webapp在本地都可以直接run，但是build的时候报错

**Comment by PonyCui** [comment]
请参照文档配置环境 https://mpflutter.com/zh/docs/install-macos

在终端命令行中依次执行以下命令，如果存在任一命令报错，请重新检查 Flutter 是否正确安装。
flutter --version

dart --version

dart2js --version

**Comment by lihehehehe** [comment]
多谢 已解决 ！

**Comment by liudonghua123** [comment]
`export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"`
