### ISSUE TITLE
assets下高清图片无法显示

### ISSUE THREAD

**Issue by shitb** [mpflutter/mpflutter#571]
flutter版本: 3.16.7
mpflutter: 2.6.0
系统: mac 

使用 Image.asset 加载本地图片
错误信息:
while trying to load an asset: Error: readCompressedFileSync:fail /assets1/assets/image/3.0x/ic_school_list.png.br not absolute path

如果删掉3.0x和2.0x文件夹没问题, 考虑到以后可能还要打包app, 所以想保留高倍图

![image](https://github.com/mpflutter/mpflutter/assets/4415390/1d01ed8f-b6dc-42db-95ba-8d7da2a3de42)

**Comment by PonyCui** [comment]
应该是微信小程序对于路径的识别有问题，我适配一下这种情况。
