### ISSUE TITLE
TextField、TextFormField IOS IPAD 收起输入法高度没恢复，MPFlutterTextField、MPFlutterTextFormField hintText 漂浮在其他组件上

### ISSUE THREAD

**Issue by Dabao-Su** [mpflutter/mpflutter#572]
Flutter 版本号：3.16.4
MPFlutter 版本号：2.6.0
操作系统：macOS 12.7.4
IDE：IDEA

TextField、TextFormField 在 IOS IPAD 小程序中，点击讯飞输入法、苹果自带输入法等的▽收起键盘按钮，键盘收起后 TextField、TextFormField 的高度没有恢复，直接 web 在 IOS IPAD 微信内打开，点击输入法收起按钮高度恢复正常，后续使用 MPFlutterTextField、MPFlutterTextFormField ，IOS IPAD 安卓小程序内文字都会漂浮在其他组件上层，而且明显有卡顿感……

https://github.com/mpflutter/mpflutter/assets/28138470/6147c108-cdf1-4225-8e6b-cc407beb3c7e

![image](https://github.com/mpflutter/mpflutter/assets/28138470/4df7cd10-ff57-438c-a5f8-fc5b54fe40c7)

**Comment by PonyCui** [comment]
我用 iPad 系统自带输入法测试，没有发现键盘收起后，高度没有恢复的问题。

**Comment by Dabao-Su** [comment]
> 我用 iPad 系统自带输入法测试，没有发现键盘收起后，高度没有恢复的问题。

我直接改 awesome_project 测试也是有问题，ipadOS 版本是：16.4.1
不是点击输入法的回车键，是点击键盘收起键有问题

![image](https://github.com/mpflutter/mpflutter/assets/28138470/a09b5767-a872-4a3a-ad35-a63be9281f9e)

**Comment by PonyCui** [comment]
我在两台 iPad 上进行相同操作，并没有出现这个问题，请使用最新版本再测试一次，如果仍然存在问题可以重开 issue。

**Comment by Anayuta** [comment]
platform_view.js 处的方法disposeView执行delete self["onPVCB_" + viewOption.pvid];异常了。Object.isFrozen(self)返回的是true，这个self是个frozen对象。 我看updateView处绑定了这个 self["onPVCB_" + viewOption.pvid] = (e) => {
      self.onPVCB(e, viewOption.pvid);
    }，但是实际上没看到有任何调用。这里绑定的是不是可以去掉？然后disposeView处的delete也可以去掉？

**Comment by PonyCui** [comment]
> platform_view.js 处的方法disposeView执行delete self["onPVCB_" + viewOption.pvid];异常了。Object.isFrozen(self)返回的是true，这个self是个frozen对象。 我看updateView处绑定了这个 self["onPVCB_" + viewOption.pvid] = (e) => { self.onPVCB(e, viewOption.pvid); }，但是实际上没看到有任何调用。这里绑定的是不是可以去掉？然后disposeView处的delete也可以去掉？

具体的异常可以发一下吗
