### ISSUE TITLE
demo无法编译是什么

### ISSUE THREAD

**Issue by cocolala317** [mpflutter/mpflutter#573]
<img width="1377" alt="image" src="https://github.com/mpflutter/mpflutter/assets/14327254/bf1ae6d5-06ce-46a6-8671-0d8d69f7a56e">
这个[es_compression](https://github.com/instantiations/es_compression)库里面的一个方法找不到，我不知道是什么原因造成的，demo无法编译。我以为是demo引入了某个我实际用不到的库，但我用自己的项目执行这个命令也同样是这个错误，谁能帮我解答一下。

**Comment by PonyCui** [comment]
fvm dart scripts/build_wechat.dart

**Comment by cocolala317** [comment]
> fvm dart scripts/build_wechat.dart

好的 谢谢
