### ISSUE TITLE
问下开发微信小程序可以使用dart的isolate功能吗？

### ISSUE THREAD

**Issue by Silentdoer** [mpflutter/mpflutter#575]
如题

**Comment by PonyCui** [comment]
不可以

**Comment by Silentdoer** [comment]
> 不可以

那如果用mpflutter开发的小程序有一些本地计算的功能，需要不影响UI线程一般是怎么处理呢？

**Comment by PonyCui** [comment]
可以使用微信提供的 Worker，但是你需要使用 JS 实现计算。
https://developers.weixin.qq.com/miniprogram/dev/api/worker/wx.createWorker.html
