### ISSUE TITLE
使用fvm编译出错请教要怎么处理

### ISSUE THREAD

**Issue by aohanhe** [mpflutter/mpflutter#579]
我今天下载模板下来测试，使用fvm安装了3.16.7，
fvm dart --version                
Dart SDK version: 3.2.4 (stable) (Thu Dec 21 19:13:53 2023 +0000) on "macos_arm64"
但是在执行：fvm dart scripts/build_wechat.dart
遇到：
The current Dart SDK version is 2.19.6.

Because awesome_project requires SDK version >=3.1.5 <4.0.0, version solving failed.
这要怎么解决呢？

**Comment by aohanhe** [comment]
我发现执行的指令没有使用fvm的dart,而是用了之前我安装的版本
pub get failed
command: "/Users/aohanhe/development/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/aohanhe/development/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:verify:web",
  "PUB_CACHE": "/Users/aohanhe/.pub-cache",
}
这是不是bug?

**Comment by aohanhe** [comment]
我卸载了fvm之外的那个版本，终于正常了。

**Comment by ksxkq** [comment]
用 fvm 设置成 global，应该也可以
