### ISSUE TITLE
测试发现 flutter端用mp_flutter生成的web,然后flutter app里调用里直接加载h5某个url  canGoBack 会返回true 然后返回会返回到首页

### ISSUE THREAD

**Issue by PonyCui** [mpflutter/mpflutter#58]
测试发现 flutter端用mp_flutter生成的web,然后flutter app里调用里直接加载h5某个url  canGoBack 会返回true 然后返回会返回到首页

_Originally posted by @zhangruiyu in https://github.com/mpflutter/mpflutter/issues/54#issuecomment-1005551330_

**Comment by zhangruiyu** [comment]
找到问题在哪了 但是不知道怎么解决
就是另外一个问题 加了下面这个解决官方跳转兼容问题 结果导致访问原来官方打包出来的页面路径 按返回键有问题 但是用mpflutter打包出来的路径访问没问题
```
if (window.location.hash) {
            window.location.href = "index.html?route=" + window.location.hash.replace("#", "");
        }
```

**Comment by PonyCui** [comment]
@zhangruiyu 用的是什么 WebView 插件？

**Comment by zhangruiyu** [comment]
举个例子
mp打包的
移动端访问: https://0.0.0.0/index.html?route=abcPage 返回键没任何问题
但是加了上面代码做了兼容,去访问https://0.0.0.0/#/abcPage 会导致返回键有问题
webview用的是官方的webview_flutter

**Comment by PonyCui** [comment]
试试
```
    <script>
        if (window.location.hash) {
            window.location.replace("index.html?route=" + window.location.hash.replace("#", ""));
        }
    </script>
```

**Comment by zhangruiyu** [comment]
还是不行的

**Comment by PonyCui** [comment]
看上去是 Android WebView 的 BUG，可以试试以下方案。
```
    <script>
        if (window.location.hash) {
            window.history.replaceState(null, "", "index.html?route=" + window.location.hash.replace("#", ""));
            window.history.go(0);
        }
    </script>
```

**Comment by zhangruiyu** [comment]
可以了  感谢
