### ISSUE TITLE
小程序使用Listener组件抬手事件不触发

### ISSUE THREAD

**Issue by as-zlq** [mpflutter/mpflutter#583]
Listener(
      onPointerMove: (PointerMoveEvent move) => print('move'),
      onPointerUp: (PointerUpEvent event) => print('up'),
      child: Material(
        color: Colors.red,
        child: SizedBox(
          height: 60,
          width: 100,
        ),
      ),
    );

小程序运行后，长按移动后，抬手事件不触发
mpflutter_build_tools 2.7.1
小程序版本3.5.0

**Comment by PonyCui** [comment]
已修复，mpflutter_build_tools 使用 2.7.4
