### ISSUE TITLE
添加shared_preferences: ^2.3.2后会出现以下报错

### ISSUE THREAD

**Issue by jack8525** [mpflutter/mpflutter#589]
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
Error: Couldn't resolve the package 'audioplayers_web' in 'package:audioplayers_web/audioplayers_web.dart'.
Error: Couldn't resolve the package 'device_info_plus' in 'package:device_info_plus/src/device_info_plus_web.dart'.
Error: Couldn't resolve the package 'image_picker_for_web' in 'package:image_picker_for_web/image_picker_for_web.dart'.
Error: Couldn't resolve the package 'package_info_plus' in 'package:package_info_plus/src/package_info_plus_web.dart'.
.dart_tool/flutter_build/9a82f01c7aeec3f9283b47ed44b8f730/web_plugin_registrant.dart:10:8:
Error: Not found: 'package:audioplayers_web/audioplayers_web.dart'
import 'package:audioplayers_web/audioplayers_web.dart';
       ^
.dart_tool/flutter_build/9a82f01c7aeec3f9283b47ed44b8f730/web_plugin_registrant.dart:11:8:
Error: Not found: 'package:device_info_plus/src/device_info_plus_web.dart'
import 'package:device_info_plus/src/device_info_plus_web.dart';
       ^
.dart_tool/flutter_build/9a82f01c7aeec3f9283b47ed44b8f730/web_plugin_registrant.dart:12:8:
Error: Not found: 'package:image_picker_for_web/image_picker_for_web.dart'
import 'package:image_picker_for_web/image_picker_for_web.dart';
       ^
.dart_tool/flutter_build/9a82f01c7aeec3f9283b47ed44b8f730/web_plugin_registrant.dart:13:8:
Error: Not found: 'package:package_info_plus/src/package_info_plus_web.dart'
import 'package:package_info_plus/src/package_info_plus_web.dart';
       ^
.dart_tool/flutter_build/9a82f01c7aeec3f9283b47ed44b8f730/web_plugin_registrant.dart:19:8:
Error: Undefined name 'AudioplayersPlugin'.
try {  AudioplayersPlugin.registerWith(registrar);} catch (e) { print("  AudioplayersPlugin.registerWith(registrar); 插件注册失败，可能是该插件未适配 MPFlutter 导致。"); }
       ^^^^^^^^^^^^^^^^^^
.dart_tool/flutter_build/9a82f01c7aeec3f9283b47ed44b8f730/web_plugin_registrant.dart:20:8:
Error: Undefined name 'DeviceInfoPlusWebPlugin'.
try {  DeviceInfoPlusWebPlugin.registerWith(registrar);} catch (e) { print("  DeviceInfoPlusWebPlugin.registerWith(registrar); 插件注册失败，可能是该插件未适配 MPFlutter 导致。"); }
       ^^^^^^^^^^^^^^^^^^^^^^^
.dart_tool/flutter_build/9a82f01c7aeec3f9283b47ed44b8f730/web_plugin_registrant.dart:21:8:
Error: Undefined name 'PackageInfoPlusWebPlugin'.
try {  PackageInfoPlusWebPlugin.registerWith(registrar);} catch (e) { print("  PackageInfoPlusWebPlugin.registerWith(registrar); 插件注册失败，可能是该插件未适配 MPFlutter 导致。"); }
       ^^^^^^^^^^^^^^^^^^^^^^^^

机器是macos 14.6.1, fvm use 3.22.0
去掉就没报错

**Comment by PonyCui** [comment]
flutter clean

**Comment by jack8525** [comment]
> flutter clean

its work!
