### ISSUE TITLE
powerShell管理员执行模板工程.\mpflutter packages get报错

### ISSUE THREAD

**Issue by qinrunhao** [mpflutter/mpflutter#593]
已经使用管理员打开powerShell，在模板工程下执行命令：./mpflutter packages get，报下面错误
![微信截图_20240926101606](https://github.com/user-attachments/assets/ef3a8ef3-d9a0-4da8-827f-b20135674522)

**Comment by PonyCui** [comment]
不要使用 v1.0，已经废弃。

**Comment by qinrunhao** [comment]
[mpflutter_template](https://github.com/mpflutter/mpflutter_template)是v1.0版本吗？那哪里有高版本的？

**Comment by qinrunhao** [comment]
@PonyCui [mpflutter_template](https://github.com/mpflutter/mpflutter_template)是v1.0版本吗？那哪里有高版本的？

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter 看 readme
