### ISSUE TITLE
Flutter 3.24.3 不支持吗？

### ISSUE THREAD

**Issue by ligbyte** [mpflutter/mpflutter#595]
Flutter 3.24.3 不支持吗？
<img width="791" alt="截屏2024-09-27 01 26 23" src="https://github.com/user-attachments/assets/d2323ff2-9240-4b8b-b154-86dbf6abef69">

**Comment by ligbyte** [comment]
<img width="570" alt="截屏2024-09-27 01 38 19" src="https://github.com/user-attachments/assets/f6886810-73d1-4cec-9e9b-9fc3be9b194c">

**Comment by PonyCui** [comment]
这个问题是小程序开发者工具的问题，mpflutter 已支持 3.24
