### ISSUE TITLE
运行官方的awesome_wegame_template预览报错

### ISSUE THREAD

**Issue by godot2d** [mpflutter/mpflutter#597]
wechat_devtools版本：1.06.2407120
系统：win11

message：预览 Error: 非法的文件，错误信息：source package include invalid file : /assets/pages/index.wxml [20240928 16:25:08][wxcbc5e0f2c1619394]
appid: wxcbc5e0f2c1619394
openid: o6zAJs9dnpNK-B0k2LZcDuA8Oj7U
ideVersion: 1.06.2407120
osType: win32-x64
time: 2024-09-28 16:25:36

flutter.bat --version
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (2 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

**Comment by PonyCui** [comment]
fixed at https://github.com/mpflutter/mpflutter_build_tools/commit/48397e1c3beb3b337feda175272943b2dd6c3f96
