### ISSUE TITLE
怎么打开一个新tab页

### ISSUE THREAD

**Issue by zhangruiyu** [mpflutter/mpflutter#60]
![image](https://user-images.githubusercontent.com/10591822/148322931-f3f1c7d4-9e57-419a-a62d-f72dedcced76.png)
之前可以通过launch插件直接打开 但是现在不知道咋搞了

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/148323163-5c0e7f7b-7df5-4967-bc55-08370843cecc.png)
这样也不行
js.context.callMethod('open', ['https://stackoverflow.com/questions/ask']);

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/148323249-f6ca4246-444b-4a7c-b4ed-40abefd453cd.png)
import 'dart:html' as html;

// ...

html.window.open('https://stackoverflow.com/questions/ask', 'new tab');
这样好像也不行

**Comment by zhangruiyu** [comment]
目前就差这个 就基本完成 可以上线了 卡这里了

**Comment by PonyCui** [comment]
```
import 'package:mpcore/mpjs/mpjs.dart' as mpjs;
```

可以替代 dart:js

**Comment by PonyCui** [comment]
不要使用其它插件

**Comment by zhangruiyu** [comment]
好的 解决了
