### ISSUE TITLE
分包超出大小，有处理方案吗

### ISSUE THREAD

**Issue by chdown** [mpflutter/mpflutter#604]
![image](https://github.com/user-attachments/assets/8478f6ea-fa0e-4080-bb82-b2c7c795bd51)

**Comment by stoneLee81** [comment]
assets的图片放到cdn上去，代码分包可以参考作者的demo deferred部分，还有，你这代码有多少啊，怎么这么大

**Comment by chdown** [comment]
> assets的图片放到cdn上去，图片用webp的压缩格式，代码分包可以参考作者的demo deferred部分，还有，你这代码有多少啊，怎么这么大

我们目前做的是一个管理类的app，功能和页面确实很多很复杂，目前我是在已上线的项目上进行转化小程序的尝试，最终只要能处理分包的话就问题不大。

**Comment by stoneLee81** [comment]
图片压缩后到cdn；mpflutter是不会给你自动分包的，你要自己代码分包，最好是能将代码package到另一个项目目录，做少关联，分包关联的也会一并打到小程序里面

**Comment by chdown** [comment]
> assets的图片放到cdn上去，图片用webp的压缩格式，代码分包可以参考作者的demo deferred部分，还有，你这代码有多少啊，怎么这么大

我们目前也在做鸿蒙版本的适配，所以提个建议就看能不能和鸿蒙插件这种类似，做常用插件的适配，这样我觉得使用面会更广一点。热刷新就看能不能和uniapp这种类似，具体还没研究，个人的一点点使用体验

**Comment by chdown** [comment]
> 图片压缩后到cdn；mpflutter是不会给你自动分包的，你要自己代码分包，最好是能将代码package到另一个项目目录，做少关联，分包关联的也会一并打到小程序里面

好的，感谢回复
