### ISSUE TITLE
怎么清除构建的缓存

### ISSUE THREAD

**Issue by liangb123** [mpflutter/mpflutter#606]
每次都是用dart scripts/build_wechat.dart 构建的。
我发现，删除了分包的代码，但是通过dart scripts/build_wechat.dart 构建的产物，还是会有之前构建的分包的东西。

例如： 第一次构建时，在main函数中，进行了分包操作。
a.loadLibrary()
b.loadLibrary()
c.loadLibrary()
build产物中有pkg0 ->main.dart.js_2.part.js，pkg1->main.dart.js_3.part.js, main.dart.js_3.part.js等等

后面删除了a.loadLibrary() b.loadLibrary() c.loadLibrary()
重新构建后，产物里还有pkg0 ->main.dart.js_2.part.js，pkg1->main.dart.js_3.part.js, main.dart.js_3.part.js。  这显然是不对的。

<img width="349" alt="image" src="https://github.com/user-attachments/assets/62b78605-1bbe-42e3-8c6b-abf127e6d84d">

想问下，要怎么删除缓存，保证每次构建的都是最新的，不收之前的影响。

**Comment by PonyCui** [comment]
flutter clean

**Comment by liangb123** [comment]
> flutter clean
okok。 可以了。 非常感谢
