### ISSUE TITLE
怎么支持flutter Isolate

### ISSUE THREAD

**Issue by liangb123** [mpflutter/mpflutter#607]
经测试发现，不支持isolate。
报错如下:
Unsupported operation: new RawReceivePort
![Uploading image.png…]()

但是,项目中一些复杂的场景需要用到isolate, 这个怎么解决呢

**Comment by PonyCui** [comment]
不支持的，JS 本身就没有多线程支持。

**Comment by liangb123** [comment]
> 不支持的，JS 本身就没有多线程支持。

compute 可以用吗

**Comment by PonyCui** [comment]
可以用，但都是在主线程运行，这是 flutter 和 web 的限制。

**Comment by liangb123** [comment]
> 可以用，但都是在主线程运行，这是 flutter 和 web 的限制。

MPFlutter支持 web worker吗。

**Comment by liangb123** [comment]
> > 可以用，但都是在主线程运行，这是 flutter 和 web 的限制。
> 
> MPFlutter支持 web worker吗。

我在微信官网找到了。
