### ISSUE TITLE
开发有关微信插件的package,真机调试白屏

### ISSUE THREAD

**Issue by jack8525** [mpflutter/mpflutter#608]
在项目的app.json中加入了微信的蓝牙mesh插件
`"plugins": {
    "ble-mesh-plugin": {
      "version": "latest",
      "provider": "wx013447465d3aa024"
    }
  }`
然后,真机预览会白屏.而mac desktop和小程序模拟器正常
请问这是为什么呢

**Comment by PonyCui** [comment]
看看 console 报什么错

**Comment by jack8525** [comment]
> 看看 console 报什么错

![image](https://github.com/user-attachments/assets/2e423f0a-2893-46d7-800e-c76d4b649693)

**Comment by PonyCui** [comment]
不要用真机调试，用预览。

**Comment by jack8525** [comment]
> 不要用真机调试，用预览。

![601732674708_ pic](https://github.com/user-attachments/assets/fb270181-b089-45f3-9209-79611ed2e6a7)
![591732674707_ pic](https://github.com/user-attachments/assets/2064246e-2e6c-403d-bce0-53be977af7c9)

**Comment by jack8525** [comment]
预览也一样是白屏,报错看不懂

**Comment by PonyCui** [comment]
通过这个 commit 暂时修复，可能是微信的问题。
https://github.com/mpflutter/mpflutter_build_tools/commit/7b4342b7b1f6fdeaf87a2d1ce270ec090bef4b19

pubspec 使用以下依赖

dependency_overrides: 
  mpflutter_build_tools: 
    git:
      url: https://github.com/mpflutter/mpflutter_build_tools.git
      ref: master


scripts/build_wechat.dart
中声明 build_tools.fixObjectDefinePropertyIssue = true;

**Comment by icofans** [comment]
> 在项目的app.json中加入了微信的蓝牙mesh插件 `"plugins": { "ble-mesh-plugin": { "version": "latest", "provider": "wx013447465d3aa024" } }` 然后,真机预览会白屏.而mac desktop和小程序模拟器正常 请问这是为什么呢

问一下, usingComponents配置在哪添加
