### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wxzhuanshu** [mpflutter/mpflutter#61]
运行mpflutter的demo 只能在 浏览器上调试吗 不能在 安卓和ios 的模拟器上运行吗

**Comment by wxzhuanshu** [comment]
是这个框架只支持在 web端和小程序上

**Comment by wxzhuanshu** [comment]
flutter run 运行后 在chrome 显示空白 （ flutter run
╔══════════════════════════════════════════════════════

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             11.4s
）

**Comment by PonyCui** [comment]
请按照文档一步一步走。
