### ISSUE TITLE
有适配到Flutter 3.22及以上版本的计划吗？

### ISSUE THREAD

**Issue by seakeylife** [mpflutter/mpflutter#615]
有适配到Flutter 3.22及以上版本的计划吗？
目前出于一定原因，我们计划升级到3.22版本，来保证与其他平台的对齐。同时我们也想尝试使用Flutter来开发小程序。但目前这块无法匹配上，如果有大致的时间计划，我们好安排对应的节奏，以及做好相关安排

**Comment by PonyCui** [comment]
早就支持了朋友
