### ISSUE TITLE
mpflutter打包后遇到小程序包太大，有拆包的教程么？

### ISSUE THREAD

**Issue by vickyYe2** [mpflutter/mpflutter#616]
原Flutter项目中用到了比较多的媒体文件，想用mpFlutter转小程序，目前看只能打包到 pages/index/index，如果我想要分页面和拆包的话应如何配置，希望有例子说明一下

**Comment by vickyYe2** [comment]
感谢作者解答~还有个问题，mpflutter是否支持本地项目中直接引用呢，我们项目引入了微信的IM聊天工具，他们uuid是3.0.6，mpflutter的uuid版本4.2.0以上，所以想用本地引入的方式修改下uuid的版本，不知道有没有更好的方法兼容依赖包版本的问题

**Comment by PonyCui** [comment]
引用冲突只能你自己解决哦
