### ISSUE TITLE
项目开启报错

### ISSUE THREAD

**Issue by qingyggg** [mpflutter/mpflutter#62]
1.照着文档clone了模板项目，照着搭建完mapflutter后，开启项目报错
`Unhandled exception:
FileSystemException: Exists failed, path = ' https://dart.dev/go/dot-packages-deprecation\lib\weapp\components' (OS Error: 文件名、目录名或卷标语法不正确。
, errno = 123)
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      buildWeappPlugin (package:mp_build_tools/build_plugins.dart:64:10)
#2      main (package:mp_build_tools/build_plugins.dart:23:3)
#3      main (file:///C:/Users/zhong/Desktop/seatune-mp-nft-frontend/scripts/build_plugins.dart:4:11)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
`

**Comment by qingyggg** [comment]
flutter 2.8.1版本

**Comment by PonyCui** [comment]
应该是 windows 下的构建问题，我会再测试一下。

**Comment by PonyCui** [comment]
已修正 windows 下的构建问题，请使用 0.11.2 或重新 clone template。
