### ISSUE TITLE
没有RefreshIndicator，如何实现下拉刷新

### ISSUE THREAD

**Issue by LondonX** [mpflutter/mpflutter#63]
感谢作者无私开源！
没有RefreshIndicator，在小程序中如何实现下拉刷新？只能在`index.json`中设置`enablePullDownRefresh`为true？
如果只能通过设置`enablePullDownRefresh`为true，那么如何控制只允许部分页面刷新？

**Comment by PonyCui** [comment]
只能在index.json中设置enablePullDownRefresh为true，暂时没有其它办法。
可以通过 https://mpflutter.com/zh/docs/weapp-route-page 生成小程序实体 Page 的方式，为每一个路由生成真正的小程序页面，并为每一个页面设置下拉刷新属性。

**Comment by PonyCui** [comment]
后续版本会考虑新增 MPRefreshIndicator，但只能在部分平台上使用，预计只会支持 Web 微信小程序。
