### ISSUE TITLE
线上程序与本机调试的性能差异明显

### ISSUE THREAD

**Issue by moseyah** [mpflutter/mpflutter#65]
在mac上用微信开发者工具调试时，后台数据获取及页面加载等速度尚算流畅，但是正式发布后，线上版本的速度却大打折扣。
网络请求库是用的dio: ^4.0.0，路由也未引入其他第三方库。
请问是小程序自身的制约吗，还是另有原因？

**Comment by PonyCui** [comment]
可否提供实际的数据说明问题？或者提供一个可公开访问的 API 代码，以进一步复现问题。

**Comment by moseyah** [comment]
抱歉，我排查了一下，这和后台数据的获取没有太大关系，因为我测试了单纯调用请求的功能和其他功能，单纯调用请求没有明显的性能差异，真正造成性能差异的点在于：我在获取后台数据前利用了[bip39](https://pub.flutter-io.cn/packages/bip39)这个库进行了前置计算。

**Comment by PonyCui** [comment]
如果是纯计算类的库，在导出成最终产物后，是有可能变慢的，因为最终代码是运行在 JS 上的，JS 的性能比调试时的 Dart JIT Runtime 是较弱的。
你也可以使用其它方式优化这个调用的性能，例如使用 wasm 等方式。

**Comment by moseyah** [comment]
好的，感谢答疑，我会尝试你的建议。
