### ISSUE TITLE
获取依赖时报错导致demo跑不起来

### ISSUE THREAD

**Issue by w51679579** [mpflutter/mpflutter#66]
[mpflutter_template-master] dart pub get
Resolving dependencies...
  characters 1.1.0 (1.2.0 available)
  json_patch 2.1.1 (3.0.0 available)
  meta 1.3.0 (1.7.0 available)
  path 1.8.0 (1.8.1 available)
  path_provider 2.0.7 (2.0.8 available)
  path_provider_android 2.0.8 (2.0.11 available)
  path_provider_linux 2.1.2 (2.1.5 available)
  path_provider_macos 2.0.3 (2.0.5 available)
  path_provider_platform_interface 2.0.1 (2.0.3 available)
  path_provider_windows 2.0.4 (2.0.5 available)
  platform 3.0.2 (3.1.0 available)
  plugin_platform_interface 2.0.2 (2.1.2 available)
  source_span 1.8.1 (1.8.2 available)
  vector_math 2.1.0 (2.1.1 available)
  vm_service 6.2.0 (8.1.0 available)
  win32 2.2.10 (2.3.3 available)
Warning: You are using these overridden dependencies:
! flutter 0.11.1
! flutter_web_plugins 0.11.1
! mpcore 0.11.1
Downloading http 0.13.1...
Pub failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
exit code 1

**Comment by PonyCui** [comment]
请阅读[文档](https://mpflutter.com/zh/docs/first-app-vs#安装依赖)
./mpflutter packages get

**Comment by PonyCui** [comment]
Pub failed to delete entry because it was in use by another process.

这可能是 dart 仍然在被使用导致的？

**Comment by PonyCui** [comment]
如果是在 windows 上使用，请使用管理员模式打开 powershell。

**Comment by w51679579** [comment]
可以了，非常感谢




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "mpflutter/mpflutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mpflutter/mpflutter] 获取依赖时报错导致demo跑不起来 (Issue #66)





 
如果是在 windows 上使用，请使用管理员模式打开 powershell。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w51679579** [comment]
好，我试试，我是windows




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mpflutter/mpflutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mpflutter/mpflutter] 获取依赖时报错导致demo跑不起来 (Issue #66)





 
如果是在 windows 上使用，请使用管理员模式打开 powershell。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w51679579** [comment]
Connecting to VM Service at http://127.0.0.1:61169/7ImNnX_hDbQ=/
lib/main.dart: Warning: Interpreting this as package URI, 'package:mpflutter_template/main.dart'.
lib/main.dart:1
Hot reloading enabled
Listening for file changes at ./lib
Serve on 127.0.0.1:9898
Use browser open http://127.0.0.1:9898/index.html or use MiniProgram Developer Tools import './dist/weapp' for dev.

**开调试后终端的报错，同时谷歌浏览器找不到网页**

Unhandled exception:
FileSystemException: Exists failed, path = ' https://dart.dev/go/dot-packages-deprecation\lib\weapp\components' (OS Error: 文件名、目录名或卷标语法不正确。
, errno = 123)
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      buildWeappPlugin (package:mp_build_tools/build_plugins.dart:64:10)
#2      main (package:mp_build_tools/build_plugins.dart:23:3)
#3      main (file:///C:/Users/86177/Desktop/mpflutter_template-master/scripts/build_plugins.dart:4:11)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
终端进程“C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command dart scripts/build_plugins.dart”已终止，退出代码: 1。

**Comment by w51679579** [comment]
@PonyCui

**Comment by PonyCui** [comment]
FileSystemException: Exists failed, path = ' https://dart.dev/go/dot-packages-deprecation\lib\weapp\components' (OS Error: 文件名、目录名或卷标语法不正确。
这个问题已知，准备修复发版，存在 windows 中。

**Comment by PonyCui** [comment]
今晚就会发一个新版本修正这个 windows 的问题

**Comment by w51679579** [comment]
@PonyCui 顺便想问一下，我可以使用dart的蓝牙插件进行通信吗，还是说蓝牙通信这块得用小程序那边的

**Comment by PonyCui** [comment]
> @PonyCui 顺便想问一下，我可以使用dart的蓝牙插件进行通信吗，还是说蓝牙通信这块得用小程序那边的

你需要使用微信小程序的 API 进行通信的，但目前 https://github.com/mpflutter-plugins/universal_miniprogram_api 尚未对蓝牙 API 进行封装，如果有需要可提需求。

**Comment by w51679579** [comment]
我们这边有这个需求的，之前是原生与flutter通信实现蓝牙通信的，如果能在mpflutter里也能实现这个的话就最好了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mpflutter/mpflutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 晚上6:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mpflutter/mpflutter] 获取依赖时报错导致demo跑不起来 (Issue #66)





  
@PonyCui 顺便想问一下，我可以使用dart的蓝牙插件进行通信吗，还是说蓝牙通信这块得用小程序那边的
  
你需要使用微信小程序的 API 进行通信的，但目前 https://github.com/mpflutter-plugins/universal_miniprogram_api 尚未对蓝牙 API 进行封装，如果有需要可提需求。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PonyCui** [comment]
> 我们这边有这个需求的，之前是原生与flutter通信实现蓝牙通信的，如果能在mpflutter里也能实现这个的话就最好了
> […](#)

好的

**Comment by PonyCui** [comment]
已修正 windows 下的构建问题，请使用 0.11.2 或重新 clone template。
