### ISSUE TITLE
windows依然无法调试

### ISSUE THREAD

**Issue by w51679579** [mpflutter/mpflutter#67]
Unhandled exception:
FileSystemException: Exists failed, path = ' https://dart.dev/go/dot-packages-deprecation\lib\weapp\components' (OS Error: 文件名、目录名或卷标语法不正确。
, errno = 123)
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      buildWeappPlugin (package:mp_build_tools/build_plugins.dart:64:10)
#2      main (package:mp_build_tools/build_plugins.dart:23:3)
#3      main (file:///C:/Users/86177/Desktop/mpflutter_template-master/scripts/build_plugins.dart:4:11)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
终端进程“C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command dart scripts/build_plugins.dart”已终止，退出代码: 1。

**Comment by PonyCui** [comment]
请使用 0.11.2 版本
