### ISSUE TITLE
MPMiniProgramView的状态更新问题

### ISSUE THREAD

**Issue by LondonX** [mpflutter/mpflutter#68]
为解决无`RefreshIndicator`组件的问题(#63)，写了一个`RefreshContainer`类，关键代码如下
```dart
MPMiniProgramView(
    tag: "scroll-view",
    attributes: {
      "refresher-enabled": widget.onRefresh != null,
      "refresher-triggered": widget.isRefreshing,
    },
)
```
但当完成刷新任务后，调用`setState({ isRefreshing = false })`时（由true赋值为false），刷新控件并未复位（收回）。
同样，style也无法通过widget.isRefreshing状态来修改。

目前我的解法
```dart
Container(
    //color、height、width等可触发渲染树更新的操作可用于处理更新refresher-triggered后无法复位的问题。
    color: widget.isRefreshing
        ? AppColor.transparent.withAlpha(1)
        : AppColor.transparent,
    child: MPMiniProgramView(...),
)
```

请问有无更好的解决方案，比如在`MPMiniProgramController`对象中调用强制刷新？

**Comment by LondonX** [comment]
#63

**Comment by PonyCui** [comment]
我先定位一下是不是 kbone 的问题

**Comment by PonyCui** [comment]
升级到 0.11.4 可以使用 MPRefreshIndicator
详见文档 https://mpflutter.com/zh/docs/mp-refresh-indicator
