### ISSUE TITLE
微信小程序模拟器预览没问题，但是真机预览和真机调试都白屏

### ISSUE THREAD

**Issue by ran7878** [mpflutter/mpflutter#69]
[sitemap 索引情况提示] 根据 sitemap 的规则[0]，当前页面 [pages/index/index] 将被索引
VM303 WAService.js:2 Sat Jan 22 2022 19:48:59 GMT+0800 (中国标准时间) Free data
VM303 WAService.js:2 Free data with key "kboneRender" of page "pages/index/index" seems not a simple value. Result of deep cloning this value in page instantiation may be unexpected. Consider assigning this value at the beginning of onLoad method.
D @ VM303 WAService.js:2
create @ VM303 WAService.js:2
Ht @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
Jt @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
te.emit @ VM303 WAService.js:2
emit @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
te.emit @ VM303 WAService.js:2
emit @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
c @ VM9 asdebug.js:1
u @ VM9 asdebug.js:1
(anonymous) @ VM9 asdebug.js:1
f @ VM9 asdebug.js:1
g @ VM9 asdebug.js:1
(anonymous) @ VM9 asdebug.js:1
_ws.onmessage @ VM9 asdebug.js:1
[sitemap 索引情况提示] 根据 sitemap 的规则[0]，当前页面 [pages/index/index?route=%2Fsecond] 将被索引
VM303 WAService.js:2 Sat Jan 22 2022 19:49:28 GMT+0800 (中国标准时间) Free data
VM303 WAService.js:2 Free data with key "kboneRender" of page "pages/index/index" seems not a simple value. Result of deep cloning this value in page instantiation may be unexpected. Consider assigning this value at the beginning of onLoad method.
D @ VM303 WAService.js:2
create @ VM303 WAService.js:2
Ht @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
Jt @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
te.emit @ VM303 WAService.js:2
emit @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
te.emit @ VM303 WAService.js:2
emit @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
(anonymous) @ VM303 WAService.js:2
c @ VM9 asdebug.js:1
u @ VM9 asdebug.js:1
(anonymous) @ VM9 asdebug.js:1
f @ VM9 asdebug.js:1
g @ VM9 asdebug.js:1
(anonymous) @ VM9 asdebug.js:1
_ws.onmessage @ VM9 asdebug.js:1
[sitemap 索引情况提示] 根据 sitemap 的规则[0]，当前页面 [pages/index/index] 将被索引

**Comment by PonyCui** [comment]
真机预览和真机调试需要修改 app.js 中的 IP
https://mpflutter.com/zh/docs/first-app-weapp#真机调试
