### ISSUE TITLE
升级0.11.3 尺寸计算出现问题

### ISSUE THREAD

**Issue by itMcdull** [mpflutter/mpflutter#70]
原版本0.11.0 代码不变的情况下升级0.11.3 
出现错误提示
`FormatException: Unexpected character (at character 1)
AssetManifest.json`
页面尺寸计算出现大幅偏差
demo地址https://github.com/itMcdull/apex_wechat

**Comment by PonyCui** [comment]
升级到 0.11.4 可解决问题。
