### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by moseyah** [mpflutter/mpflutter#73]
我想通过`Navigator.of(context).pushNamedAndRemoveUntil('/profile', (route) => false);`清除历史路由并入栈新路由，但最终结果并未清除历史路由。

**Comment by PonyCui** [comment]
暂未支持这个方法

**Comment by moseyah** [comment]
那如果我想清除历史路由，现在有什么有效的替代方法吗？

**Comment by PonyCui** [comment]
可以尝试使用 popUntil + pushNamed

**Comment by jackie099** [comment]
> 可以尝试使用 popUntil + pushNamed

      Navigator.of(context).popUntil((Route<dynamic> route) => false);
会Throw：
RangeError (index): Invalid value: Valid value range is empty: -1

**Comment by PonyCui** [comment]
OK，我会尽快支持这一特性，预计本周会发布一个版本。

**Comment by PonyCui** [comment]
fixed https://github.com/mpflutter/mpflutter/commit/f10f1d8ceb6af9bf475dec38a5c6203a42e393ad
使用 0.12.0 版本即可
