### ISSUE TITLE
模板工程执行.\mpflutter packages get报错

### ISSUE THREAD

**Issue by philos3** [mpflutter/mpflutter#74]
Warning: You are using these overridden dependencies:
! flutter 0.11.4
! flutter_web_plugins 0.11.4
! mpcore 0.11.4
Pub failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
Running "flutter pub get" in awesome_project...
pub get failed (1; in the directory open in another application.)

**Comment by PonyCui** [comment]
如果是在 windows 上使用，请使用管理员模式打开 powershell。
