### ISSUE TITLE
升级到flutter2.10.0。布局失效了

### ISSUE THREAD

**Issue by vecharm** [mpflutter/mpflutter#76]
先前是flutter2.8使用MPMainTabView，切换tab都要等好几秒才有反应。现在升级到flutter2.10.0。切换tab反应很快，web页面的布局是正常的，小程序的失效了
![image](https://user-images.githubusercontent.com/25290829/153104163-42a0af1e-97ea-4992-b527-2159f60b8d98.png)
![image](https://user-images.githubusercontent.com/25290829/153104105-00d1bc35-d218-473f-82ec-aef05beee27d.png)

**Comment by PonyCui** [comment]
> 我的flutter 版本是2.10 ，如果有布局错位的情况下，点击下微信开发者工具的 编译 就好了。

感觉是微信开发者工具的问题，重启试试也是不错的办法。
