### ISSUE TITLE
小程序 真机 无法显示

### ISSUE THREAD

**Issue by freedomcandy** [mpflutter/mpflutter#77]
根据文档 使用微信开发者工具导入 weapp 后，想使用 真机调试，扫描二维码后，真机上小程序是白色背景，没有展示内容。开发者工具有报错 提示 module "mp-custom-components.js" is not defined

**Comment by PonyCui** [comment]
你需要修改 weapp/app.js 文件，将其中的 127.0.0.1 替换为你的电脑局域网 IP。

https://mpflutter.com/zh/docs/first-app-weapp#真机调试
