### ISSUE TITLE
小程序分享功能报错

### ISSUE THREAD

**Issue by moseyah** [mpflutter/mpflutter#79]
点击小程序右上角的**发送给朋友**，在微信开发者工具会报这样的错：
`
TypeError: Cannot read property 'title' of null
`
应该是没有读到小程序的名称，但我试着改动`mpdom.min.js`中的`onShareAppMessage`方法，让此方法直接返回一个Object，仍然会出现相同的报错。

**Comment by PonyCui** [comment]
不要改动 mpdom.min.js
你需要在 MPScaffold 中的 onWechatMiniProgramShareAppMessage 返回 Object。

**Comment by PonyCui** [comment]
一般而言，至少需要返回以下信息。
{
 'title': '123123',
 'path': '/pages/index/index?route=theflutterroute',
}

**Comment by moseyah** [comment]
感谢指导。另外有一点小建议，这样的功能应该在文档中的微信小程序模块有所提及，当我想要实现分享功能的时候，我的第一反应就是查看文档的微信小程序模块。

**Comment by PonyCui** [comment]
> 感谢指导。另外有一点小建议，这样的功能应该在文档中的微信小程序模块有所提及，当我想要实现分享功能的时候，我的第一反应就是查看文档的微信小程序模块。

好的，这一块也准备优化调整一下。
