### ISSUE TITLE
在android idea中无法进行

### ISSUE THREAD

**Issue by lianlianyi** [mpflutter/mpflutter#80]
看到文档中有该选项,但是我导入到android ide中则没有,启动后chrome页面是空白的,但是我尝试用vscode调试运行则没有问题,请问需要安装什么插件吗?或者哪个步骤有问题导致没有显示出来,谢谢了

![image](https://user-images.githubusercontent.com/1701810/153490236-3d264378-b8aa-4d8e-a172-f2bf474a39ad.png)
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1701810/153490193-98fb14b8-dd85-4cc2-85e6-240c8464044a.png">

**Comment by PonyCui** [comment]
https://mpflutter.com/zh/docs/first-app-as
一步一步照着做
