### ISSUE TITLE
H5中， 跳转页面时， a页面跳转到b页面， 会先显示url地址再显示标题

### ISSUE THREAD

**Issue by huanggui924** [mpflutter/mpflutter#83]
H5中， 跳转页面时， a页面跳转到b页面， 会先显示url地址再显示标题， 目前ios上不会貌似， 在安卓手机上会显示

**Comment by PonyCui** [comment]
在 Push 到下一页的时候，需要给予 MPScaffold 中的 name 一个非空的 String 值，否则会显示 url，这是 Android Chrome 的默认行为。
