### ISSUE TITLE
能构建除微信和百度外其他小程序吗？例如飞书的小程序等

### ISSUE THREAD

**Issue by zouqunli** [mpflutter/mpflutter#85]
若是有的话，能告知下构建方法吗？
![image](https://user-images.githubusercontent.com/17965236/154639358-23eb588f-3f07-4f01-868c-010004a724f3.png)
目前只看到有这两个

**Comment by zouqunli** [comment]
> 目前暂不支持其它小程序，理论上移植到飞书是很简单的，如果你有需要我可以做。
大佬觉得很简单又有兴趣的话，可以多支持几常用的小程序构建，可以方便很多想用flutter的开发者去开发小程序。

**Comment by shitb** [comment]
> 

感觉大佬做出这么牛逼的项目，我觉得目前微信小程序和头条飞书小程序热度最高，大佬如果方便的话，可以优先考虑头条的小程序，感谢

**Comment by shitb** [comment]
> 目前暂不支持其它小程序，理论上移植到飞书是很简单的，如果你有需要我可以做。

感觉大佬做出这么牛逼的项目，我觉得目前微信小程序和头条飞书小程序热度最高，大佬如果方便的话，可以优先考虑头条的小程序，感谢

**Comment by PonyCui** [comment]
> > 目前暂不支持其它小程序，理论上移植到飞书是很简单的，如果你有需要我可以做。
> 
> 感觉大佬做出这么牛逼的项目，我觉得目前微信小程序和头条飞书小程序热度最高，大佬如果方便的话，可以优先考虑头条的小程序，感谢

可以的

**Comment by PonyCui** [comment]
计划在 0.13.0 支持 TT

**Comment by PonyCui** [comment]
0.13.0 已支持飞书、字节小程序，欢迎体验。
