### ISSUE TITLE
树形结构

### ISSUE THREAD

**Issue by shitb** [mpflutter/mpflutter#86]
请问大佬，下图的这种树形控件是不是需要自己手撸，原来flutter控件https://github.com/nabil6391/graphview，现在是不是用不了了，还是需要自己改改还能用。
![image](https://user-images.githubusercontent.com/4415390/155045323-6788cf66-b303-417d-b348-b544694052f8.png)

**Comment by PonyCui** [comment]
你自己改改就好了哦，把不兼容的 widget 去掉。
