### ISSUE TITLE
建议把 mpflutter 相关的 mpcore mp_build_tools 等发布在 https://pub.dev/ 上

### ISSUE THREAD

**Issue by liudonghua123** [mpflutter/mpflutter#87]
我看 `mpflutter.bat` 里面的内容，其实就是设置 dart 库的镜像为 https://pub.mpflutter.com ，所以建议把 `mpflutter` 相关的 `mpcore` `mp_build_tools` 等发布在 https://pub.dev/ 上。

```cmd
set PUB_HOSTED_URL=https://pub.mpflutter.com
flutter %1 %2 %3 %4 %5 %6 %7 %8 %9
```

**Comment by PonyCui** [comment]
暂时还没有这个打算，因为 mpflutter 很多的库都被修改过，是不能上传到 pub.dev 的。
例如：flutter dio 这些。

**Comment by liudonghua123** [comment]
> 因为 mpflutter 很多的库都被修改过，是不能上传到 pub.dev 的。
例如：flutter dio 这些。

这个问题倒好解决，可以fork之后用一个新的名字，例如 mp_dio 或者直接依赖里面使用 github 地址。

**Comment by PonyCui** [comment]
但依赖了 dio 的库也需要同样变更为 mp_dio，还是有不少成本。

**Comment by liudonghua123** [comment]
> 但依赖了 dio 的库也需要同样变更为 mp_dio，还是有不少成本。

嗯，如果发布到 https://pub.mpflutter.com/ 需要很多工作成本，那直接依赖里面使用 github 地址可能是一个很好的方式，这样修改的也可以开源出来，共同处理bug以及合并上游特性等。

单独维护一个 dart 镜像库也需要不少资源和工作量，长远一点其实发布到 https://pub.mpflutter.com/ 会好一点

**Comment by PonyCui** [comment]
长远来看，是需要为 pub.mpflutter.com 创建更易用的 CI 工具。

**Comment by zhanchi88** [comment]
n那也应该随便写个网页，把插件列表列出来。然开发者知道有哪些插件可以用

**Comment by PonyCui** [comment]
> n那也应该随便写个网页，把插件列表列出来。然开发者知道有哪些插件可以用

这个建议不错
