### ISSUE TITLE
iOS动态化方式里，  如何使用flutter 给顶部导航添加控件呢？

### ISSUE THREAD

**Issue by xiaoyao20084321** [mpflutter/mpflutter#93]
iOS原生代码按照教程一行不差，然后在flutter 里面写了appBar
![image](https://user-images.githubusercontent.com/10344550/156091983-b0dfeb65-605f-407f-9eb4-eac66e7023ab.png)
最后实现的效果是这样的
![image](https://user-images.githubusercontent.com/10344550/156092006-cf4df887-aeb6-4bf2-a4e5-68ea4e87f502.png)
我想要的效果是， 这个appBar往上移，盖住Template这一个原生的navagationBar

**Comment by PonyCui** [comment]
可以在 OC 里为 UINavigationController 设置 setNavigationBarHidden = YES。

**Comment by xiaoyao20084321** [comment]
OC里面设置后， 确实会消失， 但是flutter里面MPAppBar组件MediaQuery.of(context).padding.top貌似没起作用，AppBar直接在安全区域外了

**Comment by xiaoyao20084321** [comment]
![image](https://user-images.githubusercontent.com/10344550/156098711-f54c4eb3-afe8-4e45-a488-511046e847fb.png)
打印出来为0

**Comment by PonyCui** [comment]
应该是 bug，已经通过另外的 issue 跟踪。

**Comment by xiaoyao20084321** [comment]
> 应该是 bug，已经通过另外的 issue 跟踪。

好的
