### ISSUE TITLE
小程序中获取手机号的微信api未更新到新版本

### ISSUE THREAD

**Issue by moseyah** [mpflutter/mpflutter#96]
**在使用WechatMiniProgramButton组件获取手机号时，发现返回的json仍是旧版本的格式。**

_旧版本：_
<img width="1035" alt="截屏2022-03-04 上午11 03 27" src="https://user-images.githubusercontent.com/39937957/156691562-bbfda284-d5a8-4ae0-8951-ab4366ad9564.png">

_新版本：_
<img width="1064" alt="截屏2022-03-04 上午11 03 14" src="https://user-images.githubusercontent.com/39937957/156691654-f57f0e96-8e44-4421-bb09-6788e0f546cb.png">

**Comment by PonyCui** [comment]
看上去是基础库会自动处理这个变更？

**Comment by moseyah** [comment]
是的，将微信开发者工具的基础库换到最新就行了，感谢解疑。
